### ISSUE TITLE
ReferenceError: navigator is not defined when use Server Side Rendering

### ISSUE THREAD

**Issue by mSoloYu** [surmon-china/vue-awesome-swiper#1]
ReferenceError: navigator is not defined
    at d:\ws\Vue2Sample\node_modules\swiper\dist\js\swiper.js:3627:22
    at d:\ws\Vue2Sample\node_modules\swiper\dist\js\swiper.js:3629:11
    at Object.<anonymous> (d:\ws\Vue2Sample\node_modules\swiper\dist\js\swiper.js:4430:3)

**Comment by surmon-china** [comment]
1. https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L3527
2. https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L3629
3. https://github.com/nolimits4web/Swiper/blob/master/dist/js/swiper.js#L4430

**Comment by mSoloYu** [comment]
1. let developer use the swiper.js by self.
2. add some check like
`if (typeof window !== 'undefined') { //browser code }`

**Comment by DualWield** [comment]
@mSoloYu so, what do you do to solve this problem ?
