### ISSUE TITLE
[Vue warn]: Failed to resolve directive: swiper

### ISSUE THREAD

**Issue by boneq** [surmon-china/vue-awesome-swiper#103]
Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'slideTo' of undefined"

**Comment by surmon-china** [comment]
Use the ES5 function function expression instead of the arrow function.

`function(swiper) {}` replace to `swiper => {}'`

**Comment by iMomen** [comment]
I still got the same issue
Failed to resolve directive: swiper

**Comment by praveenpandey164** [comment]
My issue is same as yours @iMomen ..Did you find any solution?

**Comment by iMomen** [comment]
Actually I was using the direct injection way, When i have changed my codebase to webpack it's working normally

**Comment by EasonShen1989** [comment]
怎么解决这个问题的呀？

**Comment by shreyas-a** [comment]
Any update on this?

**Comment by zanjs** [comment]
I still got the same issue
Failed to resolve directive: swiper

**Comment by baronkoko** [comment]
Have this warning when using SSR template in SPA project.

**Comment by JamesCushway** [comment]
@surmon-china Any update on this? I keep getting Failed to resolve directive: swiper. How do I resolve this? Do I need to create a custom vue directive?

**Comment by laogui** [comment]
Any update on this?

**Comment by dealslama** [comment]
@surmon-china  Please provide solution.

**Comment by chris-aeviator** [comment]
I was able to get this running by changing the example code

```
<div v-swiper:mySwiper="swiperOption" @someSwiperEvent="callback">
    <div class="swiper-wrapper">
      <div class="swiper-slide" v-for="banner in banners">
        <img :src="banner">
      </div>
    </div>
    <div class="swiper-pagination"></div>
  </div>
```

to use the `<swiper :options="swiperOption">…</swiper>` form instead of `<div v-swiper=…`

**Comment by mrKorg** [comment]
@chris-aeviator I tried this and have error ```Error: render function or template not defined in component: anonymous```
Any update on this?

**Comment by chris-aeviator** [comment]
@mrKorg are you sure you are not having any leftovers from your last try to import it? According to https://github.com/nuxt/nuxt.js/issues/937 (similar issue) that might be the case, second comment:

> 

I've managed to fix this, it was my own stupid mistake  causing the issue. I was still importing and declaring the isotope  component inside my files which wasn't needed as the component was  available to use globally!

Maybe try to create a new project and import only vue-swiper to see if that's the issue

**Comment by 520Girl** [comment]
version  `**"swiper": "^5.3.7",  "vue-awesome-swiper": "^4.1.1",** ` I use in **webpack.prod.conf.js** file configure 
plugins: [
        { src: '~/plugins/i18n.js' },
        { src: '~/plugins/mixins/user.js' },
        { src: '~/plugins/NonSSR-Plugins.js', ssr: false } ,
..................................
]

**Comment by surmon-china** [comment]
Upgrade to v4.x please :)
