### ISSUE TITLE
嵌套swiper两个都是loop的时候，父级swiper循环到第二周第一个的时候，子swiper会卡住（子swiper在子component里面）

### ISSUE THREAD

**Issue by zhuzheng314** [surmon-china/vue-awesome-swiper#107]
`data() {
    return {
      dataHomeIndex: 0,
      swiperOption: {
        notNextTick: true,
        loop: true,
        autoplay: 3000,
        grabCursor: true,
        setWrapperSize: true,
        autoHeight: true,
        paginationClickable: true,
        mousewheelControl: true,
        observeParents: true,
        observer: true,
        debugger: true,
        onTransitionStart: (swiper) => {
          this.dataHomeIndex = swiper.realIndex
          console.log(this.dataHomeIndex)
        },
        onSlideChange: () => {

        }
      }
    }
  },
  computed: {
    swiper() {
      return this.$refs.mySwiper.swiper
    }
  },`

**Comment by zhuzheng314** [comment]
`data() {
    return {
      swiperOption2: {
        notNextTick: true,
        loop: true,
        slidesPerView: 3,
        direction: 'vertical',
        setWrapperSize: true,
        paginationClickable: true,
        autoplay: 1000,
        height: 330,
        observer: true,
        observeParents: true,
        debugger: true,
        onTransitionStart(swiper) {
        },
      };
    };
  },
  computed: {
    swiper() {
      return this.$refs.mySwiper2.swiper
    }
  }`

**Comment by surmon-china** [comment]
1. 请把代码格式化后贴出
2. 请贴出组件内所有代码，包括css和模板

**Comment by zhuzheng314** [comment]
已经解决，是以为swiper  loop 为auto的时候出现的问题

**Comment by taochao1985** [comment]
> 已经解决，是以为swiper loop 为auto的时候出现的问题

hi，我也遇到了这个问题，请问具体是怎么解决的？在线等
