### ISSUE TITLE
设置了autoplay，但是slideTo 到0 的时候，页面会停止autoplay，跳到别的index是可以的

### ISSUE THREAD

**Issue by zhuzheng314** [surmon-china/vue-awesome-swiper#109]
https://user-images.githubusercontent.com/13705072/27318502-4799c52e-55bf-11e7-9a5c-f02e0418afa8.png

**Comment by zhuzheng314** [comment]
配置文件在上面，我有设置autoplayDisableOnInteraction: false,

**Comment by surmon-china** [comment]
每次能不能格式化你的代码再贴出？

**Comment by zhuzheng314** [comment]
我这边不知道为什么格式化不了。。

**Comment by zhuzheng314** [comment]
![image](https://user-images.githubusercontent.com/13705072/27318502-4799c52e-55bf-11e7-9a5c-f02e0418afa8.png)

**Comment by zhuzheng314** [comment]
配置文件是这样

**Comment by surmon-china** [comment]
我下午测试下，这会还在上班

**Comment by zhuzheng314** [comment]
好的

**Comment by surmon-china** [comment]
这个问题遇到了，但是还没有确切可以解决问题的 API
