### ISSUE TITLE
Dynamic sliders on page

### ISSUE THREAD

**Issue by richlloydmiles** [surmon-china/vue-awesome-swiper#110]
## Problem

I have a situation where I need multiple sliders on a page:

```
<div v-swiper:mySwiper="swiperOption">
<div v-for="(item, index) in slider" :key="item.slug">
```

Unfortunately only one of the swiper actually load as `mySwiper`.

Is there any way to get all the swipers to load by making `mySwiper` dynamic?

**Comment by richlloydmiles** [comment]
I solved this by putting each instance into it's own component.

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-awesome-swiper/blob/master/ssr.js#L10

`<div v-swiper="swiperOption" :instanceName="'customSwiperInstanceName'">`
