### ISSUE TITLE
如何监听swiper参数的变动

### ISSUE THREAD

**Issue by pangtengfei** [surmon-china/vue-awesome-swiper#112]
如何监听swiper参数的变动，只有在挂载的时候根据参数初始化

![image](https://user-images.githubusercontent.com/1397432/27677152-3c744ce8-5ce3-11e7-9398-13a02d18b43a.png)

**Comment by surmon-china** [comment]
暂时还不支持

**Comment by surmon-china** [comment]
后续不在支持此需求。

**Comment by oceanvitas** [comment]
请问现在还是不打算支持吗？
那如果我自己watch options然后初始化swiper要怎么触发？
update没有效，以前好像有个reInit方法，但是现在没有了。
请教，谢谢。

**Comment by surmon-china** [comment]
@oceanvitas 用 `v-if`
