### ISSUE TITLE
vue-loader version 13.0.0 break the component ?

### ISSUE THREAD

**Issue by kevinongko** [surmon-china/vue-awesome-swiper#114]
After updating the vue-loader to v13.0.0, I cannot use the component anymore.
https://github.com/vuejs/vue-loader/releases/tag/v13.0.0

#### Vue.js version and component version
- vue v2.3.4
- vue-awesome-swiper v2.5.0
- vue-loader v13.0.0

#### Steps to reproduce
Mount globally
```js
var VueAwesomeSwiper = require('vue-awesome-swiper')
Vue.use(VueAwesomeSwiper)
```

or mount with component

```js
import { swiper, swiperSlide } from 'vue-awesome-swiper'
```

#### What is Expected?
able to use `<swiper>` and `<swiper-slide>` component		

#### What is actually happening?
the component doesn't work and console log shows

```
[Vue warn]: Failed to mount component: template or render function not defined.
```

**Comment by surmon-china** [comment]
v2.5.2 fix it.

**Comment by zuobaiquan** [comment]
[Vue warn]: Failed to mount component: template or render function not defined.
同样遇到过这个问题，下最新的版本就ok了
