### ISSUE TITLE
After the code on-line server, the first load will be stuck, after the F5 refresh, the use of no problem.

### ISSUE THREAD

**Issue by zhou1178539345** [surmon-china/vue-awesome-swiper#115]
There is no problem with local debugging。

**Comment by surmon-china** [comment]
Show me your code.

**Comment by shakegioh** [comment]
Happens with me too.
You can't swipe before reloading the page.

Here is my code:
https://gist.github.com/shakegioh/fbf1a638f9d23bba8f38b46699a425c5

**Comment by surmon-china** [comment]
@shakegioh Thanks for your feedback! I will test.

**Comment by zhou1178539345** [comment]
I found that the simulation in chrome terminal test is will appear Caton, in the real operation of mobile phone is no problem@

**Comment by shakegioh** [comment]
I just experienced the same issue using the swiper itself... Seems that is not an issue of vue-awesome-swiper

**Comment by surmon-china** [comment]
Swiper3 is no longer maintained, Swiper4 may have solved these problems, try to upgrade to v3.0.6, if it still appears, please re-open the problem.
