### ISSUE TITLE
slider not working properly when direction set to vertical

### ISSUE THREAD

**Issue by SiddiquiImran** [surmon-china/vue-awesome-swiper#119]
Hi,

Slider is not working properly when we set direction to vertical and "slidesPerView" to different values.

**Comment by surmon-china** [comment]
Show me your code.

**Comment by EM-PatriciaLopez** [comment]
I have an issue with direction: 'vertical' and slidesPerView.
If I set slidesPerView to any value the slider stops working. If I remove the variable, it works, but the slides get a random height of 36585px;

I was originally working with slider js but had to migrate this project to vue.

**Comment by SiddiquiImran** [comment]
Slider Datais array like of this data:

[ {
          AppName: '',
          Id: 0,
          Client_Id: 0,
          StartDate: '2016-11-23T13:25:29.893',
          SubscriptionActive: false,
          SubGUID: 45456
        }]

Slider Code:

 <swiper-slide v-for='item in apps' :key='item.Id' class="swiper-device-content">
          <div @click="setSelectedAppClick(item.Id)" v-if="item.Id != 0" class="swiper-device" v-bind:class="[item.Id === selectedApp.Id ? 'swiper-device_active' : 'swiper-device_deactive']">
            <div class="app-screen" :style="thumbanil(item.SubGUID)"></div>
          </div>
          <div v-else class="swiper-device swiper-device-newapp_deactive" @click="appCreateClick">
          </div>
          <div v-if="item.Id != 0" class="swiper-appname">
            {{item.AppName}}
          </div>
        </swiper-slide>
      </swiper>


data () {
    return {
      swiperOption: {
        direction: 'vertical',
        slidesPerView: 2
      }
    }
  }

**Comment by SiddiquiImran** [comment]
Even if it re draws after store update it took a random height with value like
2676px or 216756px

**Comment by surmon-china** [comment]
I was in the local test, did not find this problem.
@SiddiquiImran @EM-PatriciaLopez 

```javascript
{
  direction: 'vertical',
  slidesPerView: 3,
   paginationClickable: true,
  spaceBetween: 30,
  loop: true,
  autoplay: 3000,
  autoplayDisableOnInteraction: false
}
```

![swiper](https://user-images.githubusercontent.com/14019524/28428894-64e0a91c-6dad-11e7-9357-39c2447c0b1d.gif)

**Comment by EM-PatriciaLopez** [comment]
If it helps, my slides were either height: 100% or larger.

**Comment by mitkovalkov** [comment]
I have similar problem with the height when i use `direction: 'vertical'` and I fix it adding this option `height : window.innerHeight`

**Comment by surmon-china** [comment]
Yes, any vertical sliding need to rely on your element must have a valid height of such conditions, if it is full-screen sliding, this height should be 100%.



https://github.com/surmon-china/vue-awesome-swiper/blob/master/examples/41-mobile-fullpage-example.vue

**Comment by surmon-china** [comment]
![image](https://user-images.githubusercontent.com/14019524/29447338-07bb3480-83b7-11e7-84b5-26dabbd7030a.png)

**Comment by lucysyt** [comment]
this will be has a error ,you can set "lang=less" or "lang=sass" in "<style lang='css'></style>",try it;




------------------ 原始邮件 ------------------
发件人: "Surmon";<notifications@github.com>;
发送时间: 2017年8月18日(星期五) 下午2:46
收件人: "surmon-china/vue-awesome-swiper"<vue-awesome-swiper@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [surmon-china/vue-awesome-swiper] slider not working properlywhen direction set to vertical (#119)

**Comment by surmon-china** [comment]
@lucysyt You are right, it's `sass`.

**Comment by jhasuev** [comment]
I have the same problem. 
I set a height to container + set height to items with option "height". Also I set "slidesPerView" to 4, but it shows all slides in the container adapting the slides height.


![image](https://user-images.githubusercontent.com/26802815/77906715-15d00480-7291-11ea-9f76-a9573e9bd66b.png)

**Comment by jhasuev** [comment]
![image](https://user-images.githubusercontent.com/26802815/77907126-c63e0880-7291-11ea-8bbd-c2a591e96663.png)
here are the options...
What should I do?  I need 4 slides with 150px of height on the container .
Thanks.

**Comment by AmberKe** [comment]
版本：swiper 6.0.4，vue-awesome-swiper 4.1.1
![image](https://user-images.githubusercontent.com/44604311/87659890-c99dc700-c790-11ea-9573-41452da85d9a.png)
main.js
![image](https://user-images.githubusercontent.com/44604311/87660215-4a5cc300-c791-11ea-99b7-acb0c1a56011.png)
页面
![image](https://user-images.githubusercontent.com/44604311/87660395-8f80f500-c791-11ea-9aa0-792709fbbac3.png)
![image](https://user-images.githubusercontent.com/44604311/87660403-93ad1280-c791-11ea-9f5a-888bf8856359.png)
html中图片和左右箭头能渲染出来，图片也能手动拖动，但箭头无效，分页器不显示，找不到原因在哪？还请指点一下！！

**Comment by kantbtrue** [comment]
`height: 100vh` declaration to swiper container, solved my issue.
**Finding**
- `height` property is must

**NOTE:** `%` do not work

**Comment by ChloeQQQ** [comment]
thanks guys !! i had solved my problems

**Comment by azabroflovski** [comment]
> I have similar problem with the height when i use `direction: 'vertical'` and I fix it adding this option `height : window.innerHeight`

OH THANK YOU

**Comment by hafizjavaid** [comment]
> `height: 100vh` declaration to swiper container, solved my issue. **Finding**
> 
> * `height` property is must
> 
> **NOTE:** `%` does not work

Thank you so much for the solution
