### ISSUE TITLE
optional css file

### ISSUE THREAD

**Issue by salihsagdilek** [surmon-china/vue-awesome-swiper#123]
i think css file should be optional

https://github.com/surmon-china/vue-awesome-swiper/blob/master/swiper.vue#L18

because i have custom css in my template files and this is sick problem.

i think this line should be deleted and optional 

# Use Setup

### Install vue-awesome-swiper

``` bash
npm install vue-awesome-swiper --save
```

### Vue mount

``` javascript
// import
import Vue from 'vue'
import VueAwesomeSwiper from 'vue-awesome-swiper'


// or require
var Vue = require('vue')
var VueAwesomeSwiper = require('vue-awesome-swiper')

//add global swiper css file if you need
require('swiper/dist/css/swiper.css')

// mount with global
Vue.use(VueAwesomeSwiper)


```

I can make a pull request if you think my approach is fine for you.

**Comment by surmon-china** [comment]
This is a good suggestion, but I suggest that style loading can be controlled by a field like `loadtheme`, rather than manually, but also in the readme document update. If you can do it, you are welcome to submit pr.

**Comment by metekabak** [comment]
@surmon-china How do you prefer managing theme? I do not quite understand the method to implementing this issue.

**Comment by surmon-china** [comment]
load dedafult theme:

```html
<swiper :loadtheme="true" ...></swiper>

<!-- or -->
<swiper ...></swiper>
```

don't load default theme(and load custom theme):

```html
<swiper :loadtheme="false" ...></swiper>

<!-- and -->
require('your-custom-swiper-style.css')
```

**Comment by metekabak** [comment]
I think this is not "the right way", If any swiper component setted true will override the css entirely.
We should handle this at the beginning while importing the package.

**Comment by surmon-china** [comment]
v2.6.0 done.

https://github.com/surmon-china/vue-awesome-swiper#vue-mount
