### ISSUE TITLE
Expected":" in IE 11 with webpack

### ISSUE THREAD

**Issue by jacty** [surmon-china/vue-awesome-swiper#125]
I have met this issue when I import 'vue-awesome-swiper'. And got to know that functions like data(), failed to transform to 'data:function()' by babel. I added 'transform-runtime' to my webpack.config.js, but with 'exclude:/(node_modules)/', the data() functions cannot transform either, because they are in node_modules. What if I remove 'exclude:/(node_modules)', get an error that '$.export is not a function'. So I am thinking if I configed something wrong?
This is my webpack.config.js below.
Thanks for help.

`        module:{
            rules:[
            {
                test:/\.vue$/,
                use:{
                    loader:'vue-loader',
                }
            },
            {
                test:/\.js$/,
                exclude:/(node_modules)/,
                use:{
                    loader:'babel-loader',
                    options:{
                        presets:['env'],
                        plugins:['transform-runtime','transform-vue-jsx'],
                        cacheDirectory:true
                    }
                }
            },{
                test:/\.css$/,
                use:{
                    loader:'css-loader'
                }
            }
            ]
        },`

**Comment by surmon-china** [comment]
Why not use vue-cli to initialize the webpack configuration?

**Comment by jacty** [comment]
sorry, because of some legacy issues. I cannot just use the webpack configuration initialized by vue-cli. And I rewrite parts of the configs. I have no idea if there are something wrong even if I recovered the babel config in webpack config file, it didn't work.

**Comment by surmon-china** [comment]
You can try to replace the function `() {}` in the `. vue` file with `function () {}` and then restart the application. If this works, you can modify it after submitting a PR!

**Comment by jacty** [comment]
I have found out what the bug is. I think it is because of webpack. I move the config of babel to babelrc from webpack.config.js. Everything goes well...so ..
Anyway, thank you all the same.

**Comment by surmon-china** [comment]
v2.5.5 will fix it.
