### ISSUE TITLE
how to work both with nuxt/ssr & nuxt generate?

### ISSUE THREAD

**Issue by HADB** [surmon-china/vue-awesome-swiper#126]
I'm using nuxt.js.

It works fine with `npm run dev` but it doesn't work with `npm run generate` .

我在nuxt.js下，开发的时候使用的是ssr的引入方式，但是在生成静态页面的时候，就不work了，但是如果通过spa的方式引入，我在开发的时候又有问题了，怎样同时满足这两种使用方式呢？

**Comment by surmon-china** [comment]
`generate`下还没做过测试，要不你分别尝试下， 如果探索到可能方案，可以提交PR，很欢迎。

**Comment by HADB** [comment]
我的锅，用next/ssr的方式，generate是没有问题的。之前有问题是因为generate生成出来的文件部署到cdn的时候，通过http://xxx.com/index.html 的方式访问的，所以有点问题。将index.html设为CDN默认首页，直接通过http://xxx.com 去访问就没问题了。

**Comment by surmon-china** [comment]
明白，祝顺利。

**Comment by ermilov** [comment]
`npm run dev` works fine, but `npm run generate` have this error:

`ERROR in common.ae257c186b7c73ab5dd2.js from UglifyJs
Unexpected token: name (w) [./node_modules/swiper/dist/js/swiper.esm.bundle.js:15,0][common.ae257c186b7c73ab5dd2.js:11253,4]`

dependencies
```
"nuxt": "^1.0.0-rc11",
"vue-awesome-swiper": "^2.6.7"
```

nuxt.config.js
```
plugins: [
  { src: '~/plugins/swiper.js', ssr: false }
]
```

swiper.js
```
import Vue from 'vue'
import VueAwesomeSwiper from 'vue-awesome-swiper/ssr'

Vue.use(VueAwesomeSwiper)
```

and vue file
```
<div v-swiper:mySwiper="swiperOption">
  <div class="swiper-wrapper">
    <div class="swiper-slide" v-for="(pack, index) in packs" :key="pack.id">
      <div>{{ pack }}</div>
    </div>
  </div>
</div>
```
