### ISSUE TITLE
use vue-awesome-swiper.js  not found component swiper

### ISSUE THREAD

**Issue by zhuqinqin** [surmon-china/vue-awesome-swiper#127]
项目是直接引用vue.js,和 vue-awesome-swiper.js开发，然后是在实例中按照demo的写法来用的，结果都是报错，如果可以能给一个引用vue-awesome-swiper.js然后正确调用的写法参考吗，谢谢。
vue.js:440 [Vue warn]: Unknown custom element: <swiper> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

vue.js:440 [Vue warn]: Unknown custom element: <swiper-slide> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

**Comment by surmon-china** [comment]
抱歉，打包后的代码可能是异常的，这方面我没有做过测试

**Comment by surmon-china** [comment]
你可以暂时自己把`.vue`以js template的形式在客户端使用

**Comment by zhuqinqin** [comment]
哦，谢谢你的快速回复，期待以后有好的解决方法

**Comment by surmon-china** [comment]
@zhuqinqin 升级到最新版，按照这样使用：

https://github.com/surmon-china/vue-awesome-swiper#use-setup-for-browser
