### ISSUE TITLE
Bindings inside custom pagination

### ISSUE THREAD

**Issue by Landen13** [surmon-china/vue-awesome-swiper#128]
Hello! Is there possibility to bind some data into custom pagination, made via paginationBulletRender?

Upd: Just found an answer - as simple as possible)

**Comment by Landen13** [comment]
@surmon-china why is this opened again?

**Comment by surmon-china** [comment]
@Landen13 Because I think the data bound to `pagination `, seems to be an interesting question.

**Comment by surmon-china** [comment]
```html
<div class="swiper-pagination" slot="pagination" ref="pagination"></div>
```

```javascript
this.$refs.pagination...
```

You can use the `refs` to `swiper-pagination` internal sub-elements to operate when the data changes, but the sub-element binding events can not be changed, and can not broadcast events, it seems no better way.
