### ISSUE TITLE
In the effect-coverflow mode with loop, async data will  cause swiper broken

### ISSUE THREAD

**Issue by Hedgehogking** [surmon-china/vue-awesome-swiper#129]
In the **effect-coverflow** mode with **loop**, **async data** will  cause the slides layout disorder
, due to the implementation of destroyLoop() and createLoop() in reLoop() when update() in slide.vue.
This is my option:
<pre>
	swiperOption: {
		effect: 'coverflow',
		grabCursor: true,
		centeredSlides: true,
		slidesPerView: 'auto',
		autoplay: 3000,
		loop: true,
		coverflow: {
			rotate: 0,
			stretch: -290,
			depth: 2500,
			modifier: 1,
			slideShadows : false,
		},
	},
</pre>

Execute reLoop() by hand will reproduce the problem.

**Comment by surmon-china** [comment]
Sorry, there is no solution to this problem, there are many problems caused by the `loop` attribute, can not be solved, it comes from` swiper` itself.
