### ISSUE TITLE
Uncaught TypeError: Cannot read property 'params' of null     at Swiper.s.slideTo

### ISSUE THREAD

**Issue by moxiaobei2** [surmon-china/vue-awesome-swiper#130]
###I use this components to do a test question:like swiper to next test
     ###   swiperOption: {
                                        setWrapperSize: true,
                                        preventClicks: false,
                                        allowSwipeToNext: true, //禁止下一个滚动
                                        debugger: true,
                                        loop: true,
                                },
    ###when I go to one page,I want to go to the firstPage,to test again ,this step have no problem,but 
      go next  step ,the issues is happen,just like Uncaught TypeError: Cannot read property 'params' 
      of null     at Swiper.s.slideTo ...How can I do?

**Comment by surmon-china** [comment]
code?

**Comment by xwLyc** [comment]
我也出现这个问题了。
比如我写了三个组件 home, nav, slider，我实现 的功能是，home里 可以通 nav选项卡 切换，然后更新对应的 slider组件，第一次进入home里是没有问题的，但是，我从 home 路由 进入 其它的 路由，然后再返回 home页面时，这时候，再点击nav切换 slider组件，就会提示这个错误。

### [Vue warn]: Error in event handler for "swiperIndex": "TypeError: Cannot read property 'params' of null"(found in <Root>);


       **slider组件：**
        mounted() {
            this.swiper(this.curIndex,0,false); 
            this.$root.$on('swiperIndex',()=>{  //切换 nav 时更新 当前swiper index
                this.$store.commit('curIndex',0);
                this.swiper(this.curIndex,0,false);

            })
        },

      **nav组件：触发事件**
      this.$root.$emit('swiperIndex');

**Comment by surmon-china** [comment]
检查一下箭头函数中的`this`上下文是否是预期，多几个节点打印日志

**Comment by surmon-china** [comment]
用 $nextTick

**Comment by xwLyc** [comment]
用过了，还是一样的结果....

**Comment by surmon-china** [comment]
完整的代码贴出来

**Comment by xwLyc** [comment]
代码写的有点乱，刚刚传到github上了   https://github.com/xwLyc/library，npm install 后，然后运行地址 http://localhost:2222/?category_id=5962e63f2bc3b82e178a3878
就是初次进入home时，切换选项卡，正常。然后点击 swiper进入下一个路由，再点击返回，这时候，再切换选项卡，控制台就报错了~ 

谢谢，辛苦啦~~~

**Comment by surmon-china** [comment]
先试一下`<swiper :options="swiperOption" :not-next-tick="true" ref="mySwiper">`

**Comment by xwLyc** [comment]
还是不行 。。。

**Comment by xwLyc** [comment]
已解决，谢谢~~~

我是把，
       this.$root.$on('swiperIndex',()=>{  //切换 nav 时更新 当前swiper index
            this.$store.commit('curIndex',0);
            this.swiper.slideTo(this.curIndex,0,false);

        })
这一段的注册事件，写在了watch函数里，监听 this.$href.mySwiper, 变化也就是有值的时候，在注册 $on事件，然后就能找到swiper的属性了。

**Comment by surmon-china** [comment]
很奇怪，很奇怪

**Comment by surmon-china** [comment]
刚看了下之前你的有问题的代码，有可能是因为组件内`this.curIndex`数据本身是`undefined`，或 [ 一系列切换后 ] 再被激活 [ 立即要去执行`slideTo` ] 的时候是`undefined`，所以`this.swiper.slideTo(undefined, 0, false);`这样的语句会报错

**Comment by SiddiquiImran** [comment]
Hi @surmon-china ,
Facing same issue:
HTML Code:
`    <div class="white-box analytics-section">
      <el-row>
        <el-col :span="12">
          <h2 class="analytics-title">{{resource.appDownloads}}</h2>
          <p class="grey-color">{{resource.analyticsOverviewSubHeading}}</p>
        </el-col>
        <el-col :span="12" v-if="appDownloadsActiveName === 'First'">
          <el-row class="month-carousel">
            <swiper :options="monthSwiperOption" :not-next-tick="notNextTick" ref="monthSwiper">
              <swiper-slide v-for="(month, index) in MonthArray" :key="index">{{ month }}</swiper-slide>
              <div class="swiper-button-prev" slot="button-prev"></div>
              <div class="swiper-button-next" slot="button-next"></div>
            </swiper>
          </el-row>
        </el-col>
      </el-row>
      <el-row>
        <el-tabs class="customtabs analytics-tabs" v-model="appDownloadsActiveName" @tab-click="downloadTabClick">
          <el-tab-pane :label="resource.analyticsDayWise" name="First">
            <vue-chartist :data="appDownloadsForMonth" :options="verticalChartOptions" type="Bar"></vue-chartist>
          </el-tab-pane>
          <el-tab-pane :label="resource.analyticsWeekWise" name="second">
            <vue-chartist :data="appDownloadsForLast26Weeks" :options="weeklyVerticalChartOptions" type="Bar"></vue-chartist>
          </el-tab-pane>
          <el-tab-pane :label="resource.analyticsMonthWise" name="three">
            <vue-chartist :data="appDownloadsForLast12Month" :options="verticalChartOptions" type="Bar"></vue-chartist>
          </el-tab-pane>
        </el-tabs>
      </el-row>
    </div>`

JS code:
`monthSwiperOption: {
        paginationClickable: false,
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        initialSlide: 1,
        onSlideChangeEnd: swiper => {
          this.changeCurrentMonth(swiper.realIndex)
          console.log('onSlideChangeEnd month', swiper.realIndex)
        }
      },
      dateSwiperOption: {
        paginationClickable: false,
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        initialSlide: 1,
        onSlideChangeEnd: swiper => {
          this.changeCurrentDay(swiper.realIndex)
          console.log('onSlideChangeEnd date', swiper.realIndex)
        }
      }`

JS functions on click:
`downloadTabClick (tab, event) {
      try {
        // this.dateIntialSlide = this.DateArray.length - 1
        console.log(this.dateSwiper)
        this.monthSwiper.slideTo(1)
      } catch (e) {
        console.log('downloadTabClick', e)
      }
    },
    pageViewsTabClick (tab, event) {
      try {
        // this.dateIntialSlide = this.DateArray.length - 1
        console.log(this.dateSwiper)
        this.dateSwiper.slideTo(1)
      } catch (e) {
        console.log('pageViewsTabClick', e)
      }
    }`

console logs:
![image](https://user-images.githubusercontent.com/20870175/30855017-0eec7e9c-a2d1-11e7-8b23-5f658d3ee0cc.png)

**Comment by surmon-china** [comment]
@SiddiquiImran format your code.

**Comment by SiddiquiImran** [comment]
Hi @surmon-china ,
Have formatted it.

**Comment by PrashantKumar-Monotype** [comment]
hi @surmon-china  I am facing a similar issue in the version 2.6.7 . It says 's is null' hence the above error -params of null .
Steps:
1)Open the  screen containing swiper.
2)reroute to the same screen by using router.push with Date.now() as a parameter in the route so that it updates the screen.
The following error message occurs.
<img width="387" alt="error 2" src="https://user-images.githubusercontent.com/29861096/33647186-abdc482e-da79-11e7-86e9-60cfeffa0e6f.png">
<img width="676" alt="error" src="https://user-images.githubusercontent.com/29861096/33647187-ac2157d4-da79-11e7-8c2a-e291cbbe41b2.png">
