### ISSUE TITLE
Broken "loop" option on Slides-Per-Column layout

### ISSUE THREAD

**Issue by mikeevstropov** [surmon-china/vue-awesome-swiper#133]
#### Vue.js version and component version
"vue": "^2.4.1",
"vue-awesome-swiper": "^2.5.4",

#### Options
loop: true,
slidesPerView: 6,
slidesPerColumn: 2,

#### What is Expected?		
Looping

#### What is actually happening?
Loop is not working. If we have 12 items per view (6 * 2) so on the end swiper will add only 6 items but not 12 as expected. Try it out!

Thank you

**Comment by surmon-china** [comment]
I'm sorry. that all problems with the `loop` attribute are known issues that come from` swiper` itself, as a component, no solution, thank you for your feedback!
