### ISSUE TITLE
Getting errors when using webpack --watch

### ISSUE THREAD

**Issue by eybarta** [surmon-china/vue-awesome-swiper#134]
Hi, thanks for all your work and great plugin.

I'm building with webpack 3.4.1, and getting an error after I make a change
(first load is good, second I get the error after HMR):
![image](https://user-images.githubusercontent.com/12781988/29003709-245c0dfe-7ac4-11e7-9c95-ece4ebab63c3.png)

I noticed inside 'swiper.vue' file, if I remove this line:
`require('swiper/dist/css/swiper.css')` (line 18)

I no longer get the error, but my sliders are messed up..

Appreciate any help

thx

**Comment by surmon-china** [comment]
Update to v2.6.0 please, starting with version 2.6.0, you need to manually introduce swiper's css.

**Comment by surmon-china** [comment]
#123 
#41

**Comment by eybarta** [comment]
sweet thx, that's what I did, copied the minified css from swiper module.
