### ISSUE TITLE
关于css依赖的一个问题

### ISSUE THREAD

**Issue by fyddaben** [surmon-china/vue-awesome-swiper#136]
# 我的发布过程是这样子
- 在云主机的A目录，进行npm i 安装依赖，进行webpack 编译，得到所有的压缩后文件
- 把A目录中编译好的js文件搬到B目录，服务器的根目录。node_modules我认为是用于编译过程的文件，服务器根目录中不需要这些依赖文件

## 发现的问题
vue-swiper组件依赖，node_module中的swiper组件中的css，由于，我并没有把node_module中的文件搬运到服务器目录，造成样式错乱。

建议，在vue-swiper中把css文件编译到js中

**Comment by surmon-china** [comment]
建议无效，而且你的理解有错误，你在第一步进行`webpack`编译的时候就已经编译产出了 css 文件了，一定是其他原因导致的你的样式错乱。

#123
