### ISSUE TITLE
导航切换的路由使用keep-alive,页面切换回来，轮播图自动播放会失效

### ISSUE THREAD

**Issue by jermyLin** [surmon-china/vue-awesome-swiper#137]
`首页用swiper做了个轮播图，可自动播放，当页面切走再切回来，轮播图自动播放就失效了，是什么原因？
配置参数如下：
> `swiperOption: {
          initialSlide: 1,
          autoplay: 2000,
          autoplayDisableOnInteraction: false,
          direction: 'horizontal',
          speed: 1000,
          loop: true,
          pagination: '.swiper-pagination',
          paginationClickable: true,
          mousewheelControl: true,
          observer: true,
          observeParents: true,
        }`

**Comment by surmon-china** [comment]
在提问前能不能搜索一下，能不能！能不能！能不能！

#24
