### ISSUE TITLE
Cannot read property 'swiper' of undefined" when 'not-next-tick:true' in mounted

### ISSUE THREAD

**Issue by LJade** [surmon-china/vue-awesome-swiper#139]
template:
```
<swiper :options="swiperOption" :not-next-tick="notNextTick" ref="mySwiper">
  <slide v-for="item in XXX">
</swiper
```

script:
```
data:{
       notNextTick: true,
        swiperOption: {
          initialSlide: 0,
          onlyExternal: true,
          onInit: (swiper) => {
            console.log(swiper)
          },
          onReachEnd: (swiper) => {
            console.log('last slide')
          }
        }
},
computed: {
      swiper () {
        return this.$refs.mySwiper.swiper
      }},
mounted () {
     console.log(this)
     console.log(this.swiper)
}

```

 all above is my real code refered to README/#Use in SPA

 error in broswer and never console
![image](https://user-images.githubusercontent.com/17740329/29161160-bbff00f0-7de7-11e7-89bd-b76a6108690b.png)
![image](https://user-images.githubusercontent.com/17740329/29161185-d5b23d1e-7de7-11e7-9b16-26f1a31b7721.png)

 I need  swiper instance first time,but I can't get it
Someone else know why and how?

**Comment by surmon-china** [comment]
Format and refine your code.

**Comment by surmon-china** [comment]
I'm sorry, I did not get this error here, is it caused by other code?

**Comment by LJade** [comment]
@surmon-china Thank you,I also dont't know why it is. I can console the 'this' and find the swiper in 'this'. The close next console can't log the swiper. Key code as above. I am not sure the error caused by other.I will check my code more carefully to find the original error

**Comment by surmon-china** [comment]
The reason for the real mistake is that this context is incorrect, this is undefined, so no swiper object.

**Comment by mangoqili** [comment]
The reason for the real mistake is that this swiper's parent has v-if, change v-if to v-show

**Comment by honey93** [comment]
I am also facing the same issue, on initial load it is showing the swiperobject but once I route and come back to that same page, I do face that issue.
