### ISSUE TITLE
很正常的使用方式，但是在微信打开就出现，或无法加载，或加载的不是水平方向，而是垂直方向的情况，在chrome手机版跟安卓原生浏览器正常

### ISSUE THREAD

**Issue by qq781548819** [surmon-china/vue-awesome-swiper#141]
<swiper class="good-item" :options="imgSwiperOption">
                            <swiper-slide class="swiper-item" v-for="(goodItem,idx) in item.goods_info" :key="idx">
                                <img class="img" :src="goodItem.one_logo" />
                            </swiper-slide>
</swiper>

 imgSwiperOption: {
                scrollbar: '.swiper-scrollbar',
                scrollbarHide: true,
                slidesPerView: 'auto',
                centeredSlides: true,
                spaceBetween: 30,
                grabCursor: true
 },

 .good-item {
            padding-left: .3rem;
            padding-right: .3rem;
            width: 100%; // padding-left: .5rem;
            // height: 2.7rem;
            // padding-right: .5rem;
            margin-top: .3rem;
            margin-bottom: .1rem;
            border-bottom: 1px #ddd solid;
            .img {
                border: 1px #ddd solid;
                border-radius: 4px;
                width: 2.7rem;
                height: 2.7rem;
                object-fit: cover;
            }
        }
怒了，tm的微信，怎么那么奇葩，求作者帮忙

**Comment by surmon-china** [comment]
贴出详细代码（包括完整的组件和脚本），并格式化，对问题进行规范化的补充，然后问题再重新打开
