### ISSUE TITLE
用vue-awesome-swiper这个组件写的轮播图的每一个分页总是排成一列，而不是并排显示，原来写好的项目也变成这样了

### ISSUE THREAD

**Issue by YJZ-S** [surmon-china/vue-awesome-swiper#142]
<img width="819" alt="default" src="https://user-images.githubusercontent.com/26481272/29393417-2099acc4-8336-11e7-8bfa-5d3024c8f083.png">

**Comment by surmon-china** [comment]
阅读 README.md，手动引入css

**Comment by YJZ-S** [comment]
谢谢谢谢谢谢，终于解决了，非常感谢！

**Comment by Qdoku** [comment]
怎样手动引入？

**Comment by Qdoku** [comment]
手动引入的时候还需要install什么东西吗
