### ISSUE TITLE
Last slide autoheight like fullpage.js

### ISSUE THREAD

**Issue by mitkovalkov** [surmon-china/vue-awesome-swiper#147]
I use the swipper to make full height (100vh) onepage website. Can I use option like this one like fullpage.js https://alvarotrigo.com/fullPage/examples/autoHeight.html. I want my footer to stay in the viewport.

`swiperOption: {
  	pagination: '.swiper-pagination',
  	direction: 'vertical',
  	slidesPerView: 1,  
  	spaceBetween: 0,
  	mousewheelControl: true, 
  	keyboardControl: true, 
  	speed: 800,  
  	autoHeight: true, 
},`

**Comment by surmon-china** [comment]
Sorry, after my test, swiper should not support it.

**Comment by mitkovalkov** [comment]
Ok. Thanks a lot. I use this options to make something like this.
`onSlidePrevStart: function(swiper){  
  if (swiper.activeIndex + 1 == swiper.slides.length - 1) {
    document.body.scrollTop = document.documentElement.scrollTop = 0;
  }
},`

**Comment by surmon-china** [comment]
Nice!
