### ISSUE TITLE
32-scroll-container.vue 不会出现滚动条

### ISSUE THREAD

**Issue by egsoftcn** [surmon-china/vue-awesome-swiper#15]
您这个例子右边不会出现滚动条，滚动条貌似在左下脚。

**Comment by egsoftcn** [comment]
从查看源码看跟官方例子的区别在于。您这个生成后的代码 div class="swiper-scrollbar",包含在div class=“swiper-wrapper”下面。而官方例子的代码是应该包含在它的上级div class="swiper-container"中

**Comment by surmon-china** [comment]
感谢反馈，已修复，问题在于，slot关键词使用错误：

代码中错误实例：

```html
<div class="swiper-scrollbar" solt="scrollbar"></div>
```

正确代码：
```html
<div class="swiper-scrollbar" slot="scrollbar"></div>
```
