### ISSUE TITLE
onImagesReady回调函数获取的swiper的height属性0，但是打印对象里的height确实161

### ISSUE THREAD

**Issue by xiaodongning** [surmon-china/vue-awesome-swiper#152]
![image](https://user-images.githubusercontent.com/11451347/29806625-f44cd042-8cc2-11e7-9e33-775d7e813453.png)
![image](https://user-images.githubusercontent.com/11451347/29806649-0c49022e-8cc3-11e7-97a1-3d27477e12d1.png)
截图中红色框框里打印的 swiper对象里的height属性是161，但获取的时候却是0；在onImagesReady回调函数执行的

**Comment by surmon-china** [comment]
1. 控制台异步
2. 想办法异步
