### ISSUE TITLE
The use of animation in the nuxt(ssr)

### ISSUE THREAD

**Issue by bearRoe** [surmon-china/vue-awesome-swiper#154]
Support the animation in the nuxt(ssr)? If you can, please comment, thank you

**Comment by surmon-china** [comment]
Describe in detail please.

**Comment by bearRoe** [comment]
<p class="ani" swiper-animate-effect="fadeInUp" swiper-animate-duration="0.5s" swiper-animate-delay="0.3s">内容</p>
这些swiper-animate-*无效，要这些动画起效，需要在nuxt中如何配置

**Comment by surmon-china** [comment]
问题合并 #203
