### ISSUE TITLE
autoplay is not working

### ISSUE THREAD

**Issue by antonioreyna** [surmon-china/vue-awesome-swiper#155]
hello i updated this library and now my autoplay is not working

**Comment by surmon-china** [comment]
detail? code?

**Comment by iysf** [comment]
![image](https://user-images.githubusercontent.com/30407398/30265251-329a46c2-970e-11e7-8bf0-f5c95ac74656.png)

**Comment by terrytangabc** [comment]
seems to be an issue with swiper v4.0.0 beta3，autoplay works well after downgrading swiper to version 3.4.2

**Comment by victory-v** [comment]
The same problem, Swiper 3.4.2

**Comment by surmon-china** [comment]
v3.0.0 usr Swiper 4.0.0 +.

https://github.com/surmon-china/vue-awesome-swiper/blob/master/CHANGELOG.md#v300

**Comment by surmon-china** [comment]
Swiper4

```javascript
this.$refs.swiper.swiper.slideTo(2);
this.$refs.swiper.swiper.autoplay.stop();
this.$refs.swiper.swiper.autoplay.start();
```

**Comment by Bobur-kobilov** [comment]
Worked perfectly! thanks

**Comment by pellucidme** [comment]
> v3.0.0 usr Swiper 4.0.0 +.
> 
> https://github.com/surmon-china/vue-awesome-swiper/blob/master/CHANGELOG.md#v300

hi, i have problem with autoplay in vue-awesome-swiper (custom build)
