### ISSUE TITLE
一行多列,slidesPerView: 6,每行中显示6个。为何点击任意一个，activeIndex返回的都是0呢？

### ISSUE THREAD

**Issue by tankxxl** [surmon-china/vue-awesome-swiper#16]
![image](https://cloud.githubusercontent.com/assets/1826540/20871235/67d2133c-bace-11e6-9198-ec50f1dd095c.png)

**Comment by surmon-china** [comment]
上代码

**Comment by tankxxl** [comment]
SwiperOption: {
    name: 'moduleSwiper',
    direction : 'horizontal',
    grabCursor : true,
    setWrapperSize :true,
    // autoHeight: true,
    spaceBetween: 30,
    slidesPerView: 6,
    mousewheelControl : true,
    observeParents:true,
    // swiper callbacks
    onClick: (swiper, event) => {
      console.log('Swiper-onClick...activeIndex:' + swiper.activeIndex)
      this.moduleIndex = swiper.activeIndex
    }
}
我把swiper控件当成一个列表控件来用。

**Comment by surmon-china** [comment]
不知你上下文所述“列表控件”是什么东西，
建议你给更详细的代码，或者用Gist

**Comment by surmon-china** [comment]
是否开启了Loop

**Comment by tankxxl** [comment]
![image](https://cloud.githubusercontent.com/assets/1826540/20872157/579456f2-bad7-11e6-9b95-3dca301c650f.png)
这个swiper不用autoplay，不用显示pagination等信息，就当一个九宫格来用，点击里面的item时，activeIndex一直是0。

**Comment by tankxxl** [comment]
gist奉上：https://gist.github.com/tankxxl/ac5727ca79b3a64b524d046111340a69.js

**Comment by surmon-china** [comment]
gist当然应该是片段的形式...这js文件哪有可识别性可言...

**Comment by tankxxl** [comment]
https://gist.github.com/tankxxl/ac5727ca79b3a64b524d046111340a69

**Comment by surmon-china** [comment]
你的问题在于：onClick回调函数回调数据中的swiper.activeIndex是以swiper的轮播范围为单位的，所以你一直在第一页点击，如论点击任何一个元素，自然得到第一页的下标0。
所以你可以取swiper.clickedIndex这个数据，这个是当前范围内所点击的子元素的下标。

下次这样的问题，先打印对象出来，得到充足的扩展信息，会帮助你节省很多时间。

**Comment by surmon-china** [comment]
``` javascript
export default {
    data() {
      return {
        swiperOption: {
          pagination: '.swiper-pagination',
          slidesPerView: 3,
          slidesPerColumn: 2,
          paginationClickable: true,
          spaceBetween: 30,
          onClick(swiper, event) {
            console.log('Swiper-onClick.activePageIndex:', swiper.activeIndex)
            console.log('Swiper-onClick.current Page activeItemIndex:', swiper.clickedIndex)
          }
        }
      }
    }
  }
```
