### ISSUE TITLE
'activeIndex' doesn't find 

### ISSUE THREAD

**Issue by LJade** [surmon-china/vue-awesome-swiper#165]
Hi ,I can find this.swiper,but I can't find 'this.swiper.activeIndex' not only consoleLog but also vueDevtool.
Most important,It appear sometime,not all time.
Code run smoothly in monring,but stop in afternoon.My page depend on activeIndex much more.so Can you resolve the issue can explain why.I promise do nothing during.

**Comment by surmon-china** [comment]
Sorry, I can't get the error. you can show the code.
