### ISSUE TITLE
更改页面数据会 slide 组件会触发 updated 事件

### ISSUE THREAD

**Issue by canhongpoxiao** [surmon-china/vue-awesome-swiper#166]
更改页面数据会 slide 组件会触发 updated 事件

**Comment by canhongpoxiao** [comment]
使浏览器多次渲染

**Comment by canhongpoxiao** [comment]
不知道可否去掉 updated 事件，因为 slide 组件不会有数据更新

**Comment by surmon-china** [comment]
`update`是动态数据得以实现的核心，鉴于工作机制，无法去除。

**Comment by canhongpoxiao** [comment]
@surmon-china 您还，不太清楚为什么更新和 slide 组件无关的数据，也会导致 slide 组件触发 updated 事件，swiper 也有相同的行为，可以说明一下吗？谢谢。

**Comment by cailiuyang** [comment]
我初始化swiper后，下拉刷新数据，然后我要怎么操作，才会让slider到第一张图片，pagination也到第一个对应

**Comment by surmon-china** [comment]
@cailiuyang 业务问题自行解决。

**Comment by surmon-china** [comment]
@canhongpoxiao 因为事实上组件没有办法知道你更新的是 [ 谁 ]，是不是 [ 和 slide 相关的数据 ]，组件仅使用`updated` api，内部逻辑由 `vue`完成。
