### ISSUE TITLE
<no-ssr> feature support

### ISSUE THREAD

**Issue by mrserzhan** [surmon-china/vue-awesome-swiper#167]
Nuxt.js has new feature - tag [https://github.com/nuxt/nuxt.js/tree/dev/examples/no-ssr](no-ssr) that not compile component on server side for SSR applications. Your library throw exception on importing, cause using "window" on prototype. I think properties of prototype must be changed to methods.

**Comment by surmon-china** [comment]
Show me your code.

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-awesome-swiper/blob/master/nuxt-ssr-example/nuxt.config.js#L4

`{  ssr: false }`

https://github.com/surmon-china/vue-awesome-swiper/blob/master/nuxt-ssr-example/nuxt-swiper-plugin.js#L3

`vue-awesome-swiper/ssr`
