### ISSUE TITLE
用了新的安装vue init webpack 再安装sweper出现了css引入报错

### ISSUE THREAD

**Issue by PolanZ** [surmon-china/vue-awesome-swiper#17]
错误信息如下：
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0
!./~/vue-awesome-swiper/swiper.vue
Module not found: Error: Cannot resolve module 'style-loader' in D:\wamp\www\svn
\bigdata\homepages\node_modules\vue-awesome-swiper
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/v
ue-awesome-swiper/swiper.vue 11:2-39

怎么去配置style-loader呢，因为新的webpack config应该把CSS单独打包的，所以用ExtractTextPlugin.extract

exports.cssLoaders = function (options) {
  options = options || {}
  // generate loader string to be used with extract text plugin
  function generateLoaders (loaders) {
    var sourceLoader = loaders.map(function (loader) {
      var extraParamChar
      if (/\?/.test(loader)) {
        loader = loader.replace(/\?/, '-loader?')
        extraParamChar = '&'
      } else {
        loader = loader + '-loader'
        extraParamChar = '?'
      }
      return loader + (options.sourceMap ? extraParamChar + 'sourceMap' : '')
    }).join('!')

    // Extract CSS when that option is specified
    // (which is the case during production build)
    if (options.extract) {
      return ExtractTextPlugin.extract('vue-style-loader', sourceLoader)
    } else {
      return ['vue-style-loader', sourceLoader].join('!')
    }
  }

  // http://vuejs.github.io/vue-loader/en/configurations/extract-css.html
  return {
    css: generateLoaders(['css']),
    postcss: generateLoaders(['css']),
    less: generateLoaders(['css', 'less']),
    sass: generateLoaders(['css', 'sass?indentedSyntax']),
    scss: generateLoaders(['css', 'sass']),
    stylus: generateLoaders(['css', 'stylus']),
    styl: generateLoaders(['css', 'stylus'])
  }
}

// Generate loaders for standalone style files (outside of .vue)
exports.styleLoaders = function (options) {
  var output = []
  var loaders = exports.cssLoaders(options)
  for (var extension in loaders) {
    var loader = loaders[extension]
    output.push({
      test: new RegExp('\\.' + extension + '$'),
      loader: loader
    })
  }
  return output
}

**Comment by surmon-china** [comment]
cnpm install style-loader

**Comment by surmon-china** [comment]
将Vue-cli、Webpack均升级到最新版，重新初始化项目
