### ISSUE TITLE
多行多列的swiper手动点击next按钮无法从末尾切换到开头

### ISSUE THREAD

**Issue by myesis** [surmon-china/vue-awesome-swiper#170]
这是我的swiper配置，如果是autoplay模式可以自动从最后一页切换到第一页，但是如果打开loop：true选项，手动操作会出错误，分页器的点点会多出一倍，而实际上并没有那么多元素，并且多出的点点并不可以点击，这个问题貌似和我的2行4列有关系，不知道这样子是不是其他参数需要设置，求解。
    
swiperOptionIn: {
          slidesPerView: 4,
          slidesPerColumn: 2,
          slidesPerGroup:4,
          prevButton:'.swiper-button-prev',
          nextButton:'.swiper-button-next',
          pagination: '.swiper-pagination',
          paginationClickable: true,
          autoplayDisableOnInteraction : false,
          grabCursor : true,
          // autoplay: 5000,
          spaceBetween: 30,
          // loop: true,
        }

**Comment by surmon-china** [comment]
无法解决，一切 loop 引起的问题都是 swiper 本身的问题。
