### ISSUE TITLE
error with Use Setup for Browser(UMD)

### ISSUE THREAD

**Issue by Huanqiang** [surmon-china/vue-awesome-swiper#189]
I can't use this component with "Use Setup for Browser(UMD)", It's my code. 

![6027a578-8265-4b5e-aa85-56ee81ec8661](https://user-images.githubusercontent.com/7790051/32472392-75afe53c-c39d-11e7-8980-3d7611055830.png)

![8c77d2c9-ef77-4ef8-be62-110e5ff79d1e](https://user-images.githubusercontent.com/7790051/32472354-425e1708-c39d-11e7-8ebd-49f79cc22bd9.png)

And now, I have a error:

`vue.js:115 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at https://unpkg.com/vue@2.5.3/dist/vue.js:115:39
    at Object.isReservedTag (https://unpkg.com/vue@2.5.3/dist/vue.js:5101:28)
    at Function.Vue.(anonymous function) [as component] (https://unpkg.com/vue@2.5.3/dist/vue.js:4737:46)
    at Object.install (file:///Users/huangqiang/Downloads/web/js/vue-awesome-swiper.js:23:9)
    at Function.Vue.use (https://unpkg.com/vue@2.5.3/dist/vue.js:4605:22)
    at file:///Users/huangqiang/Downloads/web/js/jsunbabel/commodity-detail.js?v=4:31:5`

**Comment by surmon-china** [comment]
I will fix this problem as soon as possible.

**Comment by CooLNuanfeng** [comment]
I encountered the same problem, please solve

**Comment by one-pieces** [comment]
same problem, please solve

**Comment by one-pieces** [comment]
It seems that the JS file doesn't package the `./src/slide.vue` and `./src/swiper.vue`.

**Comment by surmon-china** [comment]
Update to v3.0.0 please.

[CDN Example](https://jsfiddle.net/kqaew65x/)
