### ISSUE TITLE
无限循环模式在动态数组中的表现问题

### ISSUE THREAD

**Issue by NadokaCiel** [surmon-china/vue-awesome-swiper#19]
当swiper-slide的数量在组件中动态改变时（使用v-for，ajax返回数组），无限循环模式会出现切换错误，反复重复最后一张，并且新数据不能正确地覆盖旧数据。
目前的解决方案是在swiper标签上加入v-if，在数组更新前后置为false/true强行重新渲染组件，不知对于这个特性有没有更好的解决方案？
期待您的回复

**Comment by surmon-china** [comment]
可以吧代码贴在dist，我测试下

**Comment by NadokaCiel** [comment]
@surmon-china 
关于这个表现的示例代码请看：[这里](https://github.com/NadokaCiel/vue-awesome-swiper-loop-issue)
在组件的data中定义了长度为3的数组，并在组件初始化5s后更改了数组
在Swiper向前翻的过程中出现了乱序。

**Comment by surmon-china** [comment]
我正在处理

**Comment by surmon-china** [comment]
已解决，升级到最新版即可解决问题
https://github.com/surmon-china/vue-awesome-swiper/tree/V2.2.6

**Comment by NadokaCiel** [comment]
谢谢您~

**Comment by xiaoxiaobaibai** [comment]
> 已解决，升级到最新版即可解决问题
> https://github.com/surmon-china/vue-awesome-swiper/tree/V2.2.6

链接打开404
