### ISSUE TITLE
autoHeight & lazyLoading 

### ISSUE THREAD

**Issue by aziz19** [surmon-china/vue-awesome-swiper#191]
hey, when using autoHeight with image lazyLoading, the slider doesn't measure the height correctly. 
does anyone has idea whats wrong with it ?? 

`swiperOption: {
        initialSlide: 0,
        pagination: '.img-pagination',
        grabCursor: true,
        setWrapperSize: true,
        spaceBetween: 10,
        autoHeight: true,
        preloadImages: false,
        // Enable lazy loading
        lazyLoading: true,
        observer: false,
        onTransitionStart (swiper) {
          console.log(swiper)
        }
      },`

**Comment by surmon-china** [comment]
This may be the problem of swiper itself, you can go to the official issue of swiper looking for a solution.
