### ISSUE TITLE
在pc端nuxt框架下，不知道是否是我配置的问题，在一个页面下同时用多个swiper，初始化的点会出问题，具体表现如下

### ISSUE THREAD

**Issue by wLove-c** [surmon-china/vue-awesome-swiper#195]
![轮播图的导航icon数量显示不对，active也没有](http://oukgs06el.bkt.clouddn.com/dxg-test-games/userHead/40e9b52a-7cc3-4a5e-baa1-d3c5fe08cfc9.jpg)

具体使用和配置如下
```build :{
   vendor: ['vue-awesome-swiper']
  },
  plugins: [{src: '~plugins/vue-awesome-swiper.js', ssr: false}],
  css: ['swiper/dist/css/swiper.css']
```
```
<div v-swiper:mySwiper="swiperOption">
              <div class="swiper-wrapper">
                <div class="swiper-slide" v-for="slide in swiperSlides">Slide {{slide}}</div>
              </div>
              <div class="swiper-pagination swiper-pagination-bullets"></div>
            </div>


 export default {
    data () {
      return {
        swiperOption: {
          pagination: '.swiper-pagination',
          slidesPerView: 5,
          centeredSlides: true,
          paginationClickable: true,
          spaceBetween: 18
        },
        swiperSlides: [1, 2, 3, 4, 5, 6, 7, 8, 9]
      }
    }
}
```

最后，请原谅我用了中文介绍我所遇到的问题，因为我英文确实比较差，请见谅！对了 这个页面我有用三个demo

**Comment by surmon-china** [comment]
你虽然循环出了多个实例，但是实际给每个实例绑定的名字却都是一样的，所以你需要指定实例名称，参考此问题

#110

**Comment by wLove-c** [comment]
![这个是3d循环的](http://oukgs06el.bkt.clouddn.com/dxg-test-games/userHead/80e58857-4e3b-416c-8b90-cc9f7f78d4e0.jpg)

![这个是3d循环的](http://oukgs06el.bkt.clouddn.com/dxg-test-games/userHead/bce286ff-8913-4a51-bf56-b2b203b6d6a6.jpg)

### 换上新的写法也不行喔 是不是那个点的class同一个类 所以有这种表现？但我换了className之后，点就不表现了，内置样式应该是根据.swiper-pagination写的，现在还是和之前那个问题一样...

**Comment by surmon-china** [comment]
pagination 作为参数传入时，可以指定不同的名字，本身的 class name 更多作用样式来使用

**Comment by surmon-china** [comment]
另外，可以升级到 v3.0.0 以上了。

**Comment by wLove-c** [comment]
@surmon-china  

!['vue+ssr报错'](http://oukgs06el.bkt.clouddn.com/dxg-test-games/userHead/d4d36958-5815-4b1b-8cff-4c5e42856d2c.jpg)

作者 您好，是这样的 我之前使用nuxt后发现 nuxt不能兼容IE 后面改回使用vue+ssr ,现在在vue的基础上使用了 swiper 出现了这个问题，当我把
```
<swiper>
    <swiper-slide></swiper-slide>
</swiper>

```
注释掉后就没问题了，有人提出过这个问题吗 有什么好的解决方案吗 麻烦了

**Comment by surmon-china** [comment]
SSR 下不可使用 组件！

**Comment by wLove-c** [comment]
@surmon-china  但我现在使用组件也没问题喔 莫非只能和nuxt那样使用吗，但我引入时应该如何配置或者说引入

**Comment by surmon-china** [comment]
你看过文档吗，组件 只能支持不依赖 window 对象的，所有依赖 window 的元素只能以 directive 处理，所以 SSR 就是为 SSR 提供的，组件是为 SPA 提供的！

**Comment by surmon-china** [comment]
如果还有更多问题，看文档，官方文档！

**Comment by wLove-c** [comment]
@surmon-china  有看的 只是 当我用文档 ssr的方式引入时，在我的组件修改参数swiperOption{}则不会起到作用，其他和nuxt的方式一样的 ，没有任何报错和警告

**Comment by wLove-c** [comment]
具体 如下 
```
import 'swiper/dist/css/swiper.css'
if (process.browser) {
	const VueAwesomeSwiper = require('vue-awesome-swiper/dist/ssr')
	Vue.use(VueAwesomeSwiper)
}
```

```
<div v-swiper="swiperOption" :instanceName="'inforSlide'" id="homeSlide">
					<div class="swiper-wrapper">
						<div class="swiper-slide" v-for="banner in banners">
							<img :src="banner">
						</div>
					</div>
					<div class="swiper-pagination swiper-pagination-bullets"></div>
				</div>
export default {
		data () {
			return {
				banners: ['/', '/', '/'],
				swiperOption: {
					pagination: '.swiper-pagination',
					paginationClickable: true,
					grabCursor: true,
					nextButton: '.swiper-button-next',
					prevButton: '.swiper-button-prev',
					// Enable debugger
					debugger: true,
					loop: true
				}
			}
		}
     }
```

**Comment by surmon-china** [comment]
难道你忽略了，我在这个页面给你留言的 升级到 v3.0.0 了吗。

然后能看到首页， v3.0.0 基于 Swiper4 吗。

你能认真点吗。

**Comment by wLove-c** [comment]
@surmon-china 

一直用的是这个...
![我用的是最新版](http://oukgs06el.bkt.clouddn.com/dxg-test-games/userHead/3c88ca83-efa2-4fef-90a1-d0729016d801.jpg)

**Comment by surmon-china** [comment]
据我所知，`coverflow` 这个 API 已经更新为 http://idangero.us/swiper/api/#coverflow-effect，所以？？？...

**Comment by wLove-c** [comment]
@surmon-china  ...我看到的swiper3.0的api..因为之前用的文档页没关闭过...好吧 我找找一些不同的地方 谢谢帮助！！

**Comment by luckboyi** [comment]
你好 我

![qq 20180425184452](https://user-images.githubusercontent.com/17244430/39241260-db8d95c0-48b8-11e8-8e77-d129e477959d.png)
我每个swiper都挂了相对应的实例  但我调用其中某一个this.customSwiperInstanceName0.autoplay.stop()会报错提示 autoplay is not defined! 请问怎么处理

**Comment by lyfpf** [comment]
这个问题似乎没有解决
