### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by hjujah** [surmon-china/vue-awesome-swiper#196]
Hi, I am getting this error when I try to mount the plugin by calling `Vue.use(VueAwesomeSwiper)`
Any ideas about how to resolve this? Thanks!

**Comment by surmon-china** [comment]
I need your more detailed error message.

**Comment by SeptemberMaples** [comment]
I am getting the same error....
I updated the Vue from 2.0.2 to 2.3.3. and then resolved it.
