### ISSUE TITLE
vue ssr下的bug

### ISSUE THREAD

**Issue by shx1545** [surmon-china/vue-awesome-swiper#197]
![image](https://user-images.githubusercontent.com/29303050/33238148-e02fca8e-d2c1-11e7-82c5-27d13d4f5b58.png)
配置是这样的，效果显示出来
![image](https://user-images.githubusercontent.com/29303050/33238152-05e76688-d2c2-11e7-815e-8d45c6360618.png)
两个按钮点击无效啊。

**Comment by surmon-china** [comment]
Fix in v3.0.0

**Comment by nwzk41** [comment]
v3.1.3 出现同样问题，navigation 配置无效 ，无法进行导航切换
