### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Leeying** [surmon-china/vue-awesome-swiper#2]
ERROR in ./~/.0.24.0@css-loader!./~/.1.0.0@vue-style-loader!./~/.0.24.0@css-loader!./~/.1.0.0@vue-style-loader!./~/.0.24.0@css-loader!./~/.1.0.0@vue-style-loader!./~/.0.24.0@css-loader!./~/.1.0.0@vue-style-loader!./~/.0.24.0@css-loader!./~/.1.0.0@vue-style-loader!./~/.0.24.0@css-loader!./~/.1.0.0@vue-style-loader!./~/.0.24.0@css-loader!./~/.3.3.1@swiper/dist/css/swiper.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!./../../../.0.24.0@css-loader/index.js!./../../../.1.0.0@vue-style-loader/index.js!./../../../.0.24.0@css-loader/index.js!./../../../.1.0.0@vue-style-loader/index.js!./../../../.0.24.0@css-loader/index.js!./../../../.1.0.0@vue-style-loader/index.js!./../../../.0.24.0@css-loader/index.js!./../../../.1.0.0@vue-style-loader/index.js!./../../../.0.24.0@css-loader/index.js!./../../../.1.0.0@vue-style-loader/index.js!./../../../.0.24.0@css-loader/index.js!./swiper.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // add the styles to the DOM
  7 | var update = require("!./../../../.1.0.0@vue-style-loader/addStyles.js")(content, {});
  8 | if(content.locals) module.exports = content.locals;

 @ ./~/.3.3.1@swiper/dist/css/swiper.css 4:14-576 13:2-17:4 14:20-582

**Comment by surmon-china** [comment]
使用姿势不对，建议使用vue-cli脚手架初始化你的项目，然后依赖使用
