### ISSUE TITLE
swiper.animate.min.js动画

### ISSUE THREAD

**Issue by jdfdcc** [surmon-china/vue-awesome-swiper#203]
你好：
        swiper.animate.min.js有没有集成进去？如果集成了，能提供一下配置吗？？

**Comment by surmon-china** [comment]
这个不适合集成呐，因为没有官方发布的 npm 包，你可以这样尝试：

```javascript
import Swiper from 'swiper'
window.Swiper = Swiper
import 'swiper.animate.min.js'
import 'animate.min.css'
swiperOptions: {
  on:{
    init(){
      swiperAnimateCache(this); //隐藏动画元素 
      swiperAnimate(this); //初始化完成开始动画
    }, 
    slideChangeTransitionEnd(){ 
      swiperAnimate(this); //每个slide切换结束时也运行当前slide动画
    } 
  }
}
```

**Comment by jdfdcc** [comment]
好的，谢谢

**Comment by NextBoy** [comment]
这样貌似不成功吧，直接报错了

**Comment by roc2539** [comment]
@jdfdcc 你成功了吗？

**Comment by roc2539** [comment]
@surmon-china  那用swiper 怎么使用动画啊？ 求大神指导啊

**Comment by wmaqingbo** [comment]
```JavaScript

**Comment by ChenJunsen** [comment]
可以的，有效果

**Comment by LamDeng** [comment]
引入swiper.animate.min.js后，划到下页，再划回来怎么没有动态效果了...

**Comment by JackXueX** [comment]
找了好久  终于可以用了  谢谢

**Comment by ccheneasy** [comment]
> ```js
> <template>
> <div class="culture">
>   <swiper :options="swiperOption" ref="mySwiper">
>     
>     <swiper-slide>
>       <div class="title ani" swiper-animate-effect="slideInLeft" swiper-animate-duration="2s">11111</div>
>       <div class="text ani" swiper-animate-effect="slideInLeft" swiper-animate-duration="2s">111111</div>
>       <div class="pics ani" swiper-animate-effect="slideInLeft" swiper-animate-duration="2s">1111111</div>
>     </swiper-slide>
>     <swiper-slide>
>       <div class="title ani" swiper-animate-effect="slideInRight" swiper-animate-duration="2s">222222</div>
>       <div class="text ani" swiper-animate-effect="slideInRight" swiper-animate-duration="2s">222222</div>
>       <div class="pics ani" swiper-animate-effect="slideInRight" swiper-animate-duration="2s">222222</div>
>     </swiper-slide>
>     <swiper-slide>
>       <div class="title ani" swiper-animate-effect="zoomIn" swiper-animate-duration="2s">3333333</div>
>       <div class="text ani" swiper-animate-effect="zoomIn" swiper-animate-duration="2s">3333333</div>
>       <div class="pics ani" swiper-animate-effect="zoomIn" swiper-animate-duration="2s">3333333</div>
>     </swiper-slide>
>   </swiper>
> </div>
> </template>
> 
> <script>
> import * as swiperAni from '@/common/js/swiper.animate.min.js'
> 
> export default {
>   name: 'culture',
>   data() {
>     return {
>       swiperOption: {
>         // loop: true,
>         effect: 'fade',
>         // 变手势
>         grabCursor: true,
>         initialSlide: 0,
>         // 滑动方向，水平horizontal，垂直vertical
>         direction: 'vertical',
>         on: {
>           init: function () {
>             console.log(this)
>             swiperAni.swiperAnimateCache(this)
>             swiperAni.swiperAnimate(this)
>           },
>           slideChange: function () {
>             swiperAni.swiperAnimate(this)
>           }
>         }
>       }
>     }
>   },
>   computed: {
>     swiper() {
>       return this.$refs.mySwiper.swiper
>     }
>   }
> }
> </script>
> ```
> 
> 这样可以用。
> 因为官方`swiper.animate.min.js`不支持 AMD/CMD/UMD 用法，所以进行了手动修改。
> 水平有限，代码卖相不太好，仅供参考。
> [swiper.animate.min.zip](https://github.com/surmon-china/vue-awesome-swiper/files/2213035/swiper.animate.min.zip)

终于解决了，感谢感谢
