### ISSUE TITLE
Object doest support property or method reLoop

### ISSUE THREAD

**Issue by smakinson** [surmon-china/vue-awesome-swiper#205]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Vue.js version and component version
^2.5.3

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### What is Expected?      
No error.

#### What is actually happening?
I see: Object doest support property or method reLoop in the console. I have not yet what causes it consistently. I can say is see it with hot reloads and I am seeing it more consistently this morning when looking at my project in ie11. It happens every time there and may be related to a redirect in vuejs from a server response error.

**Comment by smakinson** [comment]
Maybe related: https://github.com/nolimits4web/Swiper/issues/2336

**Comment by surmon-china** [comment]
v3.0.3 fix it.

**Comment by smakinson** [comment]
Awesome, thank you.
