### ISSUE TITLE
vue build err (Dom7)

### ISSUE THREAD

**Issue by baokuanze** [surmon-china/vue-awesome-swiper#206]
when i user vue-awesome-swiper in vue , build err ;
ERROR in static/js/vendor.....Unexpected token:name<Dom7> [static/js/vende.....]

**Comment by Reboca** [comment]
same question here
![image](https://user-images.githubusercontent.com/21053764/33537936-720e8598-d8f9-11e7-8bac-d30ebd9fdae1.png)
version:
    "vue": "^2.5.2",
    "vue-awesome-swiper": "^3.0.4",

**Comment by Reboca** [comment]
sorry,I check out  my webpack file and add this code solved my problem
alias: {
  'swiper$': 'swiper/dist/js/swiper.js'
}

**Comment by surmon-china** [comment]
Webpack - webpack.config.js:
```javascript
alias: {
  'swiper$': 'swiper/dist/js/swiper.js'
}
```

Nuxt.js - nuxt.config.js

```javascript
build: {
  extend(webpackConfig) {
     webpackConfig.resolve.alias['swiper$'] = 'swiper/dist/js/swiper.js'
     webpackConfig.resolve.alias['dom7$'] = 'dom7/dist/dom7.js'
  }
}
```

**Comment by surmon-china** [comment]
**If you are encountering errors while packing with webpack, please refer to the solution here [#206](https://github.com/surmon-china/vue-awesome-swiper/issues/206) [#204](https://github.com/surmon-china/vue-awesome-swiper/issues/204). Add the corresponding alias code in your webpack config.**

```javascript
alias: {
  'swiper$': 'swiper/dist/js/swiper.js'
}
```

v3.0.6 fix it.

**Comment by mushtaqh** [comment]
For anyone coming from google in 2020:
The solution above has moved to "'swiper/js", you can use
```
alias: {
  'swiper$': 'swiper/js/swiper.min.js'
}
```
Im using 
```
"swiper": "^5.4.0",
"vue-awesome-swiper": "^4.1.1"
```
