### ISSUE TITLE
ios设备，ajax动态获取数据，轮播不能自动播放，不显示pagination，出现白屏等问题

### ISSUE THREAD

**Issue by breathcold** [surmon-china/vue-awesome-swiper#209]
### 问题描述：
在ios设备上出现第一次进入应用无法自动播放，不显示pagination, 不过手动可以切换，切换至其他页面再次切换回来，可以自动播放，但是从最后一张切换到第一张时之后出现白屏

###hbuild 打包的webapp

### package.json
    "axios": "^0.17.0",
    "vue": "^2.4.2",
    "vue-awesome-swiper": "^3.0.4",
    "vue-router": "^2.7.0",
    "vuex": "^2.4.0"

#### main.js
import VueAwesomeSwiper from 'vue-awesome-swiper'
import 'swiper/dist/css/swiper.css'
Vue.use(VueAwesomeSwiper)

#### banner.vue
![qq 20171205150444](https://user-images.githubusercontent.com/24854685/33594141-ac42ad46-d9cd-11e7-94cd-77374ae401d3.png)

#### 配置
![qq 20171205150536](https://user-images.githubusercontent.com/24854685/33594177-d217a5ee-d9cd-11e7-9fc0-8ab4535d24f1.png)

![qq 20171205150330](https://user-images.githubusercontent.com/24854685/33594105-89309f5c-d9cd-11e7-82ab-d855dba7a28d.png)

![qq 20171205150727](https://user-images.githubusercontent.com/24854685/33594235-13dc7950-d9ce-11e7-95e3-f6b11ad6c12a.png)

#### 问题图片，第一张为第一次启动app时的界面，不能自动播放，没有小红点按钮
![1](https://user-images.githubusercontent.com/24854685/33594544-3ba33efa-d9cf-11e7-96f8-e78c12af7fd5.png)

#### 问题图片，第二张为切换到其他页面然后再次切回来的时的界面，貌似恢复正常
![2](https://user-images.githubusercontent.com/24854685/33594570-643e566a-d9cf-11e7-8967-41440006c231.png)

#### 问题图片，第三张为切换到其他页面然后再次切回来的时的界面，从最后一张切换回第一张时出现白屏，只有ios设备出现这个问题，但是手动滑动切换却没有白屏
![3](https://user-images.githubusercontent.com/24854685/33594641-a42aeaea-d9cf-11e7-9484-571e72689ac6.png)

**Comment by surmon-china** [comment]
按照 Issues 要求把你的提问更新后，重新打开问题。

**Comment by surmon-china** [comment]
滑动卡顿是 Swiper 本身的问题，异步加载数据，可以使用 `v-if` 的形式控制组件是否渲染，自己执行 `init` 会导致很多意料之外的异常。
