### ISSUE TITLE
example 31 :Uncaught TypeError: Controller.LinearSpline is not a constructor

### ISSUE THREAD

**Issue by jeffhuang2086** [surmon-china/vue-awesome-swiper#213]
你好，例子31在vue-cli下使用会出现如下报错，麻烦能提供一些解决方法吗？
Uncaught TypeError: Controller.LinearSpline is not a constructor
    at Swiper$1.getInterpolateFunction (swiper.esm.bundle.js?0cd5:5123)
    at setControlledTranslate (swiper.esm.bundle.js?0cd5:5139)
    at Swiper$1.setTranslate (swiper.esm.bundle.js?0cd5:5165)
    at Swiper$1.setTranslate (swiper.esm.bundle.js?0cd5:5244)......

**Comment by jeffhuang2086** [comment]
这个swiper作者已经修复bug了，麻烦作者更下下npm包吧  https://github.com/nolimits4web/Swiper/commit/fc078ef2885168678b252dd50bb5644575b154b6

**Comment by surmon-china** [comment]
swiper 只被依赖，不被合并，若有更新，直接在项目下安装新版本 Swiper 即可。

**Comment by surmon-china** [comment]
https://github.com/nolimits4web/Swiper/issues/2239

#206

**Comment by jeffhuang2086** [comment]
@surmon-china问题还是没解决，~~~~(>_<)~~~~ 31哪个例子依旧报错

**Comment by surmon-china** [comment]
在你项目的 webpack 配置中，将 alias 别名设置为 #206 所示

```javascript
alias: {
  'swiper$': 'swiper/dist/js/swiper.js'
}
```
