### ISSUE TITLE
how to require default css?

### ISSUE THREAD

**Issue by fishenal** [surmon-china/vue-awesome-swiper#214]
install this plugin with npm, ```import 'swiper/dist/css/swiper.css'```  , warn for 'module not found',
how to require css? where is the css file? copy manully?

i run dev server via ``` npm run start```

**Comment by fishenal** [comment]
我晕，在标准的vue webpack项目里，swiper.css 引入不进去啊，谁能告诉我怎么办

import 'swiper/dist/css/swiper.css' 这个目录是基于module下面的swiper的？项目里要怎么取？文档里为什么都不把这个写清楚？

css引入不进去，build都会卡住，完全不知道该怎么办啊

**Comment by fishenal** [comment]
{
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
}
写了， style-loaer， css-loader装了，只是单纯的css文件找不到

**Comment by fishenal** [comment]
` ERROR  Failed to compile with 1 errors                                 14:10:31

This dependency was not found:

* swiper/dist/css/swiper.css in ./node_modules/.npminstall/babel-loader/7.1.2/babel-loader/lib!./node_modules/.npminstall/vue-loader/13.5.0/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/App.vue

To install it, you can run: npm install --save swiper/dist/css/swiper.css`

**Comment by jeffhuang2086** [comment]
@fishenal   按照文档引入就行，是不是你的webpack版本问题
