### ISSUE TITLE
the v3.0.4 packing problem

### ISSUE THREAD

**Issue by gmdesting** [surmon-china/vue-awesome-swiper#215]
1.Normal display of plug-ins on a web page，but  When I'm packing ,it hint me no support  es6. so  I can only v2.6.7 ,it can Finish packing。
![s xk2 apm up9 s w3vs7](https://user-images.githubusercontent.com/15117107/33758284-9492f0f8-dc38-11e7-80f6-4f1ebe5ff367.png)

**Comment by surmon-china** [comment]
#206 
#204
