### ISSUE TITLE
 Expected":" in IE 11

### ISSUE THREAD

**Issue by YYQ8023** [surmon-china/vue-awesome-swiper#216]
#### Vue.js version and component version
```
"vue": "^2.5.9",
"vue-awesome-swiper": "^3.0.4",
```
I used the component in spa just like the  doc , and my app works correctly in chrome(63),wechat browser(android 7.1),but when open it in IE(ie11) or mobile browser(like qq,uc,and so on)，i met the error:
```
script1003: Expected":"
app.js(3562,1)
```

i was used 'babel-polyfill'.

**Comment by YYQ8023** [comment]
And , my app was built by `vue-cli`

**Comment by YYQ8023** [comment]
i solved this problem by adding
```
computed: {
      swiper() {
        return this.$refs.mySwiper.swiper
      }
    },

```
but i dont know what does it mean

**Comment by herpster** [comment]
Since this is still an issue, is there any official guideline on how to make it compatible with  IE11? I tried adding swiper and the dom7 dependencies to transpile setting within nuxt.config.js -> build: { transpileDependencies: ["dom7", "swiper"]}. Any advice on this is appreciated.
