### ISSUE TITLE
loop & centeredSlides & slidesPerView: 'auto'

### ISSUE THREAD

**Issue by GothWit** [surmon-china/vue-awesome-swiper#217]
[需要实现类似这样的效果](http://sandbox.runjs.cn/show/xlhzle4h)不带动画
我使用 centeredSlides: true, slidesPerView: 'auto' 能实现居中显示，但是加上loop后会出现

![image](https://user-images.githubusercontent.com/27495489/33822905-26045bd2-de94-11e7-88bd-77256cf66fbf.png)

看到之前的issues发现需要一个 loopedSlides 属性 加上这个属性后发现没有报错了
但是渲染出来的样式却乱了，切换的效果也不对。

上代码：
template：

![image](https://user-images.githubusercontent.com/27495489/33823324-b0292b84-de95-11e7-9350-bc67a63ae105.png)
script：

![image](https://user-images.githubusercontent.com/27495489/33823344-c53f3c70-de95-11e7-9fdf-ca5b05d3de2e.png)

再问一个，是否支持动态输入loopedSlides(即数组长度不确定的时候)？

**Comment by GothWit** [comment]
```
<section class="carousel">
      <swiper :options="swiperOption">
        <swiper-slide v-for="bannerItem in bannerList">
          <div class="carousel-item">
            <div class="item-img">
              <img :src="bannerItem.images_url" alt="">
            </div>
          </div>
        </swiper-slide>

        <div class="swiper-pagination" slot="pagination"></div>
      </swiper>
</section>
```

**Comment by GothWit** [comment]
```javascript
swiperOption: {
          slidesPerView: 'auto',
          spaceBetween: '6.6%',
          centeredSlides: true,
          autoHeight: true,
          loop: true,
          loopedSlides:4,
          pagination: {
            el: '.swiper-pagination',
            clickable: true,
            renderBullet(index, className) {
              return `<span id="pagination_custom" class="${className}"></span>`
            }
          }
},
```

**Comment by surmon-china** [comment]
稍后测试。

**Comment by GothWit** [comment]
好的

**Comment by surmon-china** [comment]
参数是一定不可以动态改变的，但是你可以利用 `参数需要变动的那一帧` + `$nextTick` + `v-if` 去造成 Swiper 重新初始化。

**Comment by surmon-china** [comment]
本地实测，没有错误，无法定位问题。

**Comment by youdianfan** [comment]
敢问仁兄是否解决了此问题?我也遇到一样的问题
