### ISSUE TITLE
同一个页面实例化两个swiper的情况下，给loop属性时会报错

### ISSUE THREAD

**Issue by sunmmerOne** [surmon-china/vue-awesome-swiper#218]
Error in updated hook: "TypeError: this.$parent.swiper.reLoop is not a function"

**Comment by sunmmerOne** [comment]
sometimes loop will get wrong message

**Comment by surmon-china** [comment]
能否贴一下组件代码

**Comment by surmon-china** [comment]
升级到 v3.0.7 修复此问题。
