### ISSUE TITLE
safari浏览器报错: SyntaxError: Unexpected token '*'

### ISSUE THREAD

**Issue by haosen** [surmon-china/vue-awesome-swiper#220]
safari浏览器目前不支持此运算符

**Comment by surmon-china** [comment]
和 Safari 版本有关吗，我这里测试没有问题 11.0.1 (13604.3.5)

**Comment by zhoubhin** [comment]
@surmon-china 我也遇到同样问题，iOS10 Safari浏览器，测试环境与正式环境均出现该错误，iOS11则此无问题

**Comment by surmon-china** [comment]
这个问题 极有可能 是由于  Swiper 内部的代码造成的，先重新开放

**Comment by xing00** [comment]
找到解决方法了，之前是手动将连乘换成Math.pow，后来发现babel有插件可以转换，插件名叫：babel-plugin-transform-exponentiation-operator，装完后在.babelrc中加入： "plugins": ["transform-exponentiation-operator"]，就可以了

**Comment by LX314** [comment]
> 找到解决方法了，之前是手动将连乘换成Math.pow，后来发现babel有插件可以转换，插件名叫：babel-plugin-transform-exponentiation-operator，装完后在.babelrc中加入： "plugins": ["transform-exponentiation-operator"]，就可以了


详细的配置可以给一下吗, 我也碰到这个问题了

**Comment by xing00** [comment]
@LX314 npm装一下依赖babel-plugin-transform-exponentiation-operator，然后在.babelrc里面添加plugins就行了 
![屏幕快照 2019-03-25 下午2 27 22](https://user-images.githubusercontent.com/7943928/54899254-26c19980-4f0a-11e9-941b-4093fea84f3f.png)

**Comment by LX314** [comment]
@xing00 

`{
  "presets": ["es2015"],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-exponentiation-operator"
  ]
}
`

看文档的配置和你的一样, 但是并不能生效, 是还需要在哪里配置吗

**Comment by xing00** [comment]
> @xing00
> 
> `{ "presets": ["es2015"], "plugins": [ "@babel/plugin-syntax-dynamic-import", "@babel/plugin-transform-exponentiation-operator" ] } `
> 
> 看文档的配置和你的一样, 但是并不能生效, 是还需要在哪里配置吗

不用啊，我这就是这样子配置的，没有去配其他东西了

**Comment by ialmost** [comment]
> 找到解决方法了，之前是手动将连乘换成Math.pow，后来发现babel有插件可以转换，插件名叫：babel-plugin-transform-exponentiation-operator，装完后在.babelrc中加入： "plugins": ["transform-exponentiation-operator"]，就可以了

使用你的方法无法解决，最后发现是 swiper 引发的问题，升级到 swiper 6 即可解决
