### ISSUE TITLE
loop为true时，复制的slider没有绑上事件

### ISSUE THREAD

**Issue by coolicer** [surmon-china/vue-awesome-swiper#222]
```html
<swiper-slide @click="showImg(index)" v-for="(slide, index) in swiperSlides" :key="index">
    <div class="item" :style="{backgroundImage: 'url(' + slide.url + ')'}"></div>
</swiper-slide>
```

```js
swiperOption: {
        autoplay: {
          delay: 3000,
          stopOnLastSlide: false,
          disableOnInteraction: false,
        },
        // loop : true,
        slidesPerView : 3,
        spaceBetween : 20
      },
```

**Comment by surmon-china** [comment]
这问题很早很早很早就有人提过了，为什么不搜索。
#21 #28 #131

**Comment by coolicer** [comment]
我试过了也不行..这就尴尬了

**Comment by surmon-china** [comment]
那这样，给 `<swiper @click="something">` 绑定点击事件，然后在事件中，获取 `swiper.activeIndex` 类似这样的实时参数，做相应处理

**Comment by coolicer** [comment]
我暂时去掉这种模式了

**Comment by dennisxnew** [comment]
Hi, has the problem been solved?

I use the slideToLoop() method to avoid entering copy slide and look like solve the problem temporarily.

Looks like this:
Swiper.vue
```vue
<swiper :options="swiperOption" ref="mySwiper" @slideChange="onSlide" v-if="swiperList.length > 0">
  <swiper-slide v-for="(item,index) in swiperList" :index="index" :key="item.index">
	<!-- something -->
  </swiper>
</swiper-slide>
```


Swiper.js
```javascript
onSlide() {
  const realIndex = this.$refs.mySwiper.swiper.realIndex;
  if(realIndex == 0){
    this.$refs.mySwiper.swiper.slideToLoop(0, 10, true);
  }else if(realIndex == this.swiperList.length - 1){
    this.$refs.mySwiper.swiper.slideToLoop(realIndex, 10, true);
  }            
}
```

**Comment by dreamHeroK** [comment]
> Hi, has the problem been solved?
> 
> I use the slideToLoop() method to avoid entering copy slide and look like solve the problem temporarily.
> 
> Looks like this:
> Swiper.vue
> 
> ```
> <swiper :options="swiperOption" ref="mySwiper" @slideChange="onSlide" v-if="swiperList.length > 0">
>   <swiper-slide v-for="(item,index) in swiperList" :index="index" :key="item.index">
>     
>   </swiper>
> </swiper-slide>
> ```
> 
> Swiper.js
> 
> ```js
> onSlide() {
>   const realIndex = this.$refs.mySwiper.swiper.realIndex;
>   if(realIndex == 0){
>     this.$refs.mySwiper.swiper.slideToLoop(0, 10, true);
>   }else if(realIndex == this.swiperList.length - 1){
>     this.$refs.mySwiper.swiper.slideToLoop(realIndex, 10, true);
>   }            
> }
> ```

Thank you for sharing
I tried @ click. Native. But it didn't work

**Comment by wilsonssss** [comment]
Thanks to @dennisxnew ,  if change ` @slideChange="onSlide"` into ` @slideChangeTransitionEnd="onSlide"`, will be better

`
<swiper :options="swiperOption" ref="mySwiper" @slideChangeTransitionEnd="onSlide" v-if="swiperList.length > 0">
  <swiper-slide v-for="(item,index) in swiperList" :index="index" :key="item.index">
    
  </swiper>
</swiper-slide>
`

`
onSlide() {
  const realIndex = this.$refs.mySwiper.swiper.realIndex;
  if(realIndex == 0){
    this.$refs.mySwiper.swiper.slideToLoop(0, 10, true);
  }else if(realIndex == this.swiperList.length - 1){
    this.$refs.mySwiper.swiper.slideToLoop(realIndex, 10, true);
  }            
}
`
