### ISSUE TITLE
从后台取到的数据，最后一屏滑到第一屏没有动画效果

### ISSUE THREAD

**Issue by a494836960** [surmon-china/vue-awesome-swiper#224]
#### Vue.js version and component version
  "vue": "^2.5.2",    "vue-awesome-swiper": "^3.0.6",
#### Reproduction Link
https://jsfiddle.net/39epgLj0/52/  代码差不多就是这样。。 不会设置组件环境，，运行不起来。。

#### Steps to reproduce
options 只设置了 loop:true , 配置了 loop:true 从后台去到的banners 数据 
#### What is Expected?      
最后一屏到第一屏有动画效果
#### What is actually happening?
 从最后一屏继续往后滑到第一屏没有动画效果。

**Comment by surmon-china** [comment]
这个问题是我遇到的所有中文问题中最优秀的，没有之一。所以，我会严格测试下。

**Comment by johnnyGoo** [comment]
缺少指针
//缺少指针var self=this;	
setTimeout(()=>{
      	self.banners=
});

**Comment by a494836960** [comment]
@johnnyGoo 不会缺少指针哦。 箭头函数可以使用 this。

**Comment by surmon-china** [comment]
@a494836960 example 中 没有 this

**Comment by a494836960** [comment]
@surmon-china  哦哦，，例子我没测。。- -！

**Comment by a494836960** [comment]
但是我提的问题是存在的。。

**Comment by GOGOGOSIR** [comment]
问题解决了吗

**Comment by a494836960** [comment]
没有哦。。 项目暂时没时间做，，，没管了。 作者也没给答案。。

**Comment by alicksnake22** [comment]
问题解决了吗，还是这样的问题呢，swiper4没有这个问题

**Comment by delehei6309** [comment]
确实存在这个问题，没办法直接去渲染，使用swiper.appendSlide(slide)去追加吧

**Comment by EPSON-LEE** [comment]
如果是自己写的动画效果，那么可以用 swiper-slide-active 作为动画class样式的父级class
```
.swiper-slide-active {
    .animate {
			animation: tada 0.5s;
			animation-direction: alternate;
		}
	}
```

**Comment by surmon-china** [comment]
我猜想这是 Swiper 本身的问题，在 Swiper5 / vue-awesome-swiper 4.x 中，loop 带来的相关的问题基本已消失殆尽或有了比较完备的解决方案，动画问题也未再出现。

所以请升级吧。

**Comment by NightFullMoon** [comment]
> 如果是自己写的动画效果，那么可以用 swiper-slide-active 作为动画class样式的父级class
> 
> ```
> .swiper-slide-active {
>     .animate {
> 	animation: tada 0.5s;
> 	animation-direction: alternate;
>   }
> }
> ```

这个方案可行
