### ISSUE TITLE
I use the swiper4 callbackfunction, but i console.log(this.swiper),the answer is undefined,i need help 

### ISSUE THREAD

**Issue by wenguangcheng** [surmon-china/vue-awesome-swiper#228]
name: "Download",
    data() {
      return {
        changeActive:0,
        swiperOption: {
          loop: true,
          autoHeight: true,
          // some swiper options/callbacks
          // 所有的参数同 swiper 官方 api 参数
          // ...
          pagination:{
            el:'.nav',
            type:'custom',
          },
          on:{
            init:()=>{

            },
            slideChange:()=>{
              console.log(this.swiper)
            },
            onSlideChangeEnd:()=>{

            }
          }
        }
      }
    },
    watch:{

    },
    methods: {
      changeSwiper(item){
        this.swiper.slideTo(item+1,1000,false);
        this.changeActive=item;
      },
      // test(){
      //
      // }

    },
    computed: {
      swiper() {
        return this.$refs.mySwiper.swiper
      }
    },
    mounted() {
  
    },
    components: {
      swiper,
      swiperSlide
    }
按照道理来说我这么写应该是没有问题，
但是打印的时候就报错了,直接让我很懵逼!
我也打印了this.swiper了,一直是undefined

**Comment by surmon-china** [comment]
箭头函数和对象函数的上下文区别明白吗？JS 的基础明白吗？
