### ISSUE TITLE
开发模式 nuxtjs  cannot read property classList of undefined 

### ISSUE THREAD

**Issue by CGerAJ** [surmon-china/vue-awesome-swiper#229]
按照官方vue-awesome-swiper   Demo nuxtjs文件配置
Vue.js v2.4.4
"vue-awesome-swiper": "^3.0.6"
"nuxt": "^1.0.0-rc11",

初始化是成功改的

![wx20171226-134000](https://user-images.githubusercontent.com/20548301/34348004-89c5e0be-ea42-11e7-9d64-03fef80c5889.png)

**Comment by CGerAJ** [comment]
nuxt.config.js 增加webpackConfig 配置还是还是报错

extend (webpackConfig, {isDev, isClient, isServer}) {
      // 处理 Swiper4 下的 dom7 模块的语法问题
      webpackConfig.resolve.alias['swiper$'] = 'swiper/dist/js/swiper.js'
      webpackConfig.resolve.alias['dom7$'] = 'dom7/dist/dom7.js'
    }

**Comment by CGerAJ** [comment]
https://github.com/surmon-china/vue-awesome-swiper/blob/df4840ff95f6855b71a013d7696350dc117103aa/examples/nuxt-ssr-example/nuxt-ssr-example.vue#L27
```
建议修改 <div class="swiper-wrapper my-wrapper">
```

https://github.com/surmon-china/vue-awesome-swiper/blob/df4840ff95f6855b71a013d7696350dc117103aa/examples/nuxt-ssr-example/nuxt-ssr-example.vue#L5

```
建议修改   <div class="swiper-slide my-slide" v-for="banner in banners"> 
```

**Comment by boyWangaC** [comment]
加载完后图片有显示但没轮播，是什么原因啊？

**Comment by see311** [comment]
你好，我也出现了这个问题，具体是如何修复的呢？没看太懂

**Comment by surmon-china** [comment]
我最近测试下， 尽快修复

**Comment by xjccc** [comment]
这个只有一张图的时候。。也会报这个错误

**Comment by surmon-china** [comment]
@CGerAJ @xjccc 分别在什么环境下得到这个错误，IE吗？

**Comment by surmon-china** [comment]
是 example 的问题，抱歉，我的锅。

**Comment by dr1ss** [comment]
I got the same problem when trying the ssr example

nuxt: v.1.1.1
vue-awesome-swiper: 3.1.2

**Comment by iooops** [comment]
这个问题好像还在……
