### ISSUE TITLE
建议增加pagination的颜色可配置

### ISSUE THREAD

**Issue by imcoka** [surmon-china/vue-awesome-swiper#23]
.swiper-pagination-bullet-active {
    background: @color;
}

**Comment by surmon-china** [comment]
[http://www.swiper.com.cn/api/pagination/2014/1217/68.html](url)

可以参考官方的自定义分页器api，或者使用css来控制颜色，能实现你的需求；
组件应该尽量避免与官方api的差异，感谢反馈。

**Comment by imcoka** [comment]
可能是我没有描述清楚，我的组件是独立的，style 添加了scoped， 官方没有提供修改分页图标颜色的API，采用样式覆盖在scoped下行不通。感谢回复。在 2016年12月25日，22:46，Surmon <notifications@github.com> 写道：http://www.swiper.com.cn/api/pagination/2014/1217/68.html可以参考官方的自定义分页器api，或者使用css来控制颜色，能实现你的需求；
组件应该尽量避免与官方api的差异，感谢反馈。—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/surmon-china/vue-awesome-swiper","title":"surmon-china/vue-awesome-swiper","subtitle":"GitHub repository","main_image_url":"<a href="<a href="<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>" class=""><a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png&lt;/a&gt;" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png&lt;/a&gt;</a></a>" class=""><a href="<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>" class=""><a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png&amp;lt;/a&amp;gt" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png&amp;lt;/a&amp;gt</a>;" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png&amp;lt;/a&amp;gt" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png&amp;lt;/a&amp;gt</a>;</a></a>","avatar_image_url":"<a href="<a href="<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>" class=""><a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png&lt;/a&gt;" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png&lt;/a&gt;</a></a>" class=""><a href="<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>" class=""><a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png&amp;lt;/a&amp;gt" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png&amp;lt;/a&amp;gt</a>;" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png&amp;lt;/a&amp;gt" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png&amp;lt;/a&amp;gt</a>;</a></a>","action":{"name":"Open in GitHub","url":"<a href="<a href="<a href="<a href="https://github.com/surmon-china/vue-awesome-swiper" class="">https://github.com/surmon-china/vue-awesome-swiper</a>" class=""><a href="https://github.com/surmon-china/vue-awesome-swiper" class="">https://github.com/surmon-china/vue-awesome-swiper</a></a>" class=""><a href="<a href="https://github.com/surmon-china/vue-awesome-swiper" class="">https://github.com/surmon-china/vue-awesome-swiper</a>" class=""><a href="https://github.com/surmon-china/vue-awesome-swiper&lt;/a&gt;" class="">https://github.com/surmon-china/vue-awesome-swiper&lt;/a&gt;</a></a>" class=""><a href="<a href="<a href="https://github.com/surmon-china/vue-awesome-swiper" class="">https://github.com/surmon-china/vue-awesome-swiper</a>" class=""><a href="https://github.com/surmon-china/vue-awesome-swiper" class="">https://github.com/surmon-china/vue-awesome-swiper</a></a>" class=""><a href="<a href="https://github.com/surmon-china/vue-awesome-swiper" class="">https://github.com/surmon-china/vue-awesome-swiper</a>" class=""><a href="https://github.com/surmon-china/vue-awesome-swiper" class="">https://github.com/surmon-china/vue-awesome-swiper</a></a></a></a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@surmon-china in #23: [<a href="<a href="<a href="<a href="http://www.swiper.com.cn/api/pagination/2014/1217/68.html" class="">http://www.swiper.com.cn/api/pagination/2014/1217/68.html</a>" class=""><a href="http://www.swiper.com.cn/api/pagination/2014/1217/68.html" class="">http://www.swiper.com.cn/api/pagination/2014/1217/68.html</a></a>" class=""><a href="<a href="http://www.swiper.com.cn/api/pagination/2014/1217/68.html" class="">http://www.swiper.com.cn/api/pagination/2014/1217/68.html</a>" class=""><a href="http://www.swiper.com.cn/api/pagination/2014/1217/68.html&lt;/a&gt;" class="">http://www.swiper.com.cn/api/pagination/2014/1217/68.html&lt;/a&gt;</a></a>" class=""><a href="<a href="<a href="http://www.swiper.com.cn/api/pagination/2014/1217/68.html" class="">http://www.swiper.com.cn/api/pagination/2014/1217/68.html</a>" class=""><a href="http://www.swiper.com.cn/api/pagination/2014/1217/68.html" class="">http://www.swiper.com.cn/api/pagination/2014/1217/68.html</a></a>" class=""><a href="<a href="http://www.swiper.com.cn/api/pagination/2014/1217/68.html&amp;lt;/a&amp;gt" class="">http://www.swiper.com.cn/api/pagination/2014/1217/68.html&amp;lt;/a&amp;gt</a>;" class=""><a href="http://www.swiper.com.cn/api/pagination/2014/1217/68.html&amp;lt;/a&amp;gt" class="">http://www.swiper.com.cn/api/pagination/2014/1217/68.html&amp;lt;/a&amp;gt</a>;</a></a>](url)\r\n\r\n可以参考官方的自定义分页器api，或者使用css来控制颜色，能实现你的需求；\r\n组件应该尽量避免与官方api的差异，感谢反馈。"}],"action":{"name":"View Issue","url":"<a href="<a href="<a href="<a href="https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495" class="">https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495</a>" class=""><a href="https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495" class="">https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495</a></a>" class=""><a href="<a href="https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495" class="">https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495</a>" class=""><a href="https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495&lt;/a&gt;" class="">https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495&lt;/a&gt;</a></a>" class=""><a href="<a href="<a href="https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495" class="">https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495</a>" class=""><a href="https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495" class="">https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495</a></a>" class=""><a href="<a href="https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495" class="">https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495</a>" class=""><a href="https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495" class="">https://github.com/surmon-china/vue-awesome-swiper/issues/23#issuecomment-269125495</a></a></a></a>"}}}

**Comment by surmon-china** [comment]
是的，因为使用scoped标签，生成的css将包含一个随机标签（属性选择器）来标记作用范围，并且子组件不会作为所在宿主组件的元素包含在范围内，所以它不会应用，这是vue的实现机制导致的，目前vue组件的模板里还没有可选的类似ng2的多种样式应用机制，所以目前可以用

1. 需要应用pagination样式的组件，不适用scoped标签
2. 将pagination样式定义在全局公公的css中

但是组件本身应该是不会有大的和官方差异较大的改动了，
如果后续有更好的方法，我会在此留言。

**Comment by imcoka** [comment]
非常感谢Surmon。

**Comment by qinouz** [comment]
终于  解决了  我都想去 css改源码了

**Comment by wildescarrot** [comment]
可以把style的scoped去掉哦
