### ISSUE TITLE
SPA mode get swiper instance undefined

### ISSUE THREAD

**Issue by Xujkstra** [surmon-china/vue-awesome-swiper#230]
#### Vue.js version 2.3.4, component version 2.6.7, swiper 3.2.4

I can't get swiper instance by computed 

example code below
```
<template>
<swiper class="honor-carousel" :options="config" ref="honorSwiper">
  <swiperSlide
    v-for="(item, idx) in honorList"
    :key="idx">
    <div class="honor-item">
      <div class="img">
        <img :src="item.img" alt="">
      </div>
      <div class="text">{{ item.title }}</div>
    </div>
  </swiperSlide>
</swiper>
</template>

<script>
import { swiper, swiperSlide } from 'vue-awesome-swiper'
import { honorList } from './data'
export default {
  name: 'honor',
  components: {
    swiper,
    swiperSlide
  },
  data() {
    return {
      config: {
        pagination: '.swiper-pagination',
        spaceBetween: 14,
        slidesPerView: 1,
        loop: true,
        loopAdditionalSlides: 10,
				initialSlide: 1,
        paginationClickable: true,
				grabCursor: true,
        onSlideChangeEnd: this.check
      },
      honorList
    }
  },
  computed: {
    __swiper__() {
      return this.$refs.honorSwiper.swiper
    }
  },
  methods: {
    check() {
      console.log(this.__swiper__)
    }
  },
  mounted() {
    console.log(this.__swiper__)
  }
}
</script>
```

there is no async process in this example.
the check methods and mounted methods output undefined both,
what should i do to get the swiper instance?
hope to get your reply, thx.

**Comment by Xujkstra** [comment]
i guess the reason is the callback onSlideChangeEnd, because if i remove it, i can get the right result, but what can i do the resolve this problem?

**Comment by nickensoul** [comment]
@Xujkstra as I understand, we should use the swiper’s API as follows to the [official documentation](http://idangero.us/swiper/api/#events).
I mean, you should put `onSlideChangeEnd ` callback into `on` property of `config` object.
Then, for example, save `this context` to temporary variable, so you’ll able to call component’s methods etc.

```
data () {
let _this = this
  return {
    config: {
      // ...
      on: {
          slideChangeTransitionEnd () {
            _this.check()
          }
        }
    }
  }
}
```

**Comment by surmon-china** [comment]
@Xujkstra You can try it:

```html
<swiper class="honor-carousel" :options="config" :not-next-tick="true" ref="honorSwiper">
```

**Comment by Xujkstra** [comment]
@surmon-china  still get undefined.

**Comment by Xujkstra** [comment]
@nickensoul  I am using swiper 3.2.4, I'm afraid the on method is in swiper4

**Comment by surmon-china** [comment]
@Xujkstra Try replace `not-next-tick`  to `notNextTick`

**Comment by Xujkstra** [comment]
@surmon-china  same, the not-next-tick is no different from 'notNextTick'

**Comment by surmon-china** [comment]
@Xujkstra Try remove the underline.
```javascript
computed: {
    swiperInstance() {
      return this.$refs.honorSwiper.swiper
    }
}
```

**Comment by Xujkstra** [comment]
@surmon-china @nickensoul  the issue happens when i try to invoke a fuction in methods, if i just use a normal function, i can get the right answer.

**Comment by Xujkstra** [comment]
@surmon-china  remove underline still can't resolve the issue but if use `this.$refs.honorSwiper.swiper`in callback I get undefined when the callback trigger the first time, and then i can get the right result, why will this happen .

**Comment by Xujkstra** [comment]
The right approach is add this.$nextTick in the callback.
```
check() {
   this.$nextTick(() => {
     console.log(this.swiperInstance)
    })
 }
```

**Comment by surmon-china** [comment]
@Xujkstra Because https://github.com/surmon-china/vue-awesome-swiper/blob/v2.6.7/src/swiper.vue#L67

**Comment by Xujkstra** [comment]
@surmon-china  thank's for your patient reply, appreciate a lot.

**Comment by leobaixinxin** [comment]
can you get the swiperInstance in the mouted state by adding this.$nextTick in the callback ? @Xujkstra

**Comment by Finley-Zhang** [comment]
so, to return the swiper is not a good idea?
