### ISSUE TITLE
z-index fixed to 1 produce bugs in some framework (vuetify)

### ISSUE THREAD

**Issue by titouancreach** [surmon-china/vue-awesome-swiper#233]
#### Vue.js version and component version
vue-awesome-swiper 3.0.6
vue 2.5.13

I noticed the z-index of the swiper is fixed to 1.

![screenshot at 2017-12-27 12-13-08](https://user-images.githubusercontent.com/3995719/34380116-6f5b8a5e-eaff-11e7-9c2a-3f4f55cc5576.png)

That cause some problems (for example some css framework that inherit from z-index or have z-index auto or compute their own z-index based of the parent) (vuetify in my case).

I also noticed that 

```
.swiper-container {
  z-index: auto !important;
}

.swiper-wrapper {
  z-index: auto !important;
}
```
Fix the problem and doesn't change anything in the slider. Is there a particular reason to set the z-index to 1 ?

**Comment by surmon-china** [comment]
This question is about swiper, I found similar answers in swiper's issues, it seems that your approach is right, just overwrite css to solve the problem, swiper allowed to do so.

https://github.com/nolimits4web/Swiper/issues/1385
https://github.com/nolimits4web/Swiper/issues?page=1&q=z-index&utf8=%E2%9C%93
