### ISSUE TITLE
为什么不能自动轮播？我用的方式不对吗

### ISSUE THREAD

**Issue by wkh2** [surmon-china/vue-awesome-swiper#235]
<div v-swiper:mySwiper="swiperOption">
        <div class="swiper-wrapper">
            <div class="swiper-slide" v-for="(banner,index) in imgData" :key="index">
                <a :href="banner.linkUrl">
                    <img :src="banner.imageUrl" class="swiper-lazy">
                </a>
            </div>
        </div>
        <div class="swiper-pagination swiper-pagination-bullets" v-show="isShowNav"></div>
    </div>

data() {
        return {
            swiperOption: {
                autoplay: 4000,
                pagination: '.swiper-pagination',
                loop: true,
                paginationClickabl: true,
                paginationHide: true,
                autoplayDisableOnInteraction: false,
                setWrapperSize: true,
                mousewheelControl: true,
                observeParents: true
            },
            swiperSlides: [],
            isShowNav: true,
            imgData: [
                {
                    'imageUrl': '//img10.jd.id/Indonesia/nHBfsgAAAgAAAAsANREWiwAA2Ew.jpg',
                    'name': null,
                    'linkUrl': '//m.jd.id/promo_vLTZ2zSubyRpC.html'
                }, {
                    'imageUrl': '//img10.jd.id/Indonesia/nHBfsgAAAwAAABwAMEmLiAABZgE.jpg',
                    'name': null,
                    'linkUrl': '//m.jd.id/promo_pCyEWvcwkPAY.html'
                }, {
                    'imageUrl': '//img10.jd.id/Indonesia/nHBfsgAABwAAAAcALehDXwABFZk.jpg',
                    'name': null,
                    'linkUrl': '//m.jd.id/promo_travel_japan.html'
                }, {
                    'imageUrl': '//img10.jd.id/Indonesia/nHBfsgAACAAAAAMAMvkkTwAPOl4.jpg',
                    'name': null,
                    'linkUrl': '//m.jd.id/promo_jdflight_harbolnas.html'
                }]
        }
    },

**Comment by surmon-china** [comment]
这一类问题！！！！仔细阅读 Swiper 的官方文档！！！
