### ISSUE TITLE
不能能过回调改变data的数据

### ISSUE THREAD

**Issue by yaoyuande** [surmon-china/vue-awesome-swiper#236]
data(){
  return{doLike:false,
      swiperOption: {
        notNextTick: true,
        on: {
          // slideChangeTransitionEnd: function() {
          //   active_index = this.activeIndex;这里可以访问
          // }
        }
    }
}
  computed: {
    swiper() {
      return this.$refs.mySwiper.swiper;
    }
  },
  mounted() {
    let self = this;
    this.swiper.onSlideChangeTransitionEnd(function(){//这里报错  is not a Function
      alert(11111)
    });
    console.dir(this.swiper)
  },
请问是怎么回事

**Comment by surmon-china** [comment]
如果你不具有基本的问题排查能力，任何人无法帮助你
