### ISSUE TITLE
prev and next not working

### ISSUE THREAD

**Issue by alziqziq** [surmon-china/vue-awesome-swiper#239]
from display none, button prev and next not working

**Comment by raintao** [comment]
me too

**Comment by raintao** [comment]
you need just do this: 
    nextButton: '.swiper-button-next',
    prevButton: '.swiper-button-prev',

**Comment by surmon-china** [comment]
@alziqziq 
@raintao 

是没有升级彻底导致的问题，应该是由于仅仅升级了组件，而没有对遗留的 `node_modules/swiper` 进行升级导致的，而使用 v4.0.0 的 API 应用在 v3.0.0 的 Swiper 上是无效的，所以。

1. remove dir `node_modules/swiper` 

2. remove `"swiper": "^3.x.x"` in `package.json`

3. `npm i swiper --save`
