### ISSUE TITLE
zoom bug

### ISSUE THREAD

**Issue by yanxiafu** [surmon-china/vue-awesome-swiper#240]
最新版及2.6.7都尝试过，移动端使用，通过后台取数据用v-for渲染swiper slide 开启zoom,双击放大，图片无法拖动,强制拖动是翻页，后面一张图片默认大小覆盖在这张图片上面，之前做别的项目直接用的swiper3未发现此类问题，这问题别人也遇到过，请排查

**Comment by surmon-china** [comment]
有时间就测试。

**Comment by yanxiafu** [comment]
自己已经解决了，需要在swiperOption里面init:false，然后异步取得数据后重新init才行，因为默认int还没数据放大后swiper-zoom-container不会正常translate
