### ISSUE TITLE
Autoplay doesn't have delay on Nuxt setup

### ISSUE THREAD

**Issue by bovas85** [surmon-china/vue-awesome-swiper#241]
#### Steps to reproduce
Visit the site and scroll down to where the animated slider is

#### What is Expected?      
Delay set as below
```
autoplay: {
    delay: 3000,
    disableOnInteraction: true
}
```
#### What is actually happening?
No delay between animations

**Comment by surmon-china** [comment]
http://idangero.us/swiper/api/#autoplay

As you can see in the docs, the effect of delay is to set the interval between any rotation, not really delaying the animation. I open your site and find that everything is as expected. Animations occur every 3000ms.

**Comment by bovas85** [comment]
No I had to manually create an interval for this to happen (every 5 seconds actually)
