### ISSUE TITLE
can not slide when I combine with bootstrap modal??

### ISSUE THREAD

**Issue by alziqziq** [surmon-china/vue-awesome-swiper#247]

**Comment by surmon-china** [comment]
Show me the code.

**Comment by akbarjoudi** [comment]
I have the same problem and the slide is not done

`<b-modal id="modal-1" title="BootstrapVue">
    <swiper class="swiper" :options="swiperOption" ref="shareSwiper">
        <swiper-slide>Slide 1</swiper-slide>
        <swiper-slide>Slide 2</swiper-slide>
        <swiper-slide>Slide 3</swiper-slide>
        <swiper-slide>Slide 4</swiper-slide>
        <swiper-slide>Slide 5</swiper-slide>
        <swiper-slide>Slide 6</swiper-slide>
        <swiper-slide>Slide 7</swiper-slide>
        <swiper-slide>Slide 8</swiper-slide>
        <swiper-slide>Slide 9</swiper-slide>
        <swiper-slide>Slide 10</swiper-slide>
        <div class="swiper-pagination" slot="pagination"></div>
        <div class="swiper-button-prev" slot="button-prev"></div>
        <div class="swiper-button-next" slot="button-next"></div>
      </swiper>
  </b-modal>`

**Comment by NikoPushkin** [comment]
Same problem. Slider doesn't work when modal was opened first time after page updating but works in second time. So strange
`
        <b-modal class='preset-modal' hide-footer centered size='l' ref='preset-modal' id='modal-preset'>
          <swiper ref='modalSwiperRef' class="swiper" :options="swiperOption">

            <swiper-slide v-for='presetImage in modalSwiper'
                          :key='presetImage.id'
            >
              <img class='modal-swiper-image' :src="presetImage">
            </swiper-slide>

            <div class="swiper-button-prev" @click='prevModalImage' slot="button-prev"></div>
            <div class="swiper-button-next" @click='nextModalImage' slot="button-next"></div>
          </swiper>
        </b-modal>
`
