### ISSUE TITLE
IE9、10下有报错：SCRIPT438: 对象不支持“use”属性或方法

### ISSUE THREAD

**Issue by imf7** [surmon-china/vue-awesome-swiper#249]
Vue.js version and component version
"vue": "^2.5.13", "vue-awesome-swiper": "^3.1.0",

Reproduction Link

Steps to reproduce
引入组件，build项目后用IE9、10进行预览

What is Expected?
希望能够兼容IE9、10

What is actually happening?
IE9、10发生了报错：SCRIPT438: 对象不支持“use”属性或方法

**Comment by surmon-china** [comment]
我比较关系 `SCRIPT438: 对象不支持“use”属性或方法` 这行的错误的具体堆栈信息，这样才能定位到问题。

**Comment by imf7** [comment]
项目build后会产生这样一行代码“return tt.use([nt,it,rt,at,ot,ut,dt,ht,mt,_t,yt,Mt,xt,St,Ct,Dt,Et,Pt,Ft,jt,Ht,zt,Wt])”引起的报错；
如果要还原报错，可以直接在原生IE10中打开官方Demo页面（https://surmon-china.github.io/vue-awesome-swiper/）打开浏览器的开发者工具-控制台，刷新即可看到报错内容

**Comment by surmon-china** [comment]
我会想办法测试下，谢谢你的反馈。

**Comment by imf7** [comment]
辛苦开发者，为开源精神点赞，项目中使用了这个组件，但因此问题未能兼容IE10、9版本，确实有些遗憾。大家一起努力为前端贡献！

**Comment by surmon-china** [comment]
@imf7 抱拳

**Comment by imf7** [comment]
http://idangero.us/swiper/demos/
用IE10访问官方Demo确实没有问题，但是我在本地通过咱们的组件build项目时还是存在这个问题，可以确定swiper@4.1.0@swiper的版本是4.1.0
你可以部署一个vue的hello项目，只引入咱们的vue-awesome-swiper组件，然后build一个版本看看，确实还是存在这个报错

**Comment by surmon-china** [comment]
我试一下，因为暂时没有 win 的机器。

**Comment by surmon-china** [comment]
尴尬了，我这里虚拟机不好用，改天找台 win 机器测试。

**Comment by surmon-china** [comment]
也许我的 Win10 内置的是 IE11，测试了官网和组件的 example，都能正常工作。

**Comment by imf7** [comment]
是的，需要纯正的原生IE10、IE9，IE11本身内置了该方法，所以不会报错。你需要搞个虚拟机安装真正的IE10才会发现bug

**Comment by tgxhx** [comment]
最近也遇到这个问题，楼主如果还没有解决的话可以参考一下[http://www.cnblogs.com/tgxh/p/8927260.html](http://www.cnblogs.com/tgxh/p/8927260.html)

**Comment by imf7** [comment]
太感谢了，我去试试，让项目支持IE10
