### ISSUE TITLE
2.2.8版本在vue-cli框架下build的时候报错

### ISSUE THREAD

**Issue by TerryZwei** [surmon-china/vue-awesome-swiper#25]
ERROR in static/js/0.de910ca440d1eebd3dd8.js from UglifyJs
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/vue-awesome-swiper/index.js:15,0]

在vue-cli里面build的时候，压缩js的时候报错。

**Comment by surmon-china** [comment]
升级

**Comment by TerryZwei** [comment]
vue-awesome-swiper最高版本不是2.2.8吗？

**Comment by surmon-china** [comment]
现在是2.2.9了
