### ISSUE TITLE
undefined is not an object (evaluating 'e.gesture.image.transform')

### ISSUE THREAD

**Issue by daidi** [surmon-china/vue-awesome-swiper#250]
使用版本 "vue-awesome-swiper": "2.4.0"，本地有效，现网大量出现错误：undefined is not an object (evaluating 'e.gesture.image.transform')
更新到v2.6.7或者v4变成白屏。不知道是不是已知问题

**Comment by surmon-china** [comment]
把 `node_modules` 及 `package.json` 中对应的依赖项删除，重新安装，按照 Swiper4.0 的 API 进行配置，如果还有这个问题，才是真有问题。

**Comment by daidi** [comment]
2.5.x都没问题，看了下是2.6.0开始有这个问题的

**Comment by surmon-china** [comment]
我意思是，你可以按照我上面所说的，使用最新版组件，按照最新版的 API 进行配置，应该是能解决问题的，旧版本的构建方式存在缺陷。
