### ISSUE TITLE
onSlideChangeEnd 事件无效

### ISSUE THREAD

**Issue by goldencolor** [surmon-china/vue-awesome-swiper#255]
onSlideChangeEnd 事件无效，用空白项目也是，很奇怪啊。。。vue 2.5

`<template>
  <swiper :options="swiperOption" ref="mySwiper">
      <swiper-slide v-for="(banner,index) in banners" :key="index">
        {{index}}
      </swiper-slide>
    <div class="swiper-pagination" slot="pagination"></div>
  </swiper>
</template>
<script>
import { swiper, swiperSlide } from "vue-awesome-swiper"

export default {
  data () {
    return {
      banners: [{

      }, {

      }, {

      }],
      swiperOption: {
        notNextTick: true,
        autoplay: 1000,
        pagination: '.swiper-pagination',
        paginationClickable: true,
        mousewheelControl: true,
        observeParents: true,
        onSlideChangeEnd: swiper => {
          this.page = swiper.realIndex + 1
          this.index = swiper.realIndex
          console.log(1)
        }
      }
    }
  },
  components: {
    swiper,
    swiperSlide
  }
}
</script>
<style>
* {
  margin: 0;
  padding: 0;
}

.swiper-wrapper {
  margin-top: 10px;
  height: 230px;
}

.swiper-wrapper img {
  width: 100%;
  height: 100%;
}
</style>`

**Comment by surmon-china** [comment]
最新版组件是基于 Swiper4 的，要使用 4.0 的 API。

**Comment by goldencolor** [comment]
@surmon-china 使用 slideChangeTransitionEnd 也无法收到回掉啊

**Comment by surmon-china** [comment]
@goldencolor https://github.com/surmon-china/vue-awesome-swiper/issues/251#issuecomment-358208866
