### ISSUE TITLE
请问作者，怎么动态设置显示初始那张图片，比如说我要像今日头条九张缩略图，点击第3张，那么初始显示就是第3张，点击第4张，初始显示就是第4张，

### ISSUE THREAD

**Issue by LannyCodes** [surmon-china/vue-awesome-swiper#258]
请问作者，怎么动态设置显示初始那张图片，比如说我要像今日头条九张缩略图，点击第3张，那么初始显示就是第3张，点击第4张，初始显示就是第4张，

**Comment by surmon-china** [comment]
不理解，截个图吧

**Comment by LannyCodes** [comment]
你好，15012480609，是我的微信号，你现在加我微信吧，我当面微信问你这个问题，很急，请帮忙，谢谢！

**Comment by surmon-china** [comment]
@LannyCodes 加群里吧，288325802，微信不方便

**Comment by LannyCodes** [comment]
@surmon-china 加了，现在没人通过，我的意思是，用vue-awesome-swiper这个轮播组件，initialSlide 这个属性能不能动态设置，我要做的效果就是类似于朋友圈里边有9张缩略图，我点击查看大图时，点击第3张，那轮播图initialSlide为3，,从第3张开始，点击第5张时，initialSlide就为5，从第5张开始轮播，求解答，，，

**Comment by surmon-china** [comment]
Swiper 是一定不支持动态参数的，所以你只能控制组件的初始化或在点击缩略图后，执行 slideTo 方法，让swiper 跳到你要的那个 item。
