### ISSUE TITLE
@someSwiperEvent does not work

### ISSUE THREAD

**Issue by yizhixiaotaozi** [surmon-china/vue-awesome-swiper#259]
`data() {
    return {
      swiperOption: {
        touchAngle: 20,
        on: {
          touchEnd() {
            alert('b')
          }
        }
      },
      tabIndex: 2
    }
  }`
This works.

`<swiper :options="swiperOption" style="height: 100%;box-sizing: border-box;" @touchEnd="touchEnd">`
`methods: {
    touchEnd() {
      alert('a')
      //console.log(this.activeIndex);
      //this.tabIndex = this.activeIndex;
    }`
This method never runs.

Did I miss any configuration?

**Comment by surmon-china** [comment]
browser or string template webpack ?

**Comment by yizhixiaotaozi** [comment]
bindEvents() {
        const vm = this
        DEFAULT_EVENTS.forEach(eventName => {
          this.swiper.on(eventName, function() {
            vm.$emit(eventName, ...arguments)
            vm.$emit(eventName.replace(/([A-Z])/g, '-$1').toLowerCase(), ...arguments)
          })
        })
      }

I did not see these code inthe latest src code.

**Comment by yizhixiaotaozi** [comment]
fiexd by re npm install again
