### ISSUE TITLE
slide内容复杂点就直接崩了

### ISSUE THREAD

**Issue by callmesoul** [surmon-china/vue-awesome-swiper#26]
slide里面的内容坚单点的
`<div class="title">< 开博啦！开博啦！踏上大神的第一步 ></div>`
没问题
但是
`<div class="acticle-item">
                            <div class="image">
                                <img src="src/assets/images/article.jpg">
                            </div>
                            <div class="content">
                                <div class="title">< 开博啦！开博啦！踏上大神的第一步 ></div>
                                <div class="drscsdsd">
                                    搭建用于记录博主的点点滴滴，无论是生活上的还是技术上的。博客刚建好，还不完善请见谅。后面会慢慢完善跟扩展。敬请期待。
                                </div>
                            </div>
                        </div>`
复杂点就崩了，不知道什么问题

**Comment by surmon-china** [comment]
请把问题描述清楚

**Comment by callmesoul** [comment]
@surmon-china 就是第一段代码的话就正常运行，下面那段代码就崩了。好像slide里面分内容复杂点就会用不了，浏览器报
`Failed to load resource: net::ERR_FAILED`
试了很多次，一点点内容加上去，少是可以正常运行的，但多了就崩了

**Comment by callmesoul** [comment]
具体我也不知道哪里出了问题，你可以试试下把每个slide弄复杂点。
例如：
`<swiper-slide>
                        <div class="acticle-item">
                            <div class="image">
                                <img src="src/assets/images/article.jpg">
                            </div>
                            <div class="content">
                                <div class="title">< 开博啦！开博啦！踏上大神的第一步 ></div>

                            </div>
                        </div>
                    </swiper-slide>`

**Comment by surmon-china** [comment]
把"< 开博啦！开博啦！踏上大神的第一步 >"里面的非工作标签，如："<"，全部换成转义符。
