### ISSUE TITLE
Virtual Slides

### ISSUE THREAD

**Issue by bourhaouta** [surmon-china/vue-awesome-swiper#260]
#### What is Expected?
I'm doing this, a simple loop in an Object:
```pug
swiper(v-if="base.status", :options="views.options", ref="views", @slideChange="swipe", @slideNextTransitionEnd="next", @slidePrevTransitionEnd="prev")
  swiper-slide(v-for="(item, index) in base.data", :key="item.id", infinite-wrapper)
    h1 {{ item.title }}
```
And then I set `virtual: true`:
```javascript
options: {
  autoHeight: true,
  loop: true,
  initialSlide: 1,
  virtual: true,
}
```
So I expected that it'll show only the first 3 DOM and then it change the slides while swiping as it look in the demo

#### What is actually happening?
But, I think I did something wrong cuz it doesn't work like I expected and it didn't allow me to swipe at all, and it shows in the DOM that whole Object data not only 3.

Is this the wrong way to do it ?

**Comment by LiHwsqh** [comment]
@surmon-china Same question, what should we do to make the 'virtual' work?

**Comment by bourhaouta** [comment]
> +1 , is the wrong spelling of 'Virtaul' causes the ignoring of this issue ?

I don't really know, and I just fixed the spelling, thank you!
