### ISSUE TITLE
loop:true extra slide doesnt use router-link

### ISSUE THREAD

**Issue by smakinson** [surmon-china/vue-awesome-swiper#261]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Vue.js version and component version
quasar 0.14.7

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### Steps to reproduce
* Create a slider with loop:true in the settings.
* I am using a custom component for the slide content and it has a router-link that gets clicked. 
* As I click navigate to the right and it comes back around to the first slide again, that slide is not selectable as a component in the vue dev tools and if I click the router-link, it reloads the whole page rather than using the router.

#### What is Expected?      
The component in the slide to be cloned as the component and router-link to behave normally.

#### What is actually happening?
It seems it may only be cloning it as dom elements?

**Comment by drNenad** [comment]
I have the exact problem, please let me know if you find a solution.

**Comment by surmon-china** [comment]
#21 
#253

**Comment by surmon-china** [comment]
This issue has been answered, please check the links provided above.

1. bind event with `<swiper>`

```html
<swiper @click.native="doSomething(this.swiper.activeIndex)">
```

2. disabled the `loop:true`

**Comment by surmon-china** [comment]
First, upgrade to v4.x

1. `<router-link>` should be work fine
2. If it doesn't work, use the new event API [`@click-slide`](https://github.com/surmon-china/vue-awesome-swiper#swiper-component-api) please

```html
<swiper @click-slide="handleClickSlide"/>
```

:)
