### ISSUE TITLE
vue-awesome-swiper@3.1.2 将swiper由4.0.7替换成4.1.0版本，ie9不生效

### ISSUE THREAD

**Issue by aiyov** [surmon-china/vue-awesome-swiper#262]
配置：
 swiperOption: {
    slidesPerView: 5,
    spaceBetween: '5%',
    slidesPerGroup: 5,
    loop: true,
    loopFillGroupWithBlank: true,
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
  },

html：

`  <swiper :options="swiperOption">
      <swiper-slide class="Surfaces" key="index" v-for="(item,index) in allWebKinInfo">
        <div class="allSurface l"> </div>
      </swiper-slide>
    </swiper>
    <div class="swiper-button-prev" slot="button-prev"></div>
    <div class="swiper-button-next" slot="button-next"></div>`

问题：在ie9上面组件不生效，无报错，点击翻页无响应，ie10及以上正常

**Comment by surmon-china** [comment]
具体问题 具体分析，你可以观察控制台的错误，或审查对应翻页元素的 element，z-index 等属性都是否符合预期，一步步排除；一个问题如果只能表面地表现出来，那也是没办法本质地找到原因的。
