### ISSUE TITLE
Window undefined with Nuxt 1.0.0 

### ISSUE THREAD

**Issue by rizkiheryandi** [surmon-china/vue-awesome-swiper#263]
Version

Nuxt : 1.0.0
Vue : 2.5.13
Swiper : 3.1.2

Steps to reproduce

- Use vue-awesome-swiper with nuxt SSR installation from repository

What is Expected?

- Running in Nuxt       

What is actually happening?

- Window is not defined

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-awesome-swiper#mount-with-ssr

```javascript
// If used in nuxt.js/ssr, you should keep it only in browser build environment
if (process.browser) {
  const VueAwesomeSwiper = require('vue-awesome-swiper/dist/ssr')
  Vue.use(VueAwesomeSwiper)
}
```

**Comment by bovas85** [comment]
It's actually const VueAwesomeSwiper = require('vue-awesome-swiper/ssr') now as per docs

**Comment by surmon-china** [comment]
@bovas85 The docs has been updated after v3.0.0.

**Comment by bovas85** [comment]
Ah yes, I noticed now. This was recent right? @surmon-china 
Thanks.

**Comment by bovas85** [comment]
english please

**Comment by zhaoxiaoer888** [comment]
@haryzxw 你的window is not defined 解决了么？我也刚遇到这个问题

**Comment by haryzxw** [comment]
@zhaoxiaoer888  嗯 解决了 当时也是参考了别人的解决方法 写法变了一下

**Comment by Xavier0818** [comment]
> @zhaoxiaoer888 嗯 解决了 当时也是参考了别人的解决方法 写法变了一下

怎么解决的？

**Comment by mrKorg** [comment]
@paragonHex can you show exapmle. I have the same problem, but I can not solved it

**Comment by surmon-china** [comment]
- Upgrade to v4.x
- Read [SSR document](https://github.com/surmon-china/surmon-china.github.io/tree/source/projects/vue-awesome-swiper/nuxt) please.

**Comment by Dhruvi16** [comment]
I am having the same issue when I use the Vue awesome swiper directive. And I am unable to solve it
