### ISSUE TITLE
You may have an infinite update loop in a component render function.

### ISSUE THREAD

**Issue by spademan** [surmon-china/vue-awesome-swiper#264]
#### Vue.js version and component version
v2.5.13
#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### Steps to reproduce
vue-awesome-swiper@3.1.2 version

[vue warn] in chrome : `You may have an infinite update loop in a component render function.`
![image](https://user-images.githubusercontent.com/6311122/35733572-db27bf34-0858-11e8-8951-411e2a037557.png)
#### What is actually happening?

**Comment by spademan** [comment]
![image](https://user-images.githubusercontent.com/6311122/35733627-1c51ca72-0859-11e8-9fb3-5acce14a591d.png)
这样就会有提示，删除掉swiper就没有提示，说明问题就是出在swiper上

**Comment by surmon-china** [comment]
尽量贴出你的组件所有相关代码。

**Comment by spademan** [comment]
找到问题了，因为我在父级中添加了一个：key
![image](https://user-images.githubusercontent.com/6311122/35735192-c32d38d6-085e-11e8-9c48-c79195f7a163.png)
用了多个组件嵌套，问题比较复杂，不好意思

**Comment by VolodymyrTesliuk** [comment]
@surmon-china May you help with similar issue?

**Comment by giuliano-oliveira** [comment]
@VolodymyrTesliuk I solved by:
1. Isolating my swiper component creating another `.vue` template or
2. Never initializing mySwiper object to null even in the `created()`.
