### ISSUE TITLE
Put Paggination inside a swiper slide

### ISSUE THREAD

**Issue by hyg1997** [surmon-china/vue-awesome-swiper#265]
#### Vue.js version and component version
**Nuxt**: 1.00  
**vue-awesome-swiper**: 3.1.2  

![image](https://user-images.githubusercontent.com/18673500/35749973-5b779b10-0821-11e8-8ad5-6687c7ca9d62.png)

Hi, is there a way/workaround to put the pagination inside a swiper slide

Thanks for your great work

**Comment by surmon-china** [comment]
Custom the pagination css `position`.

**Comment by saintplay** [comment]
right. Anyways there is a way to synchronize the swipers at the same time?

**Comment by surmon-china** [comment]
@saintplay I do not quite understand you.

**Comment by saintplay** [comment]
that looks great! thanks
