### ISSUE TITLE
异步改变数据后，原先数据不被删除？

### ISSUE THREAD

**Issue by yizhixiaotaozi** [surmon-china/vue-awesome-swiper#266]
`<swiper style="height: 140px;" ref="bannerSwiper" :options="bannerOption">`
        `<template v-if="banners.length == 0">`
          `<swiper-slide v-for="n in 3" :key="n" style="width: 100%;height: 100%;">`
            `<img src='loading.jpg'>`
          `</swiper-slide>`
        `</template>`
        `<swiper-slide v-for="(banner, index) in banners" :key="index" style="width: 100%;height: 100%;">`
          `<img style="width: 100%;height: 100%;" :src="banner.src">`
        `</swiper-slide>`
        `<div class="swiper-pagination" slot="pagination"></div>`
    `</swiper>`
mounted(){
    this.$nextTick(function () {
      setTimeout(() => {
        // 模拟ajax
        this.banners = [
        {src:'dd.jpg'},
        {src:'cc.jpg'},
        {src:'bb.jpg'},
        {src:'aa.jpg'}
        ]
      },1000)
    })
  }

vue-awesome-swiper@3.1.2
查看html，发现loading.jpg，那几个div还在，关键是自动切换到最后一张的时候不正常

**Comment by yizhixiaotaozi** [comment]
是否应该在swiper-slide的destoryed的钩子里，再调用一次swiper.update()方法？

**Comment by yizhixiaotaozi** [comment]
还发现个问题，一开始一个swiper-slide都不给的情况下，会报错，
var activeSlide;
  if (isVirtual) {
    activeSlide = swiper.$wrapperEl.find(("." + (params.slideClass) + "[data-swiper-slide-index=\"" + activeIndex + "\"]"));
  } else {
    activeSlide = slides.eq(activeIndex);
  }

  // Active classes
  activeSlide.addClass(params.slideActiveClass);
这里activeSlide取不到就报错了

**Comment by surmon-china** [comment]
这是你的 Js 基本错误，`activeSlide.addClass(params.slideActiveClass);`，下次贴出前把你代码格式化一下，如果不会就看这里 https://guides.github.com/features/mastering-markdown/

**Comment by yizhixiaotaozi** [comment]
// Active classes
activeSlide.addClass(params.slideActiveClass);
这里activeSlide取不到就报错了

这是你的源码啊，不是我的，在swiper.vue里 (┬＿┬)

**Comment by surmon-china** [comment]
并没有啊，什么地方

**Comment by leobaixinxin** [comment]
这个问题解决了吗

**Comment by clevergod** [comment]
同样的问题 ssr 首屏没问题 异步更改数据后 autoplay时在最后一张切换到第一张的时候 会出现老数据里的图片

**Comment by rmlzy** [comment]
同问, 解决了吗

**Comment by jwnoal** [comment]
同问，怎么解决这个问题，我是异步更改数据后   往左滑到新加的图会有问题，往右滑都是正常的

**Comment by iHaPBoy** [comment]
给 `<swiper>` 加上 `v-if="banners.length > 0"`，使得数据变更时触发重新渲染整个 Swiper。

参考： #322

**Comment by surmon-china** [comment]
v4.x 解决了更新相关的问题，请升级！
