### ISSUE TITLE
how to call slider by instanceName?

### ISSUE THREAD

**Issue by cannap** [surmon-china/vue-awesome-swiper#269]
Hi, i know its not an issue but i have no idea how i call the Slider by instance 
i use swiper ssr via directive and have multiple sliders they all work but i just dont know how to use them by instanceName :D
```html
 <section v-for="slider in sliders"
             class="single-work"
             :key="slider.id">
      <div :instanceName="slider.instance"
           v-swiper="swiperOptions">

        <div class="swiper-wrapper">
          <div class="swiper-slide"
               v-for="image in slider.images"
               :key="image.thumbnail">
            <img :src="image.thumbnail">
          </div>
        </div>
      </div>
    </section>
```

thanks for help

**Comment by cannap** [comment]
i found it just
```js
this.instanceName 
```

**Comment by baztypetrucci** [comment]
Hi @cannap How did you make multiple instances? I'm using SSR via Nuxt with swiper in component mode.
In the vue file importing the same component:

import carouselA from "~/components/carouselA.vue"; import carouselB from "~/components/carouselA.vue"; export default { components: { SliderchicasA, SliderchicasB } };

The component file:

<div v-swiper:mySwipper="swiperOption"> <div class="swiper-wrapper"> <div class="swiper-slide" ...

I've tried many ways, but with no result, thanks for reading.

**Comment by baztypetrucci** [comment]
@cannap 

So the component need to be called like this:
`<component :instanceName="swiperA" />`
