### ISSUE TITLE
loop为true第一个slide被跳过，如何解决

### ISSUE THREAD

**Issue by diveDylan** [surmon-china/vue-awesome-swiper#270]
``
swiperOption:{
              observer: true, 
              observeParents: true,
              loop:true,
              pagination: {
                el: '.swiper-pagination',
              },
              autoplay: {
                delay: 2500,
                disableOnInteraction: false
              },
              initialSlide:0,
             
 },
``
数据是异步获取
输出this.$refs.mySwiper 和this.$refs.mySwiper.swiper两个对象的属性和方法，试了一下，都不太行，

**Comment by surmon-china** [comment]
数据变动时，靠 `v-if` 控制组件的渲染状态。

**Comment by bubiu** [comment]
我之前也有这个问题，今天发现是我import 进去的swiper 版本的问题 换成官网最新的 4.1.6版本就好了

**Comment by Limuyang1013** [comment]
通过v-if判断是否拿到渲染列表用的数据,在拿到数据的时候在渲染swiper组件，亲测有效，我之前也是从最后一个直接跳到第二个

**Comment by leobaixinxin** [comment]
这个有一个问题，如果是渲染列表的 数据源 是动态改变的，比如随着筛选条件，列表的数据源会改变，这个时候重新渲染的列表，在点击的循环的时候会有问题。

**Comment by leobaixinxin** [comment]
而且加上v-if后，this.$refs.mySwiper  在computed 计算属性时，取不到值

**Comment by surmon-china** [comment]
@leobaixinxin 配合数据变动时的节点 + `$nextTick` 获取组件对象。

**Comment by weiving** [comment]
数据加载后才渲染swiper，我配置 direction: 'vertical'，可以垂直滚动的同时，为什么还会加载水平的滚动

**Comment by weiving** [comment]
slidesPerView: 2

**Comment by luxuebo** [comment]
<template>
<div>
	<swiper :options="swiperOption"
	v-if='ok'>
		<swiper-slide><img :src="data[0]" alt=""></swiper-slide>
		<swiper-slide><img :src="data[1]" alt=""></swiper-slide>
		<swiper-slide><img :src="data[2]" alt=""></swiper-slide>
		<swiper-slide><img :src="data[3]" alt=""></swiper-slide>
		<div class="swiper-pagination" slot="pagination"></div>
	</swiper>
</div>
</template>
<script >
export default{
	data() {
      return {
      	data:[],
      	ok:false,
        swiperOption:{
	        autoplay:{
				delay: 2000,
				stopOnLastSlide: false,
				disableOnInteraction: false,
	        },
	        loop : true,
	        pagination: {
	          el: '.swiper-pagination'
	        }
      	}
        
      }
    },
	components:{
		Navlist
	},
	mounted(){
		this.$axios.get("http://www.wwtliu.com/sxtstu/blueberrypai/getChengpinDetails.php")
		.then(res=>{
			return res.data
		})
		.then(data=>{
			if(!data){return}
			this.ok=true
			this.data=data.chengpinDetails[0].img
			console.log(data.chengpinDetails[0].img)

		})
		.catch(error=>{
			console.log(error)
		})
	}
}
</script>

**Comment by luxuebo** [comment]
<swiper :options="swiperOption"
	v-if='isok'>
		<swiper-slide><img :src="data[0]" alt=""></swiper-slide>
		<swiper-slide><img :src="data[1]" alt=""></swiper-slide>
		<swiper-slide><img :src="data[2]" alt=""></swiper-slide>
		<swiper-slide><img :src="data[3]" alt=""></swiper-slide>
		<div class="swiper-pagination" slot="pagination"></div>
</swiper>
isok默认为false,当数据加载后修改为true
