### ISSUE TITLE
Can't detect onReachEnd or isEnd

### ISSUE THREAD

**Issue by danstans** [surmon-china/vue-awesome-swiper#273]
#### Code
https://gist.github.com/danstans/87d42cd8f4eaee61bd676f5426eafbc3

#### What is Expected?      
I need a method that will detect when the last slide is being viewed. This will allow me to change the nextEl to a close button. I expect to be seeing 'This is the last slide' from line 50.

#### What is actually happening?
No log at all. Tried other methods with custom plugins, no luck yet.

**Comment by surmon-china** [comment]
http://idangero.us/swiper/api/#events

Swiper 4.0 api.

```javascript
var swiper = new Swiper('.swiper-container', {
  // other parameters
  on: {
    reachEnd: function () {
      /* do something */
    },
  }
});
```
