### ISSUE TITLE
pagination 的 paginationBulletRender无效

### ISSUE THREAD

**Issue by q154494562** [surmon-china/vue-awesome-swiper#278]
首先要说抱歉，我英语不好，正在学习中，请谅解一下我不能用英文描述发现的问题。
我按照swiper官方文档例子想创建如下pagination，但是paginationBulletRender选项却不起作用，我尝试按照swiper4的语法书写但还是不起作用。请问怎么解决？
var swiper = new Swiper('.swiper-container', {
  pagination: '.swiper-pagination',
  paginationClickable: true,
  paginationBulletRender: function (swiper, index, className) {
      return '<span class="' + className + '">' + (index + 1) + '</span>';
  }
});

**Comment by surmon-china** [comment]
英文不好没关系，但代码总得高亮规范地贴出来吧，markdown 语法总是可以学习的吧。
你留下的代码是 Swiper3 的，Swiper4 里的 API 是 `renderBullet`，API 不是 “语法”。
