### ISSUE TITLE
vue ssr服务端渲染问题

### ISSUE THREAD

**Issue by Likunone** [surmon-china/vue-awesome-swiper#279]
![image](https://user-images.githubusercontent.com/15193414/36720202-4a1fd52e-1be2-11e8-86bf-893875db385c.png)

拖动轮播图的时候会报错@3.1.2

没用使用nuxt.js

**Comment by JaremyCheng** [comment]
@Likunone 请问下你是怎么在vue ssr的项目内进行引入文件的?

**Comment by Lygitan** [comment]
@Likunone 我使用nuxt做ssr的时候也碰到这问题，请问你解决了吗？
