### ISSUE TITLE
点击 bug & 初始化bug

### ISSUE THREAD

**Issue by xiongxliu** [surmon-china/vue-awesome-swiper#28]
1:给item设置click事件，click事件执行逻辑后跳转页面。dom刚渲染后，点击item没有执行click事件，拖动item,之后有时可以点击，有时候还是不能。
2:我加入了俩个item,页面初始化后，首先显示的页面是第二个。

**Comment by surmon-china** [comment]
建议贴出详细代码

**Comment by xiongxliu** [comment]
![image](https://cloud.githubusercontent.com/assets/17661296/21755931/6418c50e-d655-11e6-8ce9-5ebd68da9c90.png)

1. 第一次打开，怎么点banner，都不执行点击事件，滑动一下才能触发点击事件。
2. 每次进去都是显示的最后一个banner，不是第一个。
3. 中间的banner更容易被点击。

**Comment by surmon-china** [comment]
1：关掉Loop，因为loop使用的是复制dom节点的方式来实现循环切换，而实际上元素内的事件不会被复制，所以首尾元素（复制出的临时节点）事件会失效
2：将click等各类事件以native修饰符绑定在<swiper-slide>元素上，如<swiper-slide @click.native="dosomething">

**Comment by surmon-china** [comment]
#21 
参考同样的问题

**Comment by xiongxliu** [comment]
谢谢
