### ISSUE TITLE
3D Coverflow Effect （ 3D滚动切换 ） 不支持loop吗？

### ISSUE THREAD

**Issue by JoyCoco** [surmon-china/vue-awesome-swiper#284]
https://github.com/surmon-china/vue-awesome-swiper/blob/master/examples/24-effect-coverflow.vue
在demo中加入**loop:true**，会报错：Error in mounted hook: "TypeError: Cannot read property 'classList' of undefined"

**Comment by surmon-china** [comment]
建议贴出代码。

**Comment by surmon-china** [comment]
不用了，这个问题，无法解决，Swiper loop 的锅。

**Comment by fdebruyne** [comment]
## ###阿斯顿撒美少女三年内，is都没拿的您

**Comment by youdianfan** [comment]
这个问题能解决吗?

**Comment by surmon-china** [comment]
loop 引起的问题只能等官方解决
