### ISSUE TITLE
ssr的时候, 读window变量会出错

### ISSUE THREAD

**Issue by ferrisBreeze** [surmon-china/vue-awesome-swiper#288]
https://github.com/surmon-china/vue-awesome-swiper/blob/df5fbd0b8e7f31bb4fc4cee365199bdc35ed682c/dist/ssr.js#L18

` var Swiper = _swiper2.default; 
`
直接这样会有什么问题吗

**Comment by surmon-china** [comment]
SSR 文件必须判断运行环境使用 `require` 引入。

1. 会有问题，因为用户的 Swiper 可能是别的方式加载注入的，比如 CDN
2. Swiper 本身就是依赖 window 的！！
