### ISSUE TITLE
vue-awesome-swiper是否可以实现我demo的这种效果

### ISSUE THREAD

**Issue by Jesonhu** [surmon-china/vue-awesome-swiper#289]
### vue-awesome-swiper 是否可以实现这种效果：
描述: Swiper官方有个效果，我想在vue spa单页面中实现这种效果。
我疑问的地方：
```
navSwiper.on('tap', function (e) {
        clickIndex = this.clickedIndex
        clickSlide = this.slides.eq(clickIndex)
        pageSwiper.slideTo(clickIndex, 0);
        this.slides.find('span').css('color', 'rgba(51,51,51,1)');
        clickSlide.find('span').css('color', 'rgba(255,72,145,1)');
 });
```
这里的navSwiper是new Swiper()实例化后的对象，而在单页面中如何获取Swiper实例化后的对象呢?
swiper使用了DOM7，vue-awesome-swiper中是否也可以直接使用

#### Vue.js version and component version
+ "vue": "^2.5.2",
+ "vue-awesome-swiper": "^3.1.3"

#### Reproduction Link
+ [copen展示地址](https://codepen.io/Jesonhu/pen/QQeVQJ)

#### What is actually happening?

**Comment by surmon-china** [comment]
获取实例的方法，README.md 中都有详细的描述：
https://github.com/surmon-china/vue-awesome-swiper#spa

Swiper4 中，监听事件的 API 可以有多种形式，也可以直接配置在 options 中。

DOM7 是已被 npm 安装的，可以引入使用，但因为其旧版本的模块问题，在 webpack 构建时可能会异常，需要特殊处理。

https://github.com/surmon-china/surmon.me/blob/master/nuxt.config.js#L23

**Comment by Jesonhu** [comment]
好的，谢谢。我试试

**Comment by Jesonhu** [comment]
@surmon-china  初始化每个swiper-slide宽度计算错误，点击的时候恢复正常
### Error show
![errow_show](https://user-images.githubusercontent.com/18684575/37442378-f7149976-2840-11e8-9ef1-83a0d045cef1.gif)
### Code show
```
<template>
<div class="m-nav-scrollX nav-scroll-wrap">
      <!-- nav swiper  -->
      <swiper :options="navSwiperOption" ref="navSwiper">
        <swiper-slide
        v-for="(item, index) in floorNavData.list"
        :key="index"
        :class="{'is-active': floorNavData.activeIndex === index}"
        @click.native="onFloorNav(index)">{{item}}</swiper-slide>
      </swiper>
      <!-- End -->
    </div>
</template>

<script>
data() {
    return {
      floorNavData: {
        list: ['全部', 'B1', '1F', '2F', '3F', '4F', '5F', '6F'],
        activeIndex: 0
      },
      navSwiperOption: {
        slidesPerView: 8,
        freeMode: true,
        slideToClickedSlide: true,
        tabIndex: 0
      }
    }
  },
</script>
```

**Comment by ferrinweb** [comment]
#290 看下是不是这个原因

**Comment by Jesonhu** [comment]
因为是依据微信开发的h5页面，用微信打开页面显示是正常的.o(╯□╰)o

**Comment by surmon-china** [comment]
@Jesonhu 数据完成后 nextTick  里为 Swiper 实例执行一次 update 或许是可以的。

**Comment by mhxy13867806343** [comment]
我是菜鸟，来学习下
