### ISSUE TITLE
在Readme.md增加“须先于模块引入css文件”说明的建议

### ISSUE THREAD

**Issue by ferrinweb** [surmon-china/vue-awesome-swiper#290]
我先前自认为可以将css引入至style块儿内，结果分页器出不来，幻灯片样式也有大大小小的问题，后来仔细看了Readme文件，试了试通过import将css引入到swiper模块前，解决了所有问题。

所以我觉得应该增加一个强调，务必将css在模块之前进行引入。

**Comment by surmon-china** [comment]
我觉得大部分是会读一下 README.md 的，抱歉，不能采纳。
