### ISSUE TITLE
自动轮播，播放完最后一个，再播放第一个时有严重闪烁

### ISSUE THREAD

**Issue by tomorrowface** [surmon-china/vue-awesome-swiper#298]
自动轮播，播放完最后一个，再播放第一个时有严重闪烁
如果不启用自动播放，到最后一页时，再点下一页是切换不到第一页的

**Comment by cangyu1993** [comment]
我在ios也遇到这个问题了

**Comment by Akenokoru** [comment]
> 自动轮播，播放完最后一个，再播放第一个时有严重闪烁
> 如果不启用自动播放，到最后一页时，再点下一页是切换不到第一页的

请问这个是怎么解决的？我也遇到这个问题了
