### ISSUE TITLE
loop 模式下报错问题

### ISSUE THREAD

**Issue by tudousi991112** [surmon-china/vue-awesome-swiper#30]
![image](https://cloud.githubusercontent.com/assets/15308650/21759693/3f380372-d681-11e6-833a-4a83deb8d779.png)
版本已经是
![image](https://cloud.githubusercontent.com/assets/15308650/21759700/4b17a206-d681-11e6-84fc-8b397e0511bf.png)

**Comment by surmon-china** [comment]
show your code, context, detail

**Comment by tudousi991112** [comment]
![image](https://cloud.githubusercontent.com/assets/15308650/21795730/0fae14fc-d73f-11e6-929f-f09d9a0e3658.png)

**Comment by tudousi991112** [comment]
sorry，找到原因了
![image](https://cloud.githubusercontent.com/assets/15308650/21834574/1cefaf92-d7f1-11e6-9dc7-6f1d3e605f6f.png)
