### ISSUE TITLE
Can you upgrade swiper version above 4.1.5 so that I can use the slideToLoop method?

### ISSUE THREAD

**Issue by DualWield** [surmon-china/vue-awesome-swiper#301]
#### Vue.js version and component version
vue@2.5.13
swiper@4.1.0
vue-awesome-swiper@3.1.2

#### Reproduction Link
none
#### Steps to reproduce
none
#### What is Expected?      
我做点击pagination的时候，slideTo对应的，但是我的swiper是循环的（loop：true），所以要用slideToLoop，但是slideToLoop在4.1.5中才能使用，能升级下swiper的版本吗？
http://www.swiper.com.cn/api/methods/417.html
#### What is actually happening?
none

**Comment by surmon-china** [comment]
在 npm 的包依赖管理中，`^` 代表自动安装依赖的副版本号的最新版，也就是说会自动安装 `4.x.x` 的最新版，所以，你只需要删掉 node_module 中安装的对应文件，重新安装就可以了。
