### ISSUE TITLE
Multiple swipers whose data was loaded async, from example "24-effect-coverflow.vue"

### ISSUE THREAD

**Issue by Robin-zero** [surmon-china/vue-awesome-swiper#305]
#### Vue.js version and component version
- "vue": "^2.5.16"
- "vue-awesome-swiper": "^3.1.3"

#### Reproduction Link
- I didn't reproduce this problem in jsFiddle, but it did happen in my project

#### Steps to reproduce
- There were two swiper, they were coded like "24-effect-coverflow.vue"
- The date of them were empty array first and  loaded with the component async

#### What is Expected?      
The page showed should be like the example

#### What is actually happening?
Both the two swipers had bad style and couldn't be controlled correctly.
![image](https://user-images.githubusercontent.com/22169252/38226928-720f71b8-372e-11e8-8e7b-d14096e0e335.png)

**PS: Please don't mind the poor English, thanks!**

**Comment by surmon-china** [comment]
But I cannot reproduce it. Or please post your code!
