### ISSUE TITLE
通过请求获取轮播数据,报错classList of undefinde

### ISSUE THREAD

**Issue by youdianfan** [surmon-china/vue-awesome-swiper#306]
代码配置了循环,这个能解决吗?
![cuowuwuwuw](https://user-images.githubusercontent.com/27018910/38251888-41967836-3785-11e8-803f-ad7d7ffb28ce.png)

**Comment by youdianfan** [comment]
描述可能不对,不知能否理解?

**Comment by youdianfan** [comment]
谢谢

**Comment by weiving** [comment]
你在配置swiper的html循环时，classList没有获取定义

**Comment by youdianfan** [comment]
如何定义classLIst?还望指教

**Comment by weiving** [comment]
这个是你自己定义的变量，你把要轮播的数据都放到这个list里面

**Comment by weiving** [comment]
你在mounted这里面的classList没有定义

**Comment by youdianfan** [comment]
还是一脸懵,有空再看看吧,谢谢你的回答

**Comment by surmon-china** [comment]
如果你用了 loop，那么必须确保 Swiper 组件尽在已经得到数据时渲染！可以尝试用`v-if`做判断

**Comment by hasbug** [comment]
同样的错误 用v-if判断也没效果。
