### ISSUE TITLE
为什么没有swiper对象

### ISSUE THREAD

**Issue by liangxiaojuan** [surmon-china/vue-awesome-swiper#31]
![qq 20170109165434](https://cloud.githubusercontent.com/assets/11735533/21761207/53afc672-d68c-11e6-8517-cf4aea819e39.png)

console.log(this.$refs.mySwiperA); 在浏览器能看到有 对象，但是
onsole.log(this.$refs.mySwiperA.swiper); 就是一个 undefined

**Comment by surmon-china** [comment]
代码截全图，标点符号问题编辑描述清晰，尽量英文。
