### ISSUE TITLE
Swiper collapses on route change

### ISSUE THREAD

**Issue by nataliawww** [surmon-china/vue-awesome-swiper#317]
Using swiper version 3.1.3 with vue & nuxt

When rendering a new route, you can see the swiper collapse, I guess because it's being destroyed on `beforeDestroy`?

Here's a video showing the issue
https://streamable.com/mthnx

**Comment by aligajani** [comment]
Interesting

**Comment by bgondy** [comment]
I have a similar issue with `<transition>` component in a parent component. Using `destroy` instead of `beforeDestroy` seems to do the trick.

Is there any reason behind using `beforeDestroy` over `destroy`?

**Comment by hoektoe** [comment]
Is this the same issue as above? How to resolve this?
Check the bottom image which is also in slider become as big as whole container

https://streamable.com/fp3fa

**Comment by rubenmeines** [comment]
I am having the same issue. Before my page transition the swiper resets and goes back to the start.

I am using nuxtjs.

**Comment by rubenmeines** [comment]
@nataliawojtkowska 
I think you can fix that issue by not using the "spaceBetween" option but use margins in your css. If not you can also try the option below which will not destroy your slider and keep the settings.

@hoektoe @bgondy 
I fixed it by using the mySwiper.destroy(deleteInstance, cleanStyles); and setting the "deleteInstance" and "cleanStyles" to **false** on mount and then initialising it again.

HTML:
<img width="291" alt="screen shot 2018-06-24 at 19 46 51" src="https://user-images.githubusercontent.com/10308155/41821885-842c6a32-77e7-11e8-9255-065a0d523bec.png">

JS:
<img width="312" alt="screen shot 2018-06-24 at 19 45 45" src="https://user-images.githubusercontent.com/10308155/41821879-5a1958ae-77e7-11e8-87c9-f78af13919d4.png">

Check also http://idangero.us/swiper/api/
and search for: _mySwiper.destroy(deleteInstance, cleanStyles);_

**Comment by rubenmeines** [comment]
If you want to keep your slide on the same position as when you left you can check out:
**mySwiper.progress** and **mySwiper.update();**

You could use mySwiper.progress to save the progress in your **store** before you leave the page and then when you come back on the page where your swiper is you can use mySwiper.updateProgress() to update the position in the **mounted()** function

**Comment by bitpunk** [comment]
I have the same issue and tried to fix it with the destory/init solution mentioned before.
I seems to work but the navigation stops working. The navigation classes in the props are just fine.

**Comment by guins** [comment]
I created a [pull request](https://github.com/surmon-china/vue-awesome-swiper/pull/388) to fix this issue. Let me know if it works for you !

**Comment by hjujah** [comment]
Having the same issue on nuxtjs... Any updates on this? 
Btw, I solved it by adjusting the swiper.js file, but still looking for a batter / more proof solution...

**Comment by lockieRichter** [comment]
@guins I've implemented your fix and it works for me, the pull request has failed checks because the CI job failed.

**Comment by nonlinearcom** [comment]
I had the same problem using page transitions on nuxt. 
My temporary fix was commenting `swiper.destroy && swiper.destroy();` on dist/ssr.js

**Comment by or2e** [comment]
`swiper-container{
opacity: 0
}`

` mounted() {
    this.$nextTick(() => {
      this.swiper.el.style.opacity = 1
    })
}`

**Comment by fire-crow** [comment]
I had the same problem when using SPA.  

i used this:  vue-awesome-swiper

i tried add an event like this: 

option： {
    on: {
         beforeDestroy: function(){
              this.params.scrollbar.el = "";
          }
    }
}
Problem may be solved, but I don't know if there are any other bugs.

**Comment by leopoldkristjansson** [comment]
> 
> 
> Is this the same issue as above? How to resolve this?
> Check the bottom image which is also in slider become as big as whole container
> 
> https://streamable.com/fp3fa
> 
> @bgondy could you elaborate what you did to resolve this issue? or is it something which needs to be fixed within the swiper codebase?

Having the same issue as this, using Nuxt.

**Comment by kyalha** [comment]
@leopoldkristjansson  I have the same issue and the PR has not been merged so in the meantime, you can use my colleague' s dirty solution by adding to the Swiper option to overwritte the destroy function: 
`init: (function() {
		  // @ts-ignore
		  const prev = this.destroy
		  if (prev != null) {
			  this.destroy = function() {
				  prev.apply(this, [true, false])
			  }
		  }
	  })`

**Comment by travbus** [comment]
I find keep alive works good for keeping presentation  between changes routes. If you populate slides when the component is created. However if you populate when the component is activated. So updated everytime you go back to that route.. issues happen like first slide is visible but the rest of the slides are not but are still in the dom.

**Comment by arcs-** [comment]
I am still facing this issue...

**Comment by abeleev** [comment]
Solution for me 

`swiper.fixedDestroy = swiper.destroy
swiper.destroy = () => swiper.fixedDestroy(true, false)`

**Comment by sebastianjung** [comment]
This seems to work for me as it overrides the default destroy function:

`swiper.destroy = () => {}`
or 
this.swiper.destroy = () => {}
`depending on your implementation`

**Comment by leopoldkristjansson** [comment]
Using the solution from @sebastianjung works for me:

```
  mounted() {
    this.mySwiper.destroy = () => {};
  }

```
`<div v-swiper:mySwiper="swiperOptions">...</div>`

**Comment by surmon-china** [comment]
Silence v4.x, you can [control the destory params by props](https://github.com/surmon-china/vue-awesome-swiper#swiper-component-api).

```html
<swiper
  :options="swiperOptionsObject"
  :auto-update="true"
  :auto-destroy="true"
  :delete-instance-on-destroy="true"
  :cleanup-styles-on-destroy="true"
  @ready="handleSwiperReadied"
  @click-slide="handleClickSlide"
/>
```

Upgrade to v4.x please!

**Comment by i-am-chuck** [comment]
I used @abeleev fix and it work great AND preserve the slideChange method
