### ISSUE TITLE
导入vue-swiper的时候 报错

### ISSUE THREAD

**Issue by CharzleZhang** [surmon-china/vue-awesome-swiper#32]
导入vue-swiper的时候 报错
window is not defined 
at /Users/apple/Desktop/swiper/dist/js/swiper.js:4480:22

**Comment by surmon-china** [comment]
node版本是？

**Comment by wszwj** [comment]
我也有这错误，node版本是6.2.0

**Comment by surmon-china** [comment]
升级node，最少7.0以上

**Comment by wszwj** [comment]
升级了
![image](https://cloud.githubusercontent.com/assets/12368485/21876025/eec80cd4-d8ba-11e6-95e8-519369d40c7f.png)

**Comment by wszwj** [comment]
![image](https://cloud.githubusercontent.com/assets/12368485/21876116/5577124a-d8bb-11e6-8dfe-4de09049aa95.png)
升级到7.4.0引入还是这报错
![image](https://cloud.githubusercontent.com/assets/12368485/21876154/904b712c-d8bb-11e6-859c-0a910fec2a3f.png)

**Comment by surmon-china** [comment]
稍等，我测试下

**Comment by surmon-china** [comment]
同学你可以测试下，全局模式use，是否会出现同样问题

**Comment by wszwj** [comment]
还是报一样的错误。。。

**Comment by surmon-china** [comment]
在测试

**Comment by surmon-china** [comment]
请升级到2.3.0，再次测试
@wszwj 
@CharzleZhang 
https://github.com/surmon-china/vue-awesome-swiper/tree/v2.3.0
