### ISSUE TITLE
{ loop: true }  swiper-slide goes  wrong when data is from v-for

### ISSUE THREAD

**Issue by lonlii4ap** [surmon-china/vue-awesome-swiper#322]
```
 config is like this:  
 swiperOption: {
              loop: true
}
vue content,if this,is ok:
"<swiper-slide>Slide 2</swiper-slide>
<swiper-slide>Slide 2</swiper-slide>
<swiper-slide>Slide 3</swiper-slide>"
go wrong is this:
"<swiper-slide v-if="v in dataList">{{v.name}}</swiper-slide>"

you can try 

English is not very well,thanks 英文不好，见谅
```

**Comment by lonlii4ap** [comment]
add v-if="dataList.length>0" for its parent to solve

**Comment by VasiliyPolyakov** [comment]
@lonlii4ap Thank you. I had the same issue. It helped me.

**Comment by sunxingchen1995** [comment]
十分感谢！弄了很长时间，看了你的回答解决了，谢谢！

**Comment by mengyagit** [comment]
太感谢了，问题解决了，谢谢~

**Comment by Hilbertangers** [comment]
its ok, but who can tell me why😂

**Comment by tomi20v** [comment]
ty, this helped me with the v-for with loop issue

**Comment by luxuebo** [comment]
循环到第一页时,是空白页,之后的正常,是什么问题

**Comment by andefine** [comment]
完美解决，但还是想知道为啥子(￣▽￣)／

**Comment by yerinho** [comment]
Estaré fuera de la oficina hasta el 6 de septiembre (incluido). Mi acceso al correo electrónico será limitado.
Si se trata de un tema urgente, puede ponerse en contacto en el email info@dfutura.com o en el teléfono 911880781.
Le ruego que disculpe las molestias que mi ausencia pueda provocarle.

Un saludo,

**Comment by pvakalo** [comment]
hey you people, you forgot your English? please contribute to the community by using the global language
