### ISSUE TITLE
How to make the slider loop without stops?

### ISSUE THREAD

**Issue by adamwardecki** [surmon-china/vue-awesome-swiper#339]
I'd like the swiper to work as a banner with items continuously flowing without stop.

This is how far I got: https://jsfiddle.net/w9denoad/

But the slides pause for a brief moment after each transition. Is there a way to have them transition without the pause?

**Comment by jfleblanc** [comment]
Take a look at .swiper-wrapper definition in swiper.css, you might want to change the `transition-timing-function: ease-out` to `transition-timing-function: linear`

**Comment by adamwardecki** [comment]
@jfleblanc That was it. Thank you a lot!

**Comment by Harshal1602** [comment]
transition-timing-function: ease-out to transition-timing-function: linear works fine. 
Thanks @jfleblanc
