### ISSUE TITLE
change swiper props doesn't work

### ISSUE THREAD

**Issue by mercer08** [surmon-china/vue-awesome-swiper#345]
#### Vue.js version and component version
Vue.js version  v2.5.13 
vue-awesome-swiper version v3.1.3

#### Reproduction Link
- https://codesandbox.io/s/38xy61p52q

#### Steps to reproduce
just click the reproduction link

#### What is Expected?   
when i change the allowTouchMove option of this component props.
 it should control the behavier of forbidding touch move event or  start the event.
but it doesn't work.

#### What is actually happening?
i saw this component computed doesn't change when i change the props by the vue develop tools,
so i think it's a bug

**Comment by 2lei** [comment]
Ok, i think the swiper component will not change its allowTouchMove option again after the instance inited. 
But is there anyway to update it's option data, or i must reinited the other instance after detsroy the old one. 
Could you give me some help out of this soluation

**Comment by 2lei** [comment]
Well, noSwiper work it out.

**Comment by vesper8** [comment]
it depends which version you're using. I got it to work like this on the latest version

```
├─ swiper@5.4.5
├─ vue-awesome-swiper@4.1.1
```

```
this.$refs.mySwiper.$swiper.allowTouchMove = false;
```

Take note of the `$swiper` instead of `swiper`
