### ISSUE TITLE
There is no swiper.css in 'dist' folder

### ISSUE THREAD

**Issue by SilicorniO** [surmon-china/vue-awesome-swiper#348]
#### Vue.js version and component version
Version 3.1.3

#### Reproduction Link
https://www.npmjs.com/package/vue-awesome-swiper

#### Steps to reproduce
Download the package with npm: npm install vue-awesome-swiper --save
Go to "node_modules" folder
Find "vue-awesome-swiper"
Select "dist"
There is not a css file that is requested in documentation

#### What is Expected?      
A file called swiper.css
(import 'swiper/dist/css/swiper.css')

#### What is actually happening?
There is not the file

**Comment by SilicorniO** [comment]
Auto-Fix: It is necessary to add the Swiper library: 
npm install --save Swiper

I thought the CSS file was in awesome folder but it is from swiper folder

**Comment by xpader** [comment]
Use this way to do that:
import 'vue-awesome-swiper/node_modules/swiper/dist/css/swiper.css'

**Comment by junhoyeo** [comment]
Mine was in `swiper/css/swiper.css`

**Comment by OtabekSadiridinov** [comment]
now it is in swiper/swiper-bundle.css

**Comment by erictor** [comment]
To add on to OtabekSadiridinov's comment above, in an Angular site that had a main styles.css file that does style imports, I needed to change the import to (using the minified version of the css):
@import '~swiper/swiper-bundle.min.css';
