### ISSUE TITLE
初次使用的时候发现的问题

### ISSUE THREAD

**Issue by douglasvegas** [surmon-china/vue-awesome-swiper#35]
发现插件并没有自动引入css所以有样式上的问题、折腾了半天。
解决方法：
1.下载swiper.min.css到本地
2.style中引入
<style>
@import '../swiper.min.css';
</style>

**Comment by surmon-china** [comment]
:)

**Comment by Cybs** [comment]
同样遇到这个问题，查半天，为啥不引入css呢？

**Comment by surmon-china** [comment]
想要css用旧版吧，已经在 README.md 写了要引入，还是第一行！

**Comment by Cybs** [comment]
@surmon-china 
我有看到你那句，但被我忽略了。。。

按你的意思是新版不需要css么？

**Comment by surmon-china** [comment]
任何版本都要，新版本只是把 css 的控制权交给开发者，满足不同业务场景下对 swiper 样式的自定义，你可以使用整套的自定义主题来代替默认的 css。

**Comment by Cybs** [comment]
@surmon-china 明白你的意图了，不过从开发者使用的角度，更加希望是有默认的样式，然后你们提供覆盖自定义，而不是默认的都要自己去添加css，因为我发现你这个库里连css文件都没有下载，还得去另外找，这坑啊~

**Comment by surmon-china** [comment]
如果你钻研点，就会知道 `webpack` 类似 aot 的编译方式目前根本做不到对资源的动态编译，可以给你加载默认，面临的另一个问题就是，当你不需要默认样式的时候，默认的css依然会被打包为几十K的无用css文件，并且会影响样式渲染；而且，npm 包之间只有依赖关系，没有复制关系，swiper 更新一次 就把他的css复制过来一次？

对于"坑"这个形容，我只能说有种 [ 心中无佛，世人皆魔 ] 的感觉，扎心。

**Comment by surmon-china** [comment]
你也可以看看不同的人的反馈啊 #123

**Comment by Cybs** [comment]
萝卜青菜各有所好，每人需求不同，我的想法可能也是针对某个场景比较片面，还是支持作者继续不停完善，很少有作者那么快给答复的，👍一个

**Comment by surmon-china** [comment]
@Cybs 没有最好的方案，只有最通用的方案；如果能被理解（为什么这么做，为什么不那么做）我会很😀，如果有好的建议，我会😁，如果像之前的有些人一句话不贴代码不描述不看已关闭的问题，js都写不好的跑来开开开问题，我就会，CTMD🤣
