### ISSUE TITLE
回调函数不生效

### ISSUE THREAD

**Issue by excxapp** [surmon-china/vue-awesome-swiper#364]
官方文档
<swiper :options="swiperOption" ref="mySwiper" @someSwiperEvent="callback">
我的使用
<swiper :options="swiperOption" ref="mySwiper" @slideChangeTransitionEndd="slideChangeTransitionEnd" @touchEnd="transitionStart">

无法调用，请官方给个具体的例子吧

**Comment by YangAi** [comment]
试试 @touchEnd="transitionStart"

http://idangero.us/swiper/api/#events

**Comment by YangAi** [comment]
`<swiper :options="pageSwiperOption" ref="pageSwiper" @slideChange="pageChange" class="swiper-box">`

This is the code we use in our project. Maybe you could try other events and test first.

 Sorry, my laptop can't type Chinese now.

**Comment by cmideal** [comment]
@YangAi  好的，我已经找到问题了，我版本升级错误的问题，升级4.0之后正常了，谢谢。

**Comment by tw-lws** [comment]
test

**Comment by yanghubin** [comment]
> 试试 @touchEnd="transitionStart"
> 
> http://idangero.us/swiper/api/#events

touchEnd可以，slideChange不可以是为什么呀
