### ISSUE TITLE
异步数据加载后，怎么更新swiper

### ISSUE THREAD

**Issue by hasbug** [surmon-china/vue-awesome-swiper#375]
英语不好，只能用中文提问了。
因为我是做类似聊天室的信息，需要循环滚动，我在vue中通过向后端取得数据后，我直接追加到我的最开始的message数组中，但我发现，滚动区域中的每一个滚动块的高度出现了科学计算值，高度非常大，并且滚动一两条信息后不动了，我通过this.swiper.update()方法貌似没效果。

求解。

**Comment by ahutyaoyj** [comment]
template中使用swiper组件，data中初始化一个swiperData数组，swiper组件内的item循环swiperData获得。 然后在mounted中获取后台数据，获取到之后更新vue data中的swiperData

**Comment by hasbug** [comment]
问题的重点不是更新data，而是数据变动后，swiper的高度计算不准确
