### ISSUE TITLE
change slidesPerView how to  init

### ISSUE THREAD

**Issue by gllhp** [surmon-china/vue-awesome-swiper#385]
修改了 slidesPerView 的值 调用update方法不管用

**Comment by NaClyxp** [comment]
> 修改了 slidesPerView 的值 调用update方法不管用

哥们解决了吗？

**Comment by surmon-china** [comment]
组件无法揣测 `options:change` 的真正意图，所以不会对传入的 `options` 做动态 reinit，你可以在外部对应的周期节点控制 `<swiper v-if="slidesPerViewChanged">`。

**Comment by yyman001** [comment]
就不能加个方法可以更新这个slidesPerView?
