### ISSUE TITLE
Thumbnail Slider behaving strange

### ISSUE THREAD

**Issue by smith64fx** [surmon-china/vue-awesome-swiper#39]
你们好 friends :)

I found a little bug using the "Thumbnail Swiper". When I click the next image and then the previous one, it goes to the next image.

Well... A picture is worth 1000 words :)

![Buggy](https://media.giphy.com/media/l0ExpjQP1Xb7af7Xi/giphy.gif)

I'm using Chrome on MaxOSx

**Comment by smith64fx** [comment]
aah.. You can't see my mouse.. Just make some clicks forward/backward then you will see the bug

**Comment by surmon-china** [comment]
Do you use the code here, or what is the difference between your code and the demo code?
https://github.com/surmon-china/vue-awesome-swiper/blob/master/examples/23-thumbs-gallery.vue

**Comment by smith64fx** [comment]
Yes I actually discovered the bug on the demo page.

Sometimes the mouse click doesn't react if I push a thumbnail. I'm trying to debug this now.

**Comment by surmon-china** [comment]
Show me the code.

**Comment by smith64fx** [comment]
I see this is a swiper bug.

http://idangero.us/swiper/

Here is the same behavior. Just try to click the thumbs, next, prev, next, prev etc... It's behaving very strange.

**Comment by smith64fx** [comment]
there is already a github issue.

https://github.com/nolimits4web/Swiper/issues/1623

this can be closed :)

**Comment by surmon-china** [comment]
Ok.
