### ISSUE TITLE
Webpack bundle both esm & cjs swiper.js

### ISSUE THREAD

**Issue by whitetrefoil** [surmon-china/vue-awesome-swiper#395]
#### Vue.js version and component version

Vue.js should not be related to this issue.

Webpack: v4.16.3
vue-awesome-swiper: v3.1.3
swiper.js: v4.3.5

#### Reproduction Link
Issue in build process instead of runtime.

#### Steps to reproduce
`import * as vas from 'vue-awesome-swiper'` then build in webpack.

#### What is Expected?      
Either `node_modules/swiper/dist/js/swiper.js` or `node_modules/swiper/dist/js/swiper.esm.bundle.js` is bundled.

#### What is actually happening?
Both of above are bundled.

#### Initial analysis
Looks like it's caused by how swiper.js is imported in source + UMD module format.

In the built code (`dist/vue-awesome-swiper.js`), it required `swiper/dist/js/swiper.js` and `swiper` module, while webpack resolve `swiper` module to `node_modules/swiper/dist/js/swiper.esm.bundle.js` because it's declared as an esm version in `swiper.js`'s `package.json` as:

```js
{
  // ...
  "main": "dist/js/swiper.js",
  "module": "dist/js/swiper.esm.bundle.js",
  // ...
}
```

#### Workaround
In webpack.config.js
```js
  // ...
  resolve: {
    alias: {
      'swiper/dist/js/swiper.js': 'swiper/dist/js/swiper.esm.bundle.js',
    },
  },
  // ...
```

**Comment by surmon-china** [comment]
Upgrade to v4.1.0 and read [custom-build-with-swiper](https://github.com/surmon-china/vue-awesome-swiper#custom-build-with-swiper).

(now: default imprort `swiper`)

(:
