### ISSUE TITLE
如何支持原插件的onTap事件？

### ISSUE THREAD

**Issue by shuanger051** [surmon-china/vue-awesome-swiper#40]
在原生的swiper中，有一个函数是点击slide可以加一下动作，我是这样写的
var swiper = new Swiper('.swiper-itme .swiper-container', {
                    pagination: '.swiper-itme .swiper-pagination',
                    slidesPerView: 'auto',
                    paginationClickable: true,
                    spaceBetween: 15,
                    onTap: function(swiper){
                        var index= swiper['clickedIndex'];
                        _self.focusThis(index);
                    }
                });
用目前的这个插件，不知道怎么写了，我按照以前的方法写了下，但是不支持。

**Comment by surmon-china** [comment]
该回调回调，该监听监听；
如果需要拿到当前的swiper对象，在readme中阅读ref和计算属性部分
