### ISSUE TITLE
Styles missing in SSR example.

### ISSUE THREAD

**Issue by wirsing** [surmon-china/vue-awesome-swiper#400]
#### Vue.js version and component version
Vue2.x vue-awesome-swiper 3.1.3

#### What is Expected?      
The SSR example is missing the style/css import from swiper
#### What is actually happening?
When loading the component as described in the SSR example all styles are missing and the swiper is not working properly. 

Solve: Import all styles in the nuxt plugin.

**Comment by AndrewBogdanovTSS** [comment]
you should include styles manually in the plugin or in the component where you use a swiper like so
`import 'node_modules/swiper/dist/css/swiper.min.css';`
or if you are using sass/postcss in your <style> section
`@import 'node_modules/swiper/dist/css/swiper.min.css';`

**Comment by surmon-china** [comment]
@AndrewBogdanovTSS Good job!
