### ISSUE TITLE
Please, provide a custom pagination example with outer pagination component

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [surmon-china/vue-awesome-swiper#416]
I want to build a custom pagination component that would reside outside of `swiper-wrapper` element. Since it has `overflow:hidden` applied to it - pagination is always cut by the wrapper. The only custom pagination example I was able to find is this one https://github.com/surmon-china/vue-awesome-swiper/blob/master/examples/07-pagination-custom.vue
but still it references an element that is inside of the slider, not outside of it

**Comment by woowyl** [comment]
may be the some question https://github.com/surmon-china/vue-awesome-swiper/issues/146

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-awesome-swiper/issues/628#issuecomment-611452830
