### ISSUE TITLE
jQuery Dependency

### ISSUE THREAD

**Issue by jgerbes** [surmon-china/vue-awesome-swiper#42]
This package cannot be used without jQuery, even though Swiper.js does not require it.

**Comment by surmon-china** [comment]
why?

**Comment by jgerbes** [comment]
Good question. This package should not require jQuery but does

**Comment by paulitolinhares** [comment]
I'm having the same problem. The project I'm working on doesn't use jQuery, and both Swiper.js and this very component doesn't set jQuery as a dependency, but when I try to run it, I get the following error:

```
 ERROR  Failed to compile with 1 errors                             4:06:02 PM

This dependency was not found:

* jquery in ./~/swiper/dist/js/swiper.js

To install it, you can run: npm install --save jquery
```

**Comment by ThomasRalee** [comment]
Same issue.
