### ISSUE TITLE
Please, provide custom build example

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [surmon-china/vue-awesome-swiper#422]
I want to use [Custom build functionality of Swiper.js](http://idangero.us/swiper/api/#custom-build) inside vue-awesome-swiper, as far as I saw from the list of package files there is no such option available, but maybe I'm just missing something. If such option exists - can you provide an example of using it, preferably inside Nuxt.js

**Comment by webistomin** [comment]
Any updates?

**Comment by avanishp2** [comment]
I am using just Swiper module of this library through custom build in my project. If there is any ways of doing it, let me know.

**Comment by surmon-china** [comment]
Upgrade to v4.1.0 and read [custom-build-with-swiper](https://github.com/surmon-china/vue-awesome-swiper#custom-build-with-swiper).

(:
