### ISSUE TITLE
loop:true activeIndex goes over the element counts

### ISSUE THREAD

**Issue by juneyoung** [surmon-china/vue-awesome-swiper#437]
#### Vue.js version and component version

I am currently using `vue.js 3.1.0` and swiper `^3.1.3`.

#### Reproduction Link

Here is the template .

```
<template>
	<swiper :options="swiperOption" @slideChange="onSlide" ref="categorySwiper">
		<swiper-slide v-for="(item, index) in slides" :key="index">
			<nuxt-link to="/">
				<img :src="imageUrl" />
			</nuxt-link>
		</swiper-slide>
	</swiper>
</template>
```

and here is the script 

```
export default {
	data : function () {
		return {
			slides : [],
			currentSlide : 0,
			swiperOption: {
				slidesPerView: 1,
				spaceBetween: 0,
				loop: true,
				pagination: {
					el: '.swiper-pagination',
					clickable: true
				},
				navigation: {
					nextEl: '.swiper-button-next',
					prevEl: '.swiper-button-prev'
				},
				autoplay: {
					delay: 5000,
				},
				speed : 1000
			}
		}
	},

	...

	methods : {
		onSlide : function () {
		const swiperIndex = this.$refs.categorySwiper.swiper.activeIndex;
		console.log('swiper index :: ', swiperIndex, ', item.length', this.slides.length)
		if(swiperIndex > this.slides.length) {
				this.currentSlide = swiperIndex%this.slides.length;
			} else this.currentSlide = swiperIndex;
		}
	}
	...	
}
```

When you watch console, `activeIndex` goes over `items.length + 1`. 

#### What is Expected?      
It is just my opinion, but an index should start with `0`, or at least, it should return correct numbers. Going over the count of elements looks a little bit weird. 

#### What is actually happening?

if `slides.length` is 2, activeIndex starts with 1 and goes till 3.

**Comment by juneyoung** [comment]
Sorry, It is my mistake. It works fine.

**Comment by gd4Ark** [comment]
Could you tell me how you solved it?

**Comment by gd4Ark** [comment]
Thank you very much for your reply.

But I seem to have found another solution.

Using the `realIndex` attribute, you can return the correct Index when you open loop

```js
onSlideChange(e) {
      const swiper = this.$refs.mySwiper.swiper;
      if (!swiper) {
        this.returnCurrent(0);
        return;
      }
      const index = swiper.realIndex;
      this.returnCurrent(index);
}
```
I'm thinking about opening a new issue。
