### ISSUE TITLE
index.js里的const没有编译成var

### ISSUE THREAD

**Issue by stop2stare** [surmon-china/vue-awesome-swiper#44]
你好，我在使用你的插件的时候遇到了一个问题。
在babel的配置文件里，我将node_modules排除了，但是最后编译的文件中，这个插件中index.js文件里的const并没有编译成var，依然是const。

**Comment by surmon-china** [comment]
下一个版本将修复。

**Comment by surmon-china** [comment]
Update to [v2.3.2](https://github.com/surmon-china/vue-awesome-swiper/tree/v2.3.2) please.

**Comment by stop2stare** [comment]
Thank you for updating so quickly.
