### ISSUE TITLE
vue-cli

### ISSUE THREAD

**Issue by shijunti19** [surmon-china/vue-awesome-swiper#45]
vue-cli+webpack
main.js
import VueAwesomeSwiper from 'vue-awesome-swiper'
到底怎么用，不都是这样引入就行了吗，怎么找不到模块，安装了啊
error:
 in ./~/vue-awesome-swiper/index.js
Module not found: Error: Can't resolve 'swiper' in 'F:\web\xiaolu\vue\a031\a031\node_modules\vue-awesome-swiper'
 @ ./~/vue-awesome-swiper/index.js 6:13-30
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
ERROR in ./~/.6.2.10@babel-loader/lib!./~/.10.3.0@vue-loader/lib/selector.js?type=script&index=0!./~/vue-awesome-swiper/swiper.vue
Module not found: Error: Can't resolve 'swiper' in 'F:\web\xiaolu\vue\a031\a031\node_modules\vue-awesome-swiper'
 @ ./~/.6.2.10@babel-loader/lib!./~/.10.3.0@vue-loader/lib/selector.js?type=script&index=0!./~/vue-awesome-swiper/swiper.vue 5:18-35
 @ ./~/vue-awesome-swiper/swiper.vue
 @ ./~/vue-awesome-swiper/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by surmon-china** [comment]
请提供更详细的main.js的信息

**Comment by shijunti19** [comment]
你把这个cnpm i swiper加到说明里呢，不过我安装的时候我看见他自动安装了，不知道为什么还得手动装
