### ISSUE TITLE
change filename

### ISSUE THREAD

**Issue by ruden91** [surmon-china/vue-awesome-swiper#451]
https://github.com/surmon-china/vue-awesome-swiper/blob/4b4f9cbd0dcc1702492b89516a918fda97863eb7/examples/nuxt-ssr-example/nuxt.config.js#L4

swiper.js -> nuxt-swiper-plugin.js

**Comment by giovannimanzoni** [comment]
yes, I confirm

**Comment by surmon-china** [comment]
Thx! example files updated.
