### ISSUE TITLE
horizontal 模式下，swiper-slide 被一个接一个 竖排放置了

### ISSUE THREAD

**Issue by liujiangfeng** [surmon-china/vue-awesome-swiper#452]
### 中文用户注意：

 三个swiper-slide 
![image](https://user-images.githubusercontent.com/5728755/50153680-0f1eb780-0302-11e9-863f-ceddfe3bd3af.png)

**Comment by yanglinxiao** [comment]
我也遇到这种情况，请问怎么解决的？

I get the same problem，how to deal with it ?

**Comment by milulee** [comment]
Me too，how to deal with it？

**Comment by milulee** [comment]
I lost this code:
 import 'swiper/dist/css/swiper.css'

**Comment by jzfan** [comment]
me too.

**Comment by yanglinxiao** [comment]
> me too.

import 'swiper/dist/css/swiper.css'
