### ISSUE TITLE
why  the callback of "slideChange" has no Arguments?

### ISSUE THREAD

**Issue by CodLee** [surmon-china/vue-awesome-swiper#454]
为什么slideChange 回调没有参数，http://idangero.us/swiper/api/#events  这里的events 中也标注了没有

**Comment by kristijan97** [comment]
I am wondering too. Why?

**Comment by githubalin** [comment]
可以通过实例，获取属性，比如当前下标
this.$refs.swiper.swiper.activeIndex

**Comment by surmon-china** [comment]
组件对 Swiper 的事件参数采用透传处理，`Swiper.slideChange` 确实没有参数。
