### ISSUE TITLE
如何吧前后按钮外置化

### ISSUE THREAD

**Issue by chenweibo** [surmon-china/vue-awesome-swiper#457]
因为有个样式的要求需要这个两个按钮在外部 ，我之前直接引用的时候，没用组件 直接swiper-button-prev 外置化是没问题的。我需要怎么样才能做到这种需求啊。

**Comment by chenweibo** [comment]
![2018-12-25 10 16 19](https://user-images.githubusercontent.com/19586007/50409518-39a2d000-082e-11e9-9f2b-82c27ac10b37.png)
这种我放到外部的前后切换按钮

**Comment by chenweibo** [comment]
因为overflow: hidden; 的缘故  按钮绝对定位不了到 外部

**Comment by daipanpan** [comment]
可以强制复写去掉overflow:hidden属性
