### ISSUE TITLE
切换页面时报错：无法读取未定义的this.swiper.update方法

### ISSUE THREAD

**Issue by Zegapaiz** [surmon-china/vue-awesome-swiper#47]
![image](https://cloud.githubusercontent.com/assets/12904995/22879265/1fc87ff0-f218-11e6-80d6-b64092a8e9bd.png)

想知道都hui shi会是什么原因呢 使用vue2+vue-router  第一个地方每次离开页面时报错  第二个地方一进入就报错 。而它们一开始开发的时候都没有报错

**Comment by Zegapaiz** [comment]
上面的是chrome的提示，下面是safari的提示
![image](https://cloud.githubusercontent.com/assets/12904995/22910001/55525414-f292-11e6-8823-197ddec11c57.png)

**Comment by Zegapaiz** [comment]
![image](https://cloud.githubusercontent.com/assets/12904995/22910055/99f87224-f292-11e6-91b2-cea891773e04.png)

**Comment by Zegapaiz** [comment]
已解决 加载时数据不全问题

**Comment by surmon-china** [comment]
ok:)
