### ISSUE TITLE
On last slide, if you try sliding back, nothing happens

### ISSUE THREAD

**Issue by faberjr** [surmon-china/vue-awesome-swiper#472]
#### Example Code
    <swiper ref="mySwiper">
        <swiper-slide v-for="(p, index) in items" :key="p.id">
        </swiper-slide>
     </swiper>
#### Steps to reproduce
Create a Swiper, then add multiple slides via a `v-for`. Go to the last slide and try sliding back.
#### What is Expected?      
Getting to the last slide, if you slide back, the swiper goes back one slide.
#### What is actually happening?
Getting to the last slide, if you slide to go backwards, nothing happens.

**Comment by MattixNow** [comment]
Can you explain ?
