### ISSUE TITLE
swiper的回调函数无法调用的当前组件的methods

### ISSUE THREAD

**Issue by ChowYoung** [surmon-china/vue-awesome-swiper#48]
您好，我现在在swiper的回调函数里 想要调我当前组件的methods里的方法，调不到了，能帮帮忙么？
这个this指向不是当前vue对象，而是swiper，那怎么才能获取到当前vue对象呢？
![image](https://cloud.githubusercontent.com/assets/17489186/22962782/2cec85a0-f38a-11e6-86fd-808e7209adec.png)

**Comment by surmon-china** [comment]
箭头函数

onTouchStart: () => {
// this
}

**Comment by YosefYuan** [comment]
可以参考下这里：
https://stackoverflow.com/questions/43107393/vue-awesome-swiper-and-callback-functions
