### ISSUE TITLE
【按钮切换】渲染后的按钮dom位置错误

### ISSUE THREAD

**Issue by zwsf** [surmon-china/vue-awesome-swiper#492]
### BUG REPORT TEMPLATE
![image](https://user-images.githubusercontent.com/7145419/56368094-4e660200-6229-11e9-9ed1-7ceaf1221964.png)

切换的按钮最终不应该与swiper-slider是兄弟元素，这样定位就相对于切换容器进行，导致切换后按钮也随着切换走
#### Vue.js version and component version
vue 2.2.2

###模板文件：
![image](https://user-images.githubusercontent.com/7145419/56368797-bec15300-622a-11e9-87aa-6cd1a28bc4e4.png)

###配置：
![image](https://user-images.githubusercontent.com/7145419/56368826-ca147e80-622a-11e9-9f0e-6e6a3d36eac1.png)

**Comment by zhanglong2397** [comment]
解决了吗
