### ISSUE TITLE
when I set Vertical,loop only active once

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [surmon-china/vue-awesome-swiper#496]
when I set Vertical,loop only active once

**Comment by Liquid-Zhangliquan** [comment]
![image](https://user-images.githubusercontent.com/23397455/57204252-0ac11580-6fe9-11e9-87c6-6552d2f0eddf.png)
![image](https://user-images.githubusercontent.com/23397455/57204255-114f8d00-6fe9-11e9-8d0b-2f299c8d1dd2.png)
![image](https://user-images.githubusercontent.com/23397455/57204261-1d3b4f00-6fe9-11e9-809f-35daa2393f41.png)
![image](https://user-images.githubusercontent.com/23397455/57204268-288e7a80-6fe9-11e9-9715-c8fd6f1b43e2.png)

**Comment by damiothar** [comment]
Having the same problem here, and if you set `slidesPerView: 'auto'` it wont even loop once.
