### ISSUE TITLE
nuxt一个页面如何使用多个swiper

### ISSUE THREAD

**Issue by lyfpf** [surmon-china/vue-awesome-swiper#498]
`"vue-awesome-swiper": "^3.1.3"`
`"nuxt": "^2.4.0"`

**HTML代码**
![iamge](https://raw.githubusercontent.com/lyfpf/noedjs/master/1557472556(1).png)
**JS代码**
![123](https://raw.githubusercontent.com/lyfpf/noedjs/master/1557472582(1).png)
**你仔细看，第二就没有分页器了，而且所有操作都失效**
![789](https://raw.githubusercontent.com/lyfpf/noedjs/master/1557473034(1).png)

**Comment by thatmatthewxu** [comment]
需要创建多个Swiper实例。

第一个swiper，使用：

`<div v-swiper:swiper1="swiperOption1">.....</div>`

第二个swiper，使用：

`<div v-swiper:swiper2="swiperOption1">.....</div>`

**Comment by surmon-china** [comment]
[here](https://github.com/surmon-china/vue-awesome-swiper#swiper-directive-api).
