### ISSUE TITLE
every img twice load

### ISSUE THREAD

**Issue by Erimons-chan** [surmon-china/vue-awesome-swiper#510]
Repetition
When I use lazy swiper,the picture reload twice
F12 in chrome ->network ->disable cache ->img
You will find it

**Comment by jintangWang** [comment]
I used nuxt, and found the same issue.

**Comment by jintangWang** [comment]
It's our usage problem, I found the answer, at [here](https://github.com/nolimits4web/swiper/issues/3079#issuecomment-514140919). We should't checked  'disable cache'。This issue should be closed.
