### ISSUE TITLE
loop模式开启后，异步获取数据只能显示最后一个

### ISSUE THREAD

**Issue by woodygithub** [surmon-china/vue-awesome-swiper#52]
notNextTick为true，initialSlide为1,

**Comment by surmon-china** [comment]
请帖出详细代码

**Comment by woodygithub** [comment]
![image](https://cloud.githubusercontent.com/assets/7663246/23638855/21c404c4-031f-11e7-80c2-680495767bb9.png)

**Comment by woodygithub** [comment]
swiperOption: {
                    notNextTick: true,
                    direction : 'horizontal',
                    initialSlide: 1,
                    loop:true,
                    onSlideChangeEnd:(swiper)=>{
                        console.log(swiper.realIndex);
                    },
                    onTouchEnd:(swiper, event)=>{
                        
                    },
                    onTap:(swiper)=>{

                    }
                }


Model.getAllRecordInfo({
      userId : this.userData.userId,
      type : 1
}).then(data=>{
      Indicator.close();
      for(var i = 0; i< this.cars.length;){
            this.cars.$remove(this.cars[i]);
      }
      this.cars = data.data.carInRecords.concat( data.data.noneCarInRecords );
}).catch(data=>{
      Indicator.close();
      Toast.toast(data.msg);
})

**Comment by surmon-china** [comment]
- 首先，要确定异步数据拼接后，数据是否在预期之内。
- `initialSlide`和异步数据本身不会有关系，数据更新时，组件仅执行了`swiper`的`update`方法，此方法并不会重新实例化实例；正常的状态应该是，数据更新后，活动页应该正常停留的数据更新前的活动页，鉴于你所描述的现象，可能是因为数据更新时，活动页下标在最后一页或首页，和loop模式的节点复制产生了冲突，导致所看到的现象，具体原因需要多次测试，期待你的反馈，问题暂且关闭。
