### ISSUE TITLE
在vue中引入swiper， 设置loop：true， autoplay：2000 不会自动滚动

### ISSUE THREAD

**Issue by jakietwo** [surmon-china/vue-awesome-swiper#522]
# 设置autoplay：2000 不会自动滚动

**Comment by NextDoorLaoWang911** [comment]
+1

**Comment by liuwujie** [comment]
最新版本更改后，autoplay接收的值不再是毫秒数，你可以把autoplay：2000替换为autoplay:{delay: 2000}来使用自动播放功能。

**Comment by YueCynthia** [comment]
我把autoplay：2000替换为autoplay:{delay: 2000}了还是不动，分页也是空的

**Comment by ixyx** [comment]
> 我把autoplay：2000替换为autoplay:{delay: 2000}了还是不动，分页也是空的



> 我把autoplay：2000替换为autoplay:{delay: 2000}了还是不动，分页也是空的

可以的哦，可能是你的使用姿势不对。如果还没解决可以把代码贴上来看看

**Comment by ixyx** [comment]
> 我把autoplay：2000替换为autoplay:{delay: 2000}了还是不动，分页也是空的

https://github.com/surmon-china/vue-awesome-swiper/issues/522#issuecomment-526800883

**Comment by ixyx** [comment]
> 我把autoplay：2000替换为autoplay:{delay: 2000}了还是不动，分页也是空的

可以正常使用的，可能是你的使用姿势不对。如果还未解决，可以把代码贴上来看看

**Comment by xqshen** [comment]
我也遇到这个问题了，一开始不会动，点击或拖动一下后就可以自动播放了。
<template>     
 <swiper :options="swiperOption">
        <swiper-slide v-for="(slide,index) in slideList" :key="index"><img :src= getImgUrl(slide) class="slide-img"/></swiper-slide>
      </swiper>
</template>

<script>
export default {
  name: 'home',
  data () {
    return {
      fit: 'scale-down',
      fit2: 'cover',
      img1_src: 'bridge001.jpg',
      img2_src: 'bridge002.jpg',
      img3_src: 'bridge003.jpg',
      slideList: ['采空区1.jpg', '采空区2.jpg', '点云1.png', '机器人1.png', '机器人2.png', '三维1.png', '无人机1.png', '物探1.png', '系统1.png', '系统2.png'],
      swiperOption: {
//     　　observer:true,//修改swiper自己或子元素时，自动初始化swiper 
// 　　    observeParents:true,//修改swiper的父元素时，自动初始化swiper 
        slidesPerView: 5, // 预览的数量
        spaceBetween: 30,
        loop: true,
        // loopAdditionalSlides : 0,
        // centeredSlides: true,
        speed: 2000,
        autoplay: {
          delay: 0,
          disableOnInteraction: false
        }
      }
    }
  }
}
</script>

**Comment by xilanhuaweidapao** [comment]
动是会动，谁能告诉我为啥loop没效果，到了最后一页就不循环了，没加loop:true反而会从右往左闪回第一页。。。

**Comment by Eurkidu** [comment]
@xilanhuaweidapao 
如果你 `swiper-slide` 是通过获取的动态数据 `list` 然后使用 `v-for` 渲染的话，需要 `swiper` 组件在数据 `list` 获取之后再渲染，即给 `swiper` 组件加个 `v-if="list && list.length > 0"` 这样 `loop` 就有效了。
因为 `swiper` 初始化的时候就会判断内部 `swiper-slide` 的个数然后动态插入 `loop` 需要的节点，因为初始化的时候数据还没获取到所以会导致 `loop` 无效。

**Comment by xilanhuaweidapao** [comment]
> @xilanhuaweidapao
> 如果你 `swiper-slide` 是通过获取的动态数据 `list` 然后使用 `v-for` 渲染的话，需要 `swiper` 组件在数据 `list` 获取之后再渲染，即给 `swiper` 组件加个 `v-if="list && list.length > 0"` 这样 `loop` 就有效了。
> 因为 `swiper` 初始化的时候就会判断内部 `swiper-slide` 的个数然后动态插入 `loop` 需要的节点，因为初始化的时候数据还没获取到所以会导致 `loop` 无效。

非常感谢

**Comment by surmon-china** [comment]
v4.x 解决了此问题，不再需要手动判断。升级后若还有异常，则重开此 issue。
