### ISSUE TITLE
关于webpack打包体积的问题

### ISSUE THREAD

**Issue by Xixi20160512** [surmon-china/vue-awesome-swiper#527]
https://github.com/surmon-china/vue-awesome-swiper/blob/4b4f9cbd0dcc1702492b89516a918fda97863eb7/src/index.js#L9

我看到源码里面是引用swiper的dist文件，是否可以改为引入esm使得打包后的体积尽可能小？

**Comment by surmon-china** [comment]
Upgrade to v4.1.0 and read [custom-build-with-swiper](https://github.com/surmon-china/vue-awesome-swiper#custom-build-with-swiper).

(:

**Comment by ycvcb123** [comment]
> Upgrade to v4.1.0 and read [custom-build-with-swiper](https://github.com/surmon-china/vue-awesome-swiper#custom-build-with-swiper).
> 
> (:

有问题啊，我用这种方式反而更大了，帮忙看下哪里的问题：

![image](https://user-images.githubusercontent.com/15381888/146197067-2bd2bc06-d400-435f-b8a7-f5b21e8e3ae8.png)
优化前后打包的体积，反而更大了：

![image](https://user-images.githubusercontent.com/15381888/146197154-1e947c5a-6026-4901-8195-96071bbb181a.png)

![image](https://user-images.githubusercontent.com/15381888/146197236-2598a481-43cb-4d5c-9f2e-7f1259d6159f.png)
