### ISSUE TITLE
Nuxt.js   在 refresh page 刷新页面 window is not defined? why

### ISSUE THREAD

**Issue by wzxxzw** [surmon-china/vue-awesome-swiper#531]
refresh page 刷新页面 window is not defined? why

![168FC3FB-E017-4ce3-8B8D-14F18620E902](https://user-images.githubusercontent.com/41424651/61782937-88066480-ae39-11e9-9844-5e5e78566305.png)
![4A8A66C9-81A2-4a67-A646-BD40B9FDEEB7](https://user-images.githubusercontent.com/41424651/61783032-b2582200-ae39-11e9-8283-fd454e9a5a90.png)
![01E1CBB6-1753-480d-A8BF-4B9C3C58539D](https://user-images.githubusercontent.com/41424651/61783129-d451a480-ae39-11e9-9366-c294d158f52f.png)
![73B4308E-BAE5-48c1-A57A-1FD04AF6E5CA](https://user-images.githubusercontent.com/41424651/61783399-4fb35600-ae3a-11e9-8953-3ace763597b3.png)

**Comment by zhanfu93** [comment]
在if (process.client) {}里面写入

**Comment by wzxxzw** [comment]
> 在if (process.client) {}里面写入
请问是判断条件不对嘛？但是换了还是刷新报错

**Comment by surmon-china** [comment]
使用 directive，而非组件，详情阅读 v4.x 文档。
