### ISSUE TITLE
如何结合el-menu使用？

### ISSUE THREAD

**Issue by lifanmvc** [surmon-china/vue-awesome-swiper#538]
项目中，想实现菜单滚动，用：
` <el-menu class="el-menu-demo" mode="horizontal">
            <swiper :options="swiperOption">
              <el-menu-item v-for="o in swiperSlides" class="swiper-slide" :key="o" index="1">菜单{{o}}</el-menu-item>
            </swiper>
          </el-menu>`
可是实现，但是破坏了ul和li的结构
请教，应该怎么正确使用？

**Comment by surmon-china** [comment]
`<swiper>` 组件内仅接受 `<swipr-slide>` 或其他具名组件。

**Comment by lifanmvc** [comment]
谢谢高手.

发送自 Windows 10 版邮件应用

发件人: Surmon
发送时间: 2020年3月29日 23:11
收件人: surmon-china/vue-awesome-swiper
抄送: lifanmvc; Author
主题: Re: [surmon-china/vue-awesome-swiper] 如何结合el-menu使用？ (#538)

Closed #538.
