### ISSUE TITLE
如何判断是否可滑动

### ISSUE THREAD

**Issue by lifanmvc** [surmon-china/vue-awesome-swiper#540]
请教如果判断是否有滑动。我想控制如没有滑动，就不显示左右箭头，如果已经滑不可以再左滑动了，就不显示左箭头；如果已经不可以再右滑动，就不显示右箭头。谢谢。

**Comment by surmon-china** [comment]
API 文档有详尽的数据提供，https://www.swiper.com.cn/api/index.html。

具体业务实现去网络社区提问，而非 Issue。
