### ISSUE TITLE
controller not work ssr mode

### ISSUE THREAD

**Issue by kooshkestani** [surmon-china/vue-awesome-swiper#547]
Hi I used nuxt js and use example (https://github.com/surmon-china/vue-awesome-swiper/blob/master/examples/31-thumbs-gallery-loop.vue) in project but not work in ssr mode

~~~~
 this.$nextTick(() => {
        const swiperTop = this.$refs.swiperTop;
        const swiperThumbs = this.$refs.swiperThumbs;
        swiperTop.controller.control = swiperThumbs
        swiperThumbs.controller.control = swiperTop
      })
~~~~

Error:
```
CANNOT SET PROPERTY 'CONTROL' OF UNDEFINED
```
Hope this helps!

**Comment by kooshkestani** [comment]
![ssss](https://user-images.githubusercontent.com/45139569/63686075-3aa15c80-c816-11e9-8e3d-fbe3da4b8075.PNG)

**Comment by kooshkestani** [comment]
Soleved:
Use:
v-swiper:mySwipper1
and
v-swiper:mySwipper2

**Comment by lusianaharyanti** [comment]
hello @kooshkestani where add mySwipper1? changing swiperTop or what?

**Comment by pablosnwg** [comment]
Hi. had same issue when i try to get controls from swiper.
I solved it by uninstalling latest version of "swiper" from npm (in package.json file, was isntaled "swiper": "^6....",).
Then installed older version of "swiper" by "npm i swiper@5.4.5".
PS. current version of "vue-awesome-swiper": "^4.1.1",
Maybe it helps for you

**Comment by songbaizhi** [comment]
@pablosnwg  很感谢你

**Comment by DropTheBase** [comment]
> hello @kooshkestani where add mySwipper1? changing swiperTop or what?

Hi, did u solved ur issue? Thanks

**Comment by root5427** [comment]
@surmon-china any updates on this? Still not working in SSR mode.
