### ISSUE TITLE
如何在swiper-slide上绑click事件？

### ISSUE THREAD

**Issue by KevinCN511** [surmon-china/vue-awesome-swiper#55]
`<swiper-slide v-for="c in course.related" class="course" @click="goCourse(c.id)">`

上面代码中的goCourse方法不执行

**Comment by surmon-china** [comment]
@click.native

**Comment by KevinCN511** [comment]
可以了，谢谢 surmon

**Comment by yinbingfan** [comment]
改为@click.native还是不执行啊

**Comment by reynold-Yang** [comment]
http://www.swiper.com.cn/api/event/onClick.html

**Comment by guanggefaguang** [comment]
nb
好了！
