### ISSUE TITLE
How can i use swiper in nuxt static generator?

### ISSUE THREAD

**Issue by WebMBX** [surmon-china/vue-awesome-swiper#556]
Hi. I use static deployment method in nuxt js. I try any ways to import swiper in my app,  but it not working if i open static html files (from nuxt generate command). How i was resolve this problem?

**Comment by cihakmar** [comment]
Hi, I have the same issue when using SSR. I get always " Failed to resolve directive: swiper" error and carousel do not work. 

Please how to handle this?

**Comment by newt0** [comment]
Me, too.
When I deploy my app  as a static site via Netlify, th vue-awsome-swiper doesn't work.

**Comment by surmon-china** [comment]
Example project:
 - [generate](https://github.com/surmon-china/surmon-china.github.io/blob/source/package.json#L12)
- [plugin](https://github.com/surmon-china/surmon-china.github.io/blob/source/plugins/vue-awesome-swiper.ts)
- [nuxt.config.js](https://github.com/surmon-china/surmon-china.github.io/blob/source/nuxt.config.js#L65)
- [usage](https://github.com/surmon-china/surmon-china.github.io/blob/source/components/mammon/aliyun-swiper.vue)

**Comment by WebMBX** [comment]
> Me, too.
> When I deploy my app as a static site via Netlify, th vue-awsome-swiper doesn't work.

My problem was i put generated files in subdirectory on the hosting. I resolved it when added correctly address in nuxt.config.js in section:
router: {
      base: 'path/to/folder'
    }

**Comment by caihai123** [comment]
请问有合适的解决办法了吗 我也遇到了同样的问题

**Comment by wusongliang** [comment]
+1

**Comment by wusongliang** [comment]
Try changing the swiper version.

**Comment by AndrewBogdanovTSS** [comment]
@WebMBX provide a reproduction repo, please. Did you try using this method of creating a swiper? https://github.com/surmon-china/vue-awesome-swiper/issues/680#issuecomment-666364812

**Comment by Dhruvi16** [comment]
Hey People! I need to access the swiper from the script as I need to change the slide with the click of a particular icon. How can I do that? I tried with refs but it is not working for me. So please if anyone can help me out here.
Thanks in advance.

**Comment by AndrewBogdanovTSS** [comment]
@Dhruvi16 your question isn't related to the one described in this ticket. Search though existing issues - your question was already answered multiple times
