### ISSUE TITLE
当图片都为(from memory cache)时，轮播失效

### ISSUE THREAD

**Issue by chenli1989** [surmon-china/vue-awesome-swiper#56]
暂时解决方案为[slide.vue#L11](https://github.com/surmon-china/vue-awesome-swiper/blob/master/slide.vue#L11)修改为
`let self = this;`
`self.$nextTick(()=> {
        self.update()
 })`

**Comment by surmon-china** [comment]
无法确定问题根源，建议贴出详细代码，或更为具体的上下文环境

**Comment by surmon-china** [comment]
是否尝试将`attached`替换为`attached`钩子，可能会解决问题，若解决，请反馈，即时更新。
