### ISSUE TITLE
vue-cli3，can not read ‘Swiper’ of undefined

### ISSUE THREAD

**Issue by ruiyong-lee** [surmon-china/vue-awesome-swiper#563]
### BUG REPORT TEMPLATE
vue-cli3

use: import VueAwesomeSwiper from 'vue-awesome-swiper';
throw error "can not read ‘Swiper’ of undefined"

use: import VueAwesomeSwiper from 'vue-awesome-swiper/src';
it works!

#### Vue.js version and component version
2.6.10

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### What is actually happening?

**Comment by surmon-china** [comment]
Upgrade to v4.x please.
