### ISSUE TITLE
Swipe and route change?

### ISSUE THREAD

**Issue by ghost** [surmon-china/vue-awesome-swiper#564]
What would be the best practice to combine swipe and router?

E.g user swipe and route change from somedomain.com to somedomain.com/newhandle

Thanks!

**Comment by dadmor** [comment]
`data: function() {
    const _t = this;
    return {
      swiperOption: {
         on: {
            slideChange() {
               _t.$router.push({ params: { your_param_name: this.snapIndex }});
            },
          
         },
      }
   }
}`

**Comment by surmon-china** [comment]
@dadmor Right!


```html
<swiper ref="mySwiper" @slide-change-end="onSwiperSlideChangeEnd" />
```

```js
onSwiperSlideChangeEnd() {
  this.$router.push({ params: { index: this.$refs.mySwiper.$swiper.activeIndex }})
}
```

**Comment by daniloc1910** [comment]
I'd like to make slide 'swipe-capa-1' go to one route and 'swipe-capa-2' go to another route. Is it possible?

`    <swiper class="swiperzao" :options="swiperOption">
      <swiper-slide class="swipe1"></swiper-slide>
      <swiper-slide class="swipe-capa-1"><img class="swipe-img" :src="require('~/assets/img/nxt-prj.jpg')" /></swiper-slide>
      <swiper-slide class="swipe-capa-2"><img class="swipe-img" :src="require('~/assets/img/nxt-prj.jpg')" /></swiper-slide>
    </swiper>`

**Comment by daniloc1910** [comment]
@surmon-china It doesn't work here. I'd like to point .slide-1 to one route and .slide-2 to another. Is it possible?

```
    <swiper class="swiperzao" ref="mySwiper" :options="swiperOption" @slide-change-end="onSwiperSlideChangeEnd">
      <swiper-slide class="swipe1"></swiper-slide>
      <swiper-slide class="slide-1"><img class="swipe-img" :src="require('~/assets/img/nxt-prj.jpg')" /></swiper-slide>
      <swiper-slide class="slide-2"><img class="swipe-img" :src="require('~/assets/img/nxt-prj.jpg')" /></swiper-slide>
    </swiper>
```
