### ISSUE TITLE
fail to import swiper

### ISSUE THREAD

**Issue by Ivan-blade** [surmon-china/vue-awesome-swiper#570]
+ page error
```
Module not found: Error :can't resolve 'swiper/dist/css/swiper.css'
```
+ console warn
```
This dependency was not found:
* swiper/dist/css/swiper.css in ./src/main.js
To install it, you can run: npm install --save swiper/dist/css/swiper.css
```
+ npm install --save swiper/dist/css/swiper.css
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "swiper\dist\css\swiper.css" as it does not contain a package.json file.
```
+ source
```
import Vue from 'vue';
import VueAwesomeSwiper from 'vue-awesome-swiper';
import 'swiper/dist/css/swiper.css';
import App from './App.vue';
import router from './router';
import store from './store';
import './assets/css/reset.css';
import './assets/fonts/iconfont.css';
import 'lib-flexible';
Vue.config.productionTip = false;

Vue.use(VueAwesomeSwiper);
new Vue({
  router,
  store,
  render: h => h(App),
}).$mount('#app');

```

**Comment by yuanhuanwebfront** [comment]
**swiper.css** in your **node_modules directory**, if you have "can't resolve 'swiper/dist/css/swiper.css", you should check the this file path is right?

**Comment by Ivan-blade** [comment]
I meet this problem two times,the first time, I rewrite the project and it works.the second time is now,I don't want to rewrite it but I don't know what to do

**Comment by surmon-china** [comment]
v4.0.0 was released!

May be you need reread the document. (Swiper was move to `peerDependencies`)

**Comment by fatid** [comment]
If you don't want to change anything in your code,  just downgrage package. The code is below:

npm i vue-awesome-swiper@3.1.3 --save

**Comment by vesper8** [comment]
For those scratching their head at this error. It's because it's not enough to just install vue-awesome-swiper, you have to explicitly also install the package `swiper` which wasn't required in V3. Just do a `npm i swiper --save` and it will work

**Comment by OtabekSadiridinov** [comment]
npm i swiper --save
or
yarn add swiper --save

and then:
import { Swiper, SwiperSlide } from 'vue-awesome-swiper'
import 'swiper/swiper-bundle.css'

**Comment by GhostyCHEN** [comment]
I have the same question ,and I use `import  'swiper/css/swiper.css'` to fix it

**Comment by vbarrientos97** [comment]
> I have the same question ,and I use `import 'swiper/css/swiper.css'` to fix it

where??

**Comment by Slavichek** [comment]
fixed by changing path to file    'swiper/swiper.scss'

**Comment by programmeranamul** [comment]
> @vbarrientos97 Add these two lines inside your component's script tag:
> 
> ```
> import { Swiper, SwiperSlide, directive } from "vue-awesome-swiper";
> import "swiper/css/swiper.css";
> ```
This is not working

**Comment by Christo-Deyzel** [comment]
I agree, all the above solutions don't work!

**Comment by barhouum7** [comment]
@programmeranamul, @Christo-Deyzel, try this and it should work:

`npm i swiper --save`
or
`yarn add swiper --save`
and then:

```
import { Swiper, SwiperSlide } from "vue-awesome-swiper"
import "swiper/swiper-bundle.css"
import "swiper/css/swiper.css"
```
If this doesn't work, so please, give us more details about the error that you are facing.

**Comment by sir-kain** [comment]
This is a [known issue](https://github.com/nolimits4web/swiper/issues/4871) when using **Swiper v7**.

I temporarily fixed the problem in my project by downgrading `swiper`
`yarn add swiper@6 --save`

We should update this package to be compatible with the new **Swiper** version.

**Comment by samuelgoldenbaum** [comment]
As per [docs](https://swiperjs.com/migration-guide): "As Swiper 7 uses exports field in package.json, all styles imports are predefined and it is not allowed to import files directly."

```
// swiper bundle styles
import 'swiper/css/bundle'

// swiper core styles
import 'swiper/css'

// modules styles
import 'swiper/css/navigation'
import 'swiper/css/pagination'
```

**Comment by MandelaMan** [comment]
None of the solutions mentioned above seem to work for me i am using swiper version "^7.0.4"

Trying to add css does not work with all solutions above

**Comment by ayimdomnic** [comment]
@MandelaMan I opted to remove swiper for now.. might delay the feature I am working on

**Comment by winstonfale** [comment]
its resolve on my case. ive upgraded 
swiper@6

then on import is
import "swiper/swiper.scss";

**Comment by sagarsiwach** [comment]
Hey,

I have faced the same problem, where my images module isn't found during gatsby build time, I cloned the repo of swiper js in a separate directory and copied the missing files and then added them to my git repo to prevent it from installing during cloud build time. this works for the time being until the fix is shipped.

**Comment by mustafa174** [comment]
someone please fixed this issue I am facing swiper/css module not found
I have uninstalled and install v6 still issue same. changed import directory still issue is there. error is only with swiper/css

**Comment by barhouum7** [comment]
@mustafa174, please try these steps below:

```ruby
npm cache clean -f
npm uninstall swiper
npm uninstall vue-awesome-swiper

npm cache clean -f
npm install --save swiper@5
npm install vue-awesome-swiper@4 --save --legacy-peer-deps
```
Please let me know if you have resolved the issue

**Comment by lowskill272** [comment]
Downgrade to version 6 is resolved the issue with import components Swiper and SwiperSlider, but im stil doesnt know how to import styles

**Comment by rosnaib11** [comment]
Idk lol.. Everything you tried to import, can't resolve

**Comment by sandercoffee** [comment]
"swiper": "^6.8.4",
"vue-awesome-swiper": "^4.1.1",

with 

```
import Vue from "vue"
import { directive } from "vue-awesome-swiper"
import "swiper/swiper.min.css"

Vue.directive("swiper", directive)
```

working fine, FINALLY!

**Comment by pcarballeda** [comment]
Same problem here using Swiper 7.0.6. I was using version 6.8.4 and everything was working fine. After upgrade to version 7.0.6 I am getting `Can't resolve '~swiper/swiper-bundle.min.css'` when the file exists in `./node_modules/swiper/`.

No matter what version of (S)CSS I use, I am getting always the same error, looks like import stylesheets from Swiper doesn't work anymore.

**Comment by RobertGres** [comment]
I have same problem installing 7.0.8

Fixed by using absolute path to node_modules, e.g. `@import '../../../../../../node_modules/swiper/swiper.scss';`

An odd problem since imports from other packages work fine with alias like `@import '~sass-rem/rem';`.

**Comment by xmoki** [comment]
i think it has to do with the way exports are configured on swiper package.json:

// this was always giving an error of file not found
@import "~swiper/swiper";  

// this fixed the issue since is what is configured on the exports of swiper package.json ("./scss": "./swiper.scss",)
@import "~swiper/scss";

**Comment by opopMihai** [comment]
npm i -g sass
or
npm i sass --save-dev

**Comment by mafnan2** [comment]
i had the same problem 
fixed it by giving a absolute path import "../../../../node_modules/swiper/swiper-bundle.min.css";
I don't know why the nextJs or reactJs wont take the imports like the other packages lol

**Comment by klich3** [comment]
Solution for Swiper 7.4.1 on Vue 3 + Vite and compile with Webpack

[https://stackoverflow.com/questions/69179230/unable-to-use-swiper-vue-dependencies-not-found/70755021#70755021](https://stackoverflow.com/questions/69179230/unable-to-use-swiper-vue-dependencies-not-found/70755021#70755021)

**Comment by slothentic** [comment]
Working for me ^7
```
import 'swiper/css/bundle'
```

**Comment by pdfco1999** [comment]
use it as plugin, that's work.

**Comment by AbdoliMR** [comment]
downgrade it to the 3.1.3 version in Nuxt.

**Comment by jianingguo** [comment]
删除node_modules
删除package-lock.json
重新npm install
如果还不能运行并提示让安装某个插件，请检查插件是否有升级，package.json中版本是否有修改

比如e-icon-picker从1.0.14升级到1.1.7之后
e-icon-picker/dist/index.css要改为
e-icon-picker/lib/index.css
