### ISSUE TITLE
If i use SSR swiper in a component like : 

### ISSUE THREAD

**Issue by raloeasy** [surmon-china/vue-awesome-swiper#572]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### What is actually happening?

**Comment by raloeasy** [comment]
I use the swiper in a component in SSR mode :
<div v-swiper:info="infoSwiperOption" >
When i try to call console.log(this.info) in mounted method of component the console show me undefined, case there isn't a reference with the swiper.

**Comment by NieHang** [comment]
in mounted function
```
this.$nextTick(() => {
console.log(this.info)
})
```

**Comment by horshechnyk** [comment]
mounted() {
  console.log(this.$refs.mySwiper);
}

**Comment by surmon-china** [comment]
[Read here](https://github.com/surmon-china/surmon-china.github.io/tree/source/projects/vue-awesome-swiper/nuxt).
