### ISSUE TITLE
iOS input bug

### ISSUE THREAD

**Issue by jizx** [surmon-china/vue-awesome-swiper#573]
## iOS mobile bug

1. 移动端H5开发在iOS系统下，整屏翻页，输入框不在首屏的话，在某些系统版本下（目前发现，iPhone7 13.1.2，iPhone8 13.1.3）获得焦点以后会出现不显示光标的问题

**Comment by surmon-china** [comment]
这类具体业务问题请不要再提了，即便是 Swiper 本身也是不欢迎的。
