### ISSUE TITLE
Auto slide with timer

### ISSUE THREAD

**Issue by Redani** [surmon-china/vue-awesome-swiper#58]
Hi, and thanks a lot for this lovely slider :)

I would like to ask you if it's possible to auto-play the slide and also show a progress bar for the timer.

Thanks in advance

**Comment by surmon-china** [comment]
Yes, the component depends on the swiper plugin, swiper all the configuration items are available in the component, swiper provides automatic playback and activities of the subscript api, it is recommended that you refer to the official api document to achieve the needs of the use of happy!

[zh docs](http://www.swiper.com.cn/api/index.html)

[en docs](http://idangero.us/swiper/api/)
