### ISSUE TITLE
如何添加mask-image属性

### ISSUE THREAD

**Issue by DJAlejandro** [surmon-china/vue-awesome-swiper#580]
想使用mask-image这个css3属性为轮播图侧边添加遮罩效果，但是发现把这个属性添加在.swiper-container时，里面的左右按钮也会被遮罩。
```
.play-list-item /deep/ .swiper-container{
  mask-size: 100%;
  mask-position: 0;
  mask-image: linear-gradient(
    90deg,
    transparent 0,
    #000 150px,
    #000 90%,
    transparent
  );
}
```
![小Q截图-20191124155659](https://user-images.githubusercontent.com/14656317/69491669-1b78a080-0ed3-11ea-8b1d-1ae35f0b04a1.png)

这个属性添加在.swiper-wrapper时，轮播到第二页时，所有轮播项被遮罩

```
.play-list-item /deep/ .swiper-wrapper {
  mask-size: 100%;
  mask-position: 0;
  mask-image: linear-gradient(
    90deg,
    transparent 0,
    #000 150px,
    #000 90%,
    transparent
  );
}
```

![小Q截图-20191124155607](https://user-images.githubusercontent.com/14656317/69491679-2f240700-0ed3-11ea-9e45-85465f4523ec.png)

希望实现的效果是在轮播项左右有固定的遮罩效果，左右切换按钮不被遮罩，效果如下

![小Q截图-20191124160121](https://user-images.githubusercontent.com/14656317/69491721-e3be2880-0ed3-11ea-8d54-badfc38fbf8e.png)

**Comment by surmon-china** [comment]
建议：
1. 尽量控制（最）外围容器
2. 使用 `z-index` 分别控制 `mask` 和 `pagination`
