### ISSUE TITLE
How to turn off grab and slide to right & left sliding effect! And use only carousel controller buttons on the left and right!

### ISSUE THREAD

**Issue by N1Mirzo** [surmon-china/vue-awesome-swiper#584]
Can you help me with this problem: 

![image](https://user-images.githubusercontent.com/55438076/69617372-ee0a2f00-1059-11ea-9f0a-e27ba86dcefe.png)

**Comment by d4ny0** [comment]
Pretty sure this isn't the right place for it. But it basically says everything you need in your console. you don't have access to the "<md-card-media>" component when you call it. so you should check if it is registered correctly

**Comment by surmon-china** [comment]
Remove `<md-*>` components.
