### ISSUE TITLE
一个页面多个swiper，变现不同，第二个没有效果了，而且后面的参数配置会影响上一个的配置

### ISSUE THREAD

**Issue by daweiyong** [surmon-china/vue-awesome-swiper#585]
`
"<template>
  <div>
    <swiper `:options="swiperOption">`
      <swiper-slide v-for="(slide, index) in swiperList" :key="index">
        <img :src="slide.src" alt="图片">
      </swiper-slide>
      <div slot="pagination" class="swiper-pagination" />
    </swiper>
  </div>
</template>
<script>
export default {
  name: 'CdySwiper',
  props: {
    swiperOption: {
      type: Object,
      default: () => { return {} }
    },
    swiperList: {
      type: [Array],
      default: () => { return [] },
      required: true
    }
  },
  data() {
    return {

    }
  },
  mounted() {

  },
  methods: {

  }
}
</script>
<style lang="scss" scoped>
.swiper-container {
  height: 20vh;
  .swiper-slide {
    width: 100%;
    overflow: hidden;
    img {
      width: calc(100% + 10vw);
      vertical-align: middle;
      transform: translateX(-10vw);
      opacity: 0.5;
    }
  }
  .animated {
    img {
      opacity: 1;
      transform: translateX(0);
      transition:all 3s;
    }
  }
  .swiper-pagination {
    text-align: right;
  }
}
</style>
//引用的模块
<template>
  <div class="about">
    <swiper :swiper-list="swiperList1" :swiper-option="swiperOption1" />
    <swiper :swiper-list="swiperList2" :swiper-option="swiperOption2" />
  </div>
</template>
<script>
import swiper from '@/components/swiper'
import { addClass, removeClass } from '@/utils/index'
export default {
  components: {
    swiper
  },
  data() {
    return {
      swiperOption1: {
        speed: 200,
        loop: true,
        autoplayDisableOnInteraction: false,
        preventLinksPropagation: true,
        effect: 'fade',
        autoplay: {
          delay: 5000 // 5秒切换一次
        },
        pagination: {
          el: '.swiper-pagination'
        },
        on: {
          slideChangeTransitionStart() {
            removeClass(document.querySelector('.swiper-slide-active'), 'animated')
          },
          slideChangeTransitionEnd() {
            addClass(document.querySelector('.swiper-slide-active'), 'animated')
          }
        }
      },
      swiperList1: [
        {
          src: 'http://m.youmeitu.com/Upload/20190415/1555306123444903.jpg'
        }, {
          src: 'http://img95.699pic.com/photo/50055/5642.jpg_wh300.jpg'
        }, {
          src: 'https://pic1.zhimg.com/v2-3b4fc7e3a1195a081d0259246c38debc_1200x500.jpg'
        }, {
          src: 'http://img95.699pic.com/photo/50062/8783.jpg_wh300.jpg'
        }
      ],
      swiperOption2: {
        speed: 200,
        loop: true,
        autoplayDisableOnInteraction: false,
        preventLinksPropagation: true,
        effect: 'fade',
        autoplay: {
          delay: 3000 // 3秒切换一次
        },
        pagination: {
          el: '.swiper-pagination'
        },
        on: {
          slideChangeTransitionStart() {
            removeClass(document.querySelector('.swiper-slide-active'), 'animated')
          },
          slideChangeTransitionEnd() {
            addClass(document.querySelector('.swiper-slide-active'), 'animated')
          }
        }
      },
      swiperList2: [
        {
          src: 'https://pic1.zhimg.com/v2-3b4fc7e3a1195a081d0259246c38debc_1200x500.jpg'
        }, {
          src: 'http://img95.699pic.com/photo/50062/8783.jpg_wh300.jpg'
        }
      ]
    }
  }
}
`</script>"``

**Comment by yixinagqingyuan** [comment]
大佬，我也遇到了同样的问题，解决了吗

**Comment by daweiyong** [comment]
@yixinagqingyuan 解决了，用了原生的，自己的封装了一个组件，个人也是看到了一些网上的例子，要求是声明对象的时候，要给不同的根容器
<!--组建部分
<template>
  <div>
    <div :class="[container,contentNo]">
      <div class="swiper-wrapper">
        <div v-for="(item,index) in swiperList" :key="index" class="swiper-slide">
          <img :src="item.src" alt="图片">
        </div>
      </div>
      <div class="swiper-pagination" />
    </div>
  </div>
</template>
<script>
import Swiper from 'swiper'
export default {
  name: 'CdySwiper',
  props: {
    swiperOption: {
      type: Object,
      default: () => { return {} }
    },
    swiperList: {
      type: [Array],
      default: () => { return [] },
      required: true
    },
    contentNo: {
      type: [Number, String],
      default: () => { return '' },
      required: true
    }

  },
  data() {
    return {
      container: 'swiper-container',
      swiperArr: [] // 所有swiper的列表
    }
  },
  watch: {
    swiperList: {
      handler(newVal, oldVal) {
        if (newVal.length) {
          this.$nextTick(() => {
            setTimeout(() => {
              this.swiperInit()
            }, 100)
          })
        }
      },
      deep: true,
      immediate: true
    }
  },
  mounted() {

  },
  destroyed() {
    console.log('销毁了')
    this.swiperArr.map(res => {
      res.destroy(true, false)// 第一个参数是否销毁swiper对象，第二个参数是否销样式
    })
  },
  methods: {
    swiperInit() {
      this.swiperArr.push(new Swiper(document.querySelector(`.${this.contentNo}`), this.swiperOption))
    }
  }
}
</script>
<style lang="scss">
@import 'swiper/dist/css/swiper.min.css';
.swiper-container {
  height: 30vh;
  .swiper-slide {
    width: 100%;
    overflow: hidden;
    img {
      width: calc(100% + 10vw);
      vertical-align: middle;
      transform:translateX(-10vw);
      opacity: 0.5;
    }
  }
  .animated {
    img {
      opacity: 1;
      transform:translateX(0);
      transition:all 3s;
    }
  }
  .swiper-pagination {
    text-align: right;
  }
}
</style>
--!>


引用部分

<template>
  <div class="about">
    <swiper content-no="swiper-container1" :swiper-list="swiperList1" :swiper-option="swiperOption1" />
    <swiper content-no="swiper-container2" :swiper-list="swiperList2" :swiper-option="swiperOption2" />
    <swiper content-no="swiper-container3" :swiper-list="swiperList3" :swiper-option="swiperOption3" />
  </div>
</template>
<script>
import swiper from '@/components/swiper'
import { addClass, removeClass } from '@/utils/index'
export default {
  components: {
    swiper
  },
  data() {
    return {
      swiperOption1: {
        speed: 200,
        loop: true,
        autoplayDisableOnInteraction: false,
        preventLinksPropagation: true,
        effect: 'fade',
        autoplay: {
          delay: 10000 // 5秒切换一次
        },
        pagination: {
          el: '.swiper-container1 .swiper-pagination'
        },
        on: {
          slideChangeTransitionStart() {
            removeClass(document.querySelector('.swiper-container1 .swiper-slide-active'), 'animated')
          },
          slideChangeTransitionEnd() {
            addClass(document.querySelector('.swiper-container1 .swiper-slide-active'), 'animated')
          }
        }
      },
      swiperList1: [
        {
          src: 'http://m.youmeitu.com/Upload/20190415/1555306123444903.jpg'
        }, {
          src: 'http://img95.699pic.com/photo/50055/5642.jpg_wh300.jpg'
        }, {
          src: 'https://pic1.zhimg.com/v2-3b4fc7e3a1195a081d0259246c38debc_1200x500.jpg'
        }, {
          src: 'http://img95.699pic.com/photo/50062/8783.jpg_wh300.jpg'
        }
      ],
      swiperOption2: {
        speed: 400,
        loop: true,
        autoplayDisableOnInteraction: false,
        preventLinksPropagation: true,
        effect: 'fade',
        autoplay: {
          delay: 3000 // 3秒切换一次
        },
        pagination: {
          el: '.swiper-container2 .swiper-pagination'
        },
        on: {
          slideChangeTransitionStart() {
            removeClass(document.querySelector('.swiper-container2 .swiper-slide-active'), 'animated')
          },
          slideChangeTransitionEnd() {
            addClass(document.querySelector('.swiper-container2 .swiper-slide-active'), 'animated')
          }
        }
      },
      swiperList2: [
        {
          src: 'http://img95.699pic.com/photo/50055/5642.jpg_wh300.jpg'
        }, {
          src: 'https://pic1.zhimg.com/v2-3b4fc7e3a1195a081d0259246c38debc_1200x500.jpg'
        }
      ],
      swiperOption3: {
        speed: 400,
        loop: true,
        autoplayDisableOnInteraction: false,
        preventLinksPropagation: true,
        effect: 'fade',
        autoplay: {
          delay: 5000 // 5秒切换一次
        },
        pagination: {
          el: '.swiper-container3 .swiper-pagination'
        },
        on: {
          slideChangeTransitionStart() {
            removeClass(document.querySelector('.swiper-container3 .swiper-slide-active'), 'animated')
          },
          slideChangeTransitionEnd() {
            addClass(document.querySelector('.swiper-container3 .swiper-slide-active'), 'animated')
          }
        }
      },
      swiperList3: [
        {
          src: 'https://pic1.zhimg.com/v2-3b4fc7e3a1195a081d0259246c38debc_1200x500.jpg'
        }, {
          src: 'http://img95.699pic.com/photo/50062/8783.jpg_wh300.jpg'
        }
      ]
    }
  }
}
</script>
我的里面加了一些特效，所有有增加和减少class来完成的，不需要可以去掉，希望可以帮助到你

**Comment by yixinagqingyuan** [comment]
用了原生的swiper？
