### ISSUE TITLE
I got error "Can not read property of undefined" but swiper works. Can I know What I missed?

### ISSUE THREAD

**Issue by parkyh1974** [surmon-china/vue-awesome-swiper#590]
#### Vue.js version and component version

I'm using Vue.js 2.6.1  and awsome swiper 3.1.3

#### Situation

This is code works well.

              <transition :name="routerTransition" mode="out-in">
                <swiper :options="swiperOption"  :ref="reportSwiper" >
                  <swiper-slide v-for="date in DateList" v-bind:key="date">
                    <router-view v-bind:date-info="date" ></router-view>
                  </swiper-slide>                                  
                </swiper>
              </transition>

And I wanted to get active index. So I used computed.

		  computed: {
			currentSwiperDate() {
			  const swiper = this.$refs.reportSwiper.swiper;
			  if (!swiper)
			  {
				this.returnCurrent(0);
				return;
			  }
			  const index = swiper.realIndex;
			  this.returnCurrent(index);
			},
		}

But I get this error message.
[Vue warn]: Error in render: "TypeError: Cannot read property 'swiper' of undefined"

#### What is Expected?      

I want to know what I missed. I enlisted reference reportSwiper and accessed. 
Why swiped is undefined? what should I do to get activeindex?

#### What is actually happening?

It does not works. I get error.
[Vue warn]: Error in render: "TypeError: Cannot read property 'swiper' of undefined"

**Comment by marcelo2605** [comment]
@parkyh1974 Same error here. Did you get a solution?

**Comment by Griffin23** [comment]
use `ref` instead of `:ref`

**Comment by surmon-china** [comment]
@Griffin23 Yes.

`:ref="contextData"`

`ref="string"`
