### ISSUE TITLE
点击左右边的侧边栏 发现有个橘黄色的框 隔段时间就没有了 但是这个很难看 找了样式没有focus 情况下的样式 用Border也替换不了

### ISSUE THREAD

**Issue by yehoan** [surmon-china/vue-awesome-swiper#600]
### 中文用户注意：

1. 尽量用英文描述你的 issue
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，必须仔细阅读 REMADE.md + 在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决
5. **如果无法做到提一个合格、优秀的问题，则问题会被 close + block**

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/39epgLj0/

#### What is actually happening?

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/72316448-8ab97800-366c-11ea-9cb4-ff0e4a54ba28.png)

**Comment by yehoan** [comment]
这个橘黄色的框  不知道从哪里来的

**Comment by yehoan** [comment]
请帮忙协助一下 谢谢

**Comment by AnnamayYan** [comment]
> 请帮忙协助一下 谢谢

黄框是outline，之前遇到过去掉了
