### ISSUE TITLE
[help] Swiper on click event

### ISSUE THREAD

**Issue by d4sein** [surmon-china/vue-awesome-swiper#604]
Hi, I'm trying to call a Vue method on click event and would like to pass a variable `image`, so that I can make changes to it and update the component with the `computed` property. The problem I'm having is that I can't handle these click events directly with Vue, and handling them with the Swiper's click event doesn't let me pass the `image` variable. I've read the docs and searched it, but couldn't find anything.

**Comment by surmon-china** [comment]
v4.0.0 was released!

Maybe you can use the [`@click-slide`](https://github.com/surmon-china/vue-awesome-swiper#swiper-component-api) api and `dynamic data` to achieve the goal.
