### ISSUE TITLE
Virtual slides not updating after updating items

### ISSUE THREAD

**Issue by bgondy** [surmon-china/vue-awesome-swiper#609]
#### Vue.js version and component version

```js
{
  "dependencies": {
    // ...
    "vue": "^2.6.11",
    "vue-awesome-swiper": "^3.1.3",
    // ...
  }
}
```

#### Steps to reproduce

Let's say I have a slider with hundreds of items. To avoid performance hits, I managed to set up virtual slides with an external component by following the official Swiper documentation (https://swiperjs.com/api/#virtual-example) and the example in this repo. So far so good.

My list of items can also be filtered by category and I need to keep only matching items in the slider. It seems there is no reactivity when I update the list of slides.

#### What is Expected?    

I'm using a computed property to build swiper options and I was expecting the slider to be updated.  

#### What is actually happening?

Items in the slider are not updated.

As a workaround, I managed to get it work by using a watcher on the `items` property and to update virtual slides manually but I'm not aware of possible side-effects.

After digging into `Swiper.vue`, this may not be related to vue-awesome-swiper but to Swiper itself. I'm not even sure this is a bug. Please let me know.

Here is my (simplified) component if it can help : 

```vue
<template>
  <div>
    <button ref="prevEl" type="button">
      <slot name="nav-prev"></slot>
    </button>

    <swiper :options="swiperOptions" ref="slider" v-if="isSliderReady">
      <swiper-slide
        :key="index"
        :style="{ left: `${virtualData.offset}px` }"
        v-for="(item, index) in virtualData.slides"
      >
        <slot :item="item"></slot>
      </swiper-slide>
    </swiper>

    <button ref="nextEl" type="button">
      <slot name="nav-next"></slot>
    </button>
  </div>
</template>

<script>
import { swiper, swiperSlide } from 'vue-awesome-swiper';

export default {
  name: 'ConfiguratorSlider',
  components: { swiper, swiperSlide },
  props: {
    items: { type: Array, default: () => [] },
    sliderOptions: { type: Object, default: () => ({}) },
  },
  data() {
    return {
      isSliderReady: false,
      virtualData: { slides: [] },
    };
  },
  computed: {
    swiperOptions() {
      return {
        navigation: {
          // ...
        },
        virtual: {
          // I was expecting slides to be updated when `this.items` is updated
          slides: this.items,
          cache: false,
          renderExternal: data => {
            console.log(data);

            this.virtualData = data;
          },
        },
        ...this.sliderOptions,
      };
    },
  },
  watch: {
    items(items) {
      const slider = this.$refs.slider;
      const swiperInstance = slider.swiper;

      // Remove manually old items
      swiperInstance.virtual.removeAllSlides();
      // Add new items
      swiperInstance.virtual.appendSlide(items);
    },
  },
  mounted() {
    this.swiperNavPrev = this.$refs.prevEl || null;
    this.swiperNavNext = this.$refs.nextEl || null;
    this.isSliderReady = true;
  },
};
</script>
```

Thank you for your amazing work BTW.

**Comment by surmon-china** [comment]
I will try tonight.

**Comment by surmon-china** [comment]
When the `Swiper component`  updated, it cannot be inferred that the update comes from the `content `or `swiperOption`, so swiper will not be re-instantiated.
 
so it cannot be automatically updated according to the configuration change, but manually operating the `swiper instance` is a good way.

After my testing, the related methods of `swiperInstance.virtual.[methods]` are feasible.

If some content is not updated as expected,
you can try to manually execute `this.$refs.[SwiperRefName].update`.
