### ISSUE TITLE
在服务器渲染下，要怎么用呢

### ISSUE THREAD

**Issue by sujinw** [surmon-china/vue-awesome-swiper#61]
用普通的引入的话，swiper本身肯定会出现window的问题，要怎样绕过，这些代码呢

**Comment by surmon-china** [comment]
nuxt.js的话可以先参考这段代码

[carrousel.vue](https://github.com/surmon-china/surmon.me/blob/master/components/article/archive/carrousel.vue)

[announcement.vue](https://github.com/surmon-china/surmon.me/blob/master/components/article/archive/announcement.vue)

**Comment by surmon-china** [comment]
问题合并至 #12
