### ISSUE TITLE
IE 打开演示还是报 缺少 ':'

### ISSUE THREAD

**Issue by jy159874** [surmon-china/vue-awesome-swiper#612]
IE 11 打开 这个地址 https://github.surmon.me/vue-awesome-swiper/  还是报 SCRIPT1003: 缺少 ':'           install(n) 
Vue 项目中一样的错误，3.1.3 版怎么解决，有知道的朋友吗帮下忙啊，感激不尽

**Comment by jy159874** [comment]
在组件内去 用就正常了，  Vue.use(VueAwesomeSwiper) 这样就 错误

**Comment by P-Mz** [comment]
> 在组件内去用就正常了，Vue.use（VueAwesomeSwiper）这样就错误

应该是没有提供 install 方法所以不能使用 Vue.use

**Comment by surmon-china** [comment]
v4.0.0 was released!

如果可以，请贴出 IE 下错误的堆栈详情。
