### ISSUE TITLE
How i can destroy and reinit slider?

### ISSUE THREAD

**Issue by Venegrad** [surmon-china/vue-awesome-swiper#615]
I need use slider, only on mobile devices. How i can destroy, and after reinit slider?
Im trying destroy ```this.sliderZimmer.destroy(true, true)``` and slider destroying fine. But if after i try to init ``` this.sliderZimmer.init() ```. Script give me an error. 
![image](https://user-images.githubusercontent.com/9676703/76923658-b101cb00-68dc-11ea-885b-5d8728e6bab0.png)

**Comment by ipa1981** [comment]
Having exactly the same. Supporting this Issue.

**Comment by surmon-china** [comment]
The author of Swiper has stated Swiper does not support this action:

["You need to recreate instance with calling new Swiper, swiper.init() won't have effect after destroying"](https://github.com/nolimits4web/swiper/issues/3484#issuecomment-593441308)

I recommend using `v-if` to control the destruction and initialization of Swiper inside the component.

e.g.:

```html
<swiper v-if="renderSwiper">
```

```ts
shouldBeDestroy() {
  this.renderSwiper = false
},
shouldBeWork() {
  this.renderSwiper = true
}
```

**Comment by ipa1981** [comment]
@surmon-china The problem here is when slides load dynamically and need to run initialization manually, then user can change. `v-if` doesn't work in this case. Any suggestions how to deal with it?

**Comment by manwithawp** [comment]
> @surmon-china The problem here is when slides load dynamically and need to run initialization manually. `v-if` doesn't work in this case. Any suggestions how to deal with it?

Hello! did U check this?

**Comment by TakCastel** [comment]
Destroying the swiper doesn't mean making it disappear, we could still need to display the slides; without the swiper behavior.
