### ISSUE TITLE
[Bug] SSR is not working after switching from v.3 to v.4

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [surmon-china/vue-awesome-swiper#619]
I've decided to upgrade my project from Swiper v.3 to v.4.0.4
After that I got several issues.
I use swiper in Nuxt so I'm adding swiper to my project like so:
```
<div class="swiper"v-swiper:mySwiper="swiperOptions">
...

created() {
      if (process.browser) {
        const VueAwesomeSwiper = require('vue-awesome-swiper/dist/ssr')
        Vue.use(VueAwesomeSwiper)
      }
    },

@import 'node_modules/swiper/dist/css/swiper.min.css';
```
Problem 1:
- `swiper.min.css` is not found since swiper dependency is no longer installed. For some reason it's specified as peer dependency in `vue-awesome-swiper` package.json and it is no longer downloaded during dependency install process. 
Problem 2:
- `vue-awesome-swiper/dist/ssr` is gone and now I don't understand how `vue-awesome-swiper` should be used inside Nuxt, no info in the docs I could find.

@surmon-china Please, could you release a proper upgrade guide? Examples that were present in version 3 are also gone for some reason which makes setting up a project even harder. Those should be returned, I guess.

**Comment by surmon-china** [comment]
@AndrewBogdanovTSS 

Quick upgrade guide:

1. `npm i swiper vue-awesome-swiper --save`

2.
```
<div class="swiper"v-swiper:mySwiper="swiperOptions">
...

created() {
  if (process.browser) {
    const VueAwesomeSwiper = require('vue-awesome-swiper')
    Vue.use(VueAwesomeSwiper)
  }
},

@import 'node_modules/swiper/css/swiper.css';
```

**Comment by surmon-china** [comment]
@AndrewBogdanovTSS 

All example code is the same as before, the example code of nuxt [is here](https://github.com/surmon-china/surmon-china.github.io/tree/source/projects/vue-awesome-swiper/nuxt).

**Comment by AndrewBogdanovTSS** [comment]
@surmon-china thanks a lot for the response. This was exactly the information I was looking for! Closing the issue

**Comment by 1297947244** [comment]
Demo link 404
