### ISSUE TITLE
Does not support webapck1.14.0

### ISSUE THREAD

**Issue by haoxl3** [surmon-china/vue-awesome-swiper#62]
when I npm install vue-awesome-swiper, but fail to install.  I don't want to upgrade  the webpack version,If there were any other method. Error message is as follows:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.1.1
npm WARN extract-text-webpack-plugin@2.1.0 requires a peer of webpack@^2.2.0 but
 none was installed.

**Comment by surmon-china** [comment]
Try using the `--no-optional` flag as a workaround.

`npm update --no-optional`
