### ISSUE TITLE
请问我使用webpack打包后发现本插件引用的swiper体积很大，请问有没有好的解决办法让打完的包可以体积变小些？非常感谢

### ISSUE THREAD

**Issue by 1409004379** [surmon-china/vue-awesome-swiper#621]
### 中文用户注意：
1. 尽量用英文描述你的 Issue，你的问题是面向世界的
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，务必仔细阅读 README.md；在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/surmon/kLtj6h3p/

**Comment by surmon-china** [comment]
有，最近会有一个新版本，可解决此问题。

**Comment by surmon-china** [comment]
Upgrade to v4.1.0 and read [custom-build-with-swiper](https://github.com/surmon-china/vue-awesome-swiper#custom-build-with-swiper).

(:

**Comment by 1409004379** [comment]
thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Surmon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月29日(星期天) 晚上11:02
收件人:&nbsp;"surmon-china/vue-awesome-swiper"<vue-awesome-swiper@noreply.github.com&gt;;
抄送:&nbsp;"YOU 龍"<1409004379@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [surmon-china/vue-awesome-swiper] 请问我使用webpack打包后发现本插件引用的swiper体积很大，请问有没有好的解决办法让打完的包可以体积变小些？非常感谢 (#621)





 
Upgrade to v4.1.0 and read custom-build-with-swiper.
 
(:
