### ISSUE TITLE
使用4.0.4版本对于低版本安卓会报错

### ISSUE THREAD

**Issue by juice157** [surmon-china/vue-awesome-swiper#625]
使用版本：
"vue-awesome-swiper": 4.0.4
"vue": "2.6.11",
"swiper": "5.3.6"
安卓版本：5.0
机型：华为P8

报错内容：
Uncaught SyntaxError: Use of const in strict mode.

我现在暂时将vue-awesome-swiper版本降为3.1.3解决问题。

未来4.X版本是否还会对这种低版本的安卓机型进行兼容呢？

**Comment by surmon-china** [comment]
1. Swiper 4/5 的 API 是兼容的，你可以单独把 Swiper 降级为 v4.x
2. vue-awesome-swiper 目标代码中不存在 const，是 Swiper 5.x 不再兼容部分浏览器

**Comment by juice157** [comment]
十分感谢
