### ISSUE TITLE
It doesn't work on iOS9 , when upgrading from 3.x to 4.x 

### ISSUE THREAD

**Issue by zhanyuzhang** [surmon-china/vue-awesome-swiper#626]
on iOS9 , it works perfectly  with vue-awesome-swiper@3.1.3 , but when upgrading  to 4.0.4  it throws error as ` Unexpected keyword 'const'. Const declarations are not supported in strict mode. `

**Comment by surmon-china** [comment]
Merged to https://github.com/surmon-china/vue-awesome-swiper/issues/625#issuecomment-606569371
