### ISSUE TITLE
How to initialize swiper without swiper-slide class

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [surmon-china/vue-awesome-swiper#629]
I use directive style approach to initialize the swiper, but the swiper is only working if I apply `swiper-slide` class to the swipable elements. That sets a limitation to what can be passed to swiper as children elements. Is there any way to tell swiper what to slide by reference or in some other way?

**Comment by surmon-china** [comment]
[API Namespace  `slideClass `](https://swiperjs.com/api/)

e.g.

```html
<div class="swiper-container">
  <div class="swiper-wrapper">
    <div class="my-slide">slider 1</div>
    <div class="my-slide">slider 2</div>
    <div class="my-slide">slider 3</div>
  </div>
</div>
```

```js
swiperOptions: {
  slideClass : 'my-slide'
}
```

**Comment by AndrewBogdanovTSS** [comment]
Hm...ok, but my question was more about whether I can use another mechanism of getting items rather than specifying a class?
I would like to iterate items in the slider outside the component and pass generated code inside swiper via slots. With the current logic, everyone that will use swiper should always specify a class on the generated markup, so I would like to somehow escape this limitation
