### ISSUE TITLE
"mySwiper.pagination.bullets.length" bullets确实是存在的，但是一旦读取bullets的length属性就一直是0

### ISSUE THREAD

**Issue by Aspark1996** [surmon-china/vue-awesome-swiper#631]
```javascript
//鼠标滑过pagination控制swiper切换
_paginationMouseOver() {
console.log(this.$swiper.pagination)  
console.log(this.$swiper.pagination.bullets)
for(let i=0;i<this.$swiper.pagination.bullets.length;i++){
	this.$swiper.pagination.bullets[i].onmouseover=function(){
	   this.click()
	}
  }
}
```
for循环一直执行不了，于是打印了下bullets，发现其属性length是0，但是看pagination里bullets的length确不是0.....

**Comment by surmon-china** [comment]
1. 控制台打印的数据如果是引用类型，则 "确实是存在的" 只代表数据的最新状态，而不是 "运行时状态"。
2. 不建议这样的方式控制 Swiper，而是采用 “外部自定义pagination 元素 + 调用 swiper 实例的方法” 来做到，类似可参考 [此处](https://github.com/surmon-china/vue-awesome-swiper/issues/628#issuecomment-611452830)
