### ISSUE TITLE
Can we place slides between buttons?

### ISSUE THREAD

**Issue by OtabekSadiridinov** [surmon-china/vue-awesome-swiper#635]
**Can we place slides between buttons?**
_I am nearly making a website carousel and want the button to be out of the slides_
_And tried many way but couldn't. And tried with .swiper-container class too. But failure.
Please add btn-out="true/false" option too. It is really many people want. And I am too.
Have a great day Surmon._

**Comment by surmon-china** [comment]
@OtabekSadiridinov [here](https://github.com/surmon-china/vue-awesome-swiper/issues/628#issuecomment-611452830). maybe help you

**Comment by OtabekSadiridinov** [comment]
Ok I am closing issue it helped me. Thank you very much.
