### ISSUE TITLE
点击轮播图之外的tab栏，轮播图会重新初始化

### ISSUE THREAD

**Issue by JOYCEQL** [surmon-china/vue-awesome-swiper#636]
### 中文用户注意：
1. 尽量用英文描述你的 Issue，你的问题是面向世界的
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，务必仔细阅读 README.md；在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决

### BUG REPORT TEMPLATE
点击tab栏切换区域的显示隐藏时，轮播图部分会重新初始化，而tab栏和轮播图是不相干的两部分DOM，左侧轮播图部分和右侧tab栏分别有一个变量（布尔值）来控制是否隐藏。
#### Vue.js version and component version
vue2.5
#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/surmon/kLtj6h3p/

#### What is Expected?
需要的效果是点击tab栏轮播图不会被初始化

**Comment by surmon-china** [comment]
这个需求不合理，几乎所有与 UI 渲染有关的库或工具都需假设一个前提：UI 可见、DOM 可交互；
如 echarts，如果初始化时目标元素被隐藏或没有有效的宽高，则会初始化失败；
你应该尝试去理解，如果你是 Swiper 的设计者，当 Swiper 的父元素被 `display: none`，Swiper 拿到的容器尺寸为 `0`，它如何去计算各种各样的 “分片” “自动高度” ...

“需要的效果是点击tab栏轮播图不会被初始化” 可以做到，但你需要解决的是 “保证类 Swiper 组件的渲染周期与外部环境同步”。

**Comment by surmon-china** [comment]
可能是 Tab 引起了父组件的重新渲染，同时引起了 Swiper 的重新渲染，这个问题重在测试，测试 rerender 的过程，测试 Parent、Swiper、Tab 之间的数据关系，需要自己动手。

如果要禁止自动更新，Swiper 组件提供有 `:auto-update` props，可以传递 `false` 以禁用。
