### ISSUE TITLE
当页面使用{{}}绑定数据时，而这个数据不断变化，swiper会不断渲染，且拖动未完成就会被恢复默认

### ISSUE THREAD

**Issue by luchanan** [surmon-china/vue-awesome-swiper#637]
这个案例可以复现：
先点click， 再拖动一下，看效果，也可以看看elment的变化
https://codesandbox.io/s/epic-swanson-m61zh?file=/src/App.vue

**Comment by surmon-china** [comment]
1. 不是 Swiper 在 rerender，而是 Swiper 的兄弟元素 `{{ xxx }}` 引起了整个组件的 rerender
2. Swiper 内部使用了 Vue 的 `updated ` API，以对数据更新做出实时 rerender，但其并没有能力知道 `updated` 是由什么原因引起的
3. 如果你的 Swiper 不存在动态内容，则可以使用 props `:auto-update="false"` 以关闭自动更新

关闭后，就不会 “不断渲染” 了，[测试代码在此](https://codesandbox.io/s/quirky-mayer-cn9bz)。

**Comment by luchanan** [comment]
thanks

**Comment by SantiagoFan** [comment]
如果我的options 参数也在动态变化，如何实现自定渲染 Swiper

**Comment by Yubiao-Li** [comment]
> 1. 不是 Swiper 在 rerender，而是 Swiper 的兄弟元素 `{{ xxx }}` 引起了整个组件的 rerender
> 2. Swiper 内部使用了 Vue 的 `updated ` API，以对数据更新做出实时 rerender，但其并没有能力知道 `updated` 是由什么原因引起的
> 3. 如果你的 Swiper 不存在动态内容，则可以使用 props `:auto-update="false"` 以关闭自动更新
> 
> 关闭后，就不会 “不断渲染” 了，[测试代码在此](https://codesandbox.io/s/quirky-mayer-cn9bz)。

但是我的页面存在动态内容，这时候应该怎么样避免这种情况呢
