### ISSUE TITLE
window is undefined with SSR build with vue-hackernews-2.0 

### ISSUE THREAD

**Issue by liuchonggao** [surmon-china/vue-awesome-swiper#64]
I import he  `vue-awesome-swiper/ssr` in `app.js` and use it with `Vue.use`.
But, when I use swiper in a components throw a exception that **window is not defined**
So... I make some mistake? How can I use with SSR... Thx~
>[vue-hackernews-2.0](https://github.com/vuejs/vue-hackernews-2.0)

**Comment by surmon-china** [comment]
``` javascript
import Vue from 'vue'

// You need to make sure that you are introducing it in a browser build environment
if (process.BROWSER_BUILD) {
	const VueAwesomeSwiper = require('vue-awesome-swiper/ssr')
	Vue.use(VueAwesomeSwiper)
}
```

**Comment by liuchonggao** [comment]
@surmon-china I know what should I do and I appreciate that you can reply for me.

**Comment by buxinxu** [comment]
i have the same quetion . can you tell me what should i do?
