### ISSUE TITLE
Windows 10, Chrome 81 + IE etc., mousewheel is not working

### ISSUE THREAD

**Issue by ljanecek** [surmon-china/vue-awesome-swiper#647]
On the Windows 10, Chrome 81, mousewheel scroll is not working. It's not possible to scroll to third and other slides.

**Comment by surmon-china** [comment]
![ezgif-6-4a0d6f0bb445](https://user-images.githubusercontent.com/14019524/82009769-cad44a00-96a2-11ea-88a5-3a543b18222a.gif)

**Comment by ljanecek** [comment]
The same problem is here: https://github.com/nolimits4web/swiper/issues/3581#event-3341700917

And fix is also done.

**Comment by isuke01** [comment]
Also the scroll is not working in Mac OS Chrome, Safari, FF etc ...  ;) 
`
swiperOptions: {
          observer: true,
          mousewheelControl: true,
          slidesPerView: 1,
          freeMode: false,
          freeModeSticky: true,
         direction: 'vertical'
}
`

**Comment by BuSSioR** [comment]
@isuke01  Your solution works good enough for most cases, but it "trims" freeMode feature. To use default solution (by which I mean defining wheel in swiper options) you guys need to register swiper class in "custom" way described in `Readme.md` by @surmon-china .

Small example:
```
import Vue from 'vue';
import { Swiper as SwiperClass, Mousewheel } from 'swiper/core';
import getAwesomeSwiper from 'vue-awesome-swiper/dist/exporter';
SwiperClass.use([Mousewheel]);
Vue.use(getAwesomeSwiper(SwiperClass));
```

If you register component this way, scroll works when options provided:
```
{
   mousewheel:true,
   freeMode:true
}

**Comment by MrToxy** [comment]
> @isuke01 Your solution works good enough for most cases, but it "trims" freeMode feature. To use default solution (by which I mean defining wheel in swiper options) you guys need to register swiper class in "custom" way described in `Readme.md` by @surmon-china .
> 
> Small example:
> 
> ```
> import Vue from 'vue';
> import { Swiper as SwiperClass, Mousewheel } from 'swiper/core';
> import getAwesomeSwiper from 'vue-awesome-swiper/dist/exporter';
> SwiperClass.use([Mousewheel]);
> Vue.use(getAwesomeSwiper(SwiperClass));
> ```
> 
> If you register component this way, scroll works when options provided:
> 
> ```
> {
>    mousewheel:true,
>    freeMode:true
> }
> ```

This is far easier solution, thank you
