### ISSUE TITLE
The copied node does't have the event function of the original node

### ISSUE THREAD

**Issue by qqlxxlxx** [surmon-china/vue-awesome-swiper#648]
in the vue-awesome-swiper 4.1.1 version, the copied swiper-slide node does't have the the event function of the original swiper-slide node

```html
<swiper ref="mySwiper" :options="swiperOptions">
  <swiper-slide v-for="(item, index) in list" :key="index" @click.native="fn(index)">
    <img :src="item" />
  </swiper-slide>
</swiper>
```

**the original swiper-slide node**

![image](https://user-images.githubusercontent.com/51897302/82038640-68953c80-96d6-11ea-9e18-8c7b50eead54.png)

**the copied swiper-slide node**

![image](https://user-images.githubusercontent.com/51897302/82038753-98dcdb00-96d6-11ea-9e45-95ccfc9cd10f.png)

**Comment by surmon-china** [comment]
@qqlxxlxx 

Use [`<swiper @click-slide="handleClickSlide" />`](https://github.com/surmon-china/vue-awesome-swiper#swiper-component-api) API please.
