### ISSUE TITLE
how to only dependency a part of swiper module like swiper/core,import all swiper too big

### ISSUE THREAD

**Issue by chaoqunL** [surmon-china/vue-awesome-swiper#666]
i see the package.json below:
"peerDependencies": {
    "swiper": "^5.2.0",
    "vue": "2.x"
  },
looks like need import all swiper modules, which too large

**Comment by AndrewBogdanovTSS** [comment]
https://github.com/surmon-china/vue-awesome-swiper/issues/680#issuecomment-666364812
