### ISSUE TITLE
Swiper starting position indented at 16px

### ISSUE THREAD

**Issue by zababurinsv** [surmon-china/vue-awesome-swiper#673]
Hi.
My init Options

    swiperOption: {
      loop: false,
      autoplay: false,
      slidesPerView: 3,
      centeredSlides: true,
      spaceBetween: 30,
    }

But I need the first slide to be indented at 16px.
if i set `margin-left: 16px`  last slider cut on 16 px.

How can I set the starting position indented at 16px ?

**Comment by zababurinsv** [comment]
I solved this problem then. just saw your comment now

**Comment by AndrewBogdanovTSS** [comment]
@zababurinsv the most reliable way I could find to achieve this was adding a div with a fixed width as the first slide, e.g.:
 ```
 <div class="swiper-wrapper">
      <div style="width: 16px" />
      <div class="swiper-slide" v-for="num in 10" :key="num">
      ...
      </div>    
</div>           
```
You can also add a similar element after the list of slides
