### ISSUE TITLE
How can i create centered carousel with 1 slide per view in loop mode?

### ISSUE THREAD

**Issue by mortezasabihi** [surmon-china/vue-awesome-swiper#675]
Hi

I want to create carousel like this, (1 slider per view in center mode)
![image](https://user-images.githubusercontent.com/35567646/86456144-de14a500-bd36-11ea-8c49-4519ec858796.png)
as you see, Active slide has not 100% width.

This is my template:
```
    <client-only>
      <swiper class="swiper" :options="swiperOption">
        <swiper-slide v-for="(item, index) in gallery" :key="index">
          <b-img :src="item.img" :alt="item.alt | slug" />
        </swiper-slide>
      </swiper>
    </client-only>
```

This is option:
```
      swiperOption: {
        slidesPerView: 1,
        spaceBetween: 18,
        // centeredSlides: true,
        loop: true,
        loopFillGroupWithBlank: false
      },
```

This is style:
```
.swiper-slide {
  width: 70% !important;
  height: 250px;
  color: #fff;

  img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
}
```

This is result:
![image](https://user-images.githubusercontent.com/35567646/86456626-98a4a780-bd37-11ea-8dbe-56cb2f2f9fd7.png)

**Comment by eragon1206** [comment]
import 'swiper/css/swiper.css'

is outdated, use

import 'swiper/swiper-bundle.css';

**Comment by iammertg** [comment]
> import 'swiper/css/swiper.css'
> 
> is outdated, use
> 
> import 'swiper/swiper-bundle.css';

this does not work, can you elaborate?

**Comment by MUMUKSHMEGHWAL** [comment]
> > import 'swiper/css/swiper.css'
> > is outdated, use
> > import 'swiper/swiper-bundle.css';
> 
> this does not work, can you elaborate?

import 'swiper/css/swiper.min.css'

or check in swiper node modules, which css is there. It will depend on your swiper version.
