### ISSUE TITLE
无法修改 wrapperClass 参数

### ISSUE THREAD

**Issue by hoythan** [surmon-china/vue-awesome-swiper#68]
swiper 提供了一个设置 wrapperclass 的api, 但是好像该参数无法通过 vue-awesome-swiper 进行修改?

`
<swiper :options="swiperOption">
    <swiper-slide v-for="(food,index) in foods">
        I'm Slide 1
    </swiper-slide>
    <div class="swiper-pagination"  slot="pagination"></div>
</swiper>
`
配置如下
`
swiperOption: {
    wrapperClass : 'wx-wrapper'
}
`

**Comment by surmon-china** [comment]
我将很快修复此问题。

**Comment by hoythan** [comment]
蛮多自定义 class 都无法使用,例如slideClass ,slideActiveClass
加油么么哒比💗

**Comment by surmon-china** [comment]
升级到v2.4.0呦
