### ISSUE TITLE
No work before my project upgrade to Vue 3.0

### ISSUE THREAD

**Issue by Young-Spark** [surmon-china/vue-awesome-swiper#686]
## Vue.js version and component version
`"vue": "^3.0.0-beta.21",
"vue-awesome-swiper": "^4.1.1"`
#### Reproduction Link
https://gitee.com/young_spark/Travel/tree/new-version

#### Steps to reproduce
Everthing is ok until my project upgrade to Vue 3.0. When I run my project with `npm run serve`, this info appear in the chrome devtools console panel:

> Uncaught TypeError: Vue.extend is not a function 
>     at eval (vue-awesome-swiper.js?7212:410)
>     at eval (vue-awesome-swiper.js?7212:9)
>     at eval (vue-awesome-swiper.js?7212:9)
>     at Object../node_modules/vue-awesome-swiper/dist/vue-awesome-swiper.js (chunk-vendors.js:2177)
>     at __webpack_require__ (app.js:849)
>     at fn (app.js:151)
>     at eval (main.js:14)
>     at Module../src/main.js (app.js:1985)
>     at __webpack_require__ (app.js:849)
>     at fn (app.js:151)

And I found that [Vue 3.0 doesn't have `Vue.extend` anymore](https://github.com/vuejs/vue-next/issues/629).
But vue-awesome-swiper 4.1.1 still use `Vue.extend` function.

#### What is Expected?
Run successfully
#### What is actually happening?
Error occurs

**Comment by mulili** [comment]
I have the same issue

**Comment by IgorHalfeld** [comment]
@Young-Spark @mulili 
It's the responsibility of `vue-awesome-swiper` to adapt the new versions of Vue and not the other way around

**Comment by AndrewBogdanovTSS** [comment]
awesome swiper doesn't support Vue 3. Use official swiper.js plugin https://swiperjs.com/vue/
