### ISSUE TITLE
无法修改 containerModifierClass 参数

### ISSUE THREAD

**Issue by hoythan** [surmon-china/vue-awesome-swiper#69]
这个参数比较重要,如果无法使用该参数,将无法实现全局的自定义.
另外不知如何移除原生的 css 样式,因为在不修改 class 的情况下,很多样式会冲突,导致需要专门写一份样式重置表.

**Comment by surmon-china** [comment]
这个api昨天测试过，是可以正常使用的，所以遇到的问题是？

**Comment by hoythan** [comment]
正常情况下,设置 containerModifierClass 例如
`
containerModifierClass:'demo-swiper-'
`
页面中的
`swiper-container `
会变成
`demo-swiper-container`

**Comment by hoythan** [comment]
还有的用户比如其他的不可定义 swiper- 的地方,使用 containerModifierClass 都可以修改前缀

**Comment by surmon-china** [comment]
``` javascript
return {
     swiperOption: {
          // noSwiping: true,
          // height : window.innerHeight,
          wrapperClass: 'my-wrapper',
          slideClass: 'my-slide',
          slideActiveClass: 'my-slide-active',
          slidePrevClass : 'my-slide-prev',
          // containerModifierClass : 'my-container-',
          containerModifierClass : 'my-container-',
          autoplay: 5000,
          notNextTick: true,
          initialSlide: 1,
          // direction : 'vertical',
          loop: true,
          pagination: '.my-pagination',
          onSlideChangeEnd: (swiper) => {
            console.log('onSlideChangeEnd', swiper.realIndex);
          },
          onTap: (swiper) => {
            console.log('onTap', swiper.realIndex);
          }
        },
        banners: []
}
```

1：官方文档说明了：
可以替换`swiper-container-`前缀，`swiper-container`不被包含，如果你要指定`swiper-container`，可以直接给组件赋予class就可以了，<swiper class="your-class">
但`swiper-container`类是固定的，起码目前是，如果没有这个类，则需要自定义样式

2：目前不存在
> 还有的用户比如其他的不可定义 swiper- 的地方

昨天已经都修复了

**Comment by hoythan** [comment]
先别关…吃饭

**Comment by hoythan** [comment]
噢,官方 js 中的`swiper-container`是在 new 的时候创建的,请问使用 `vue-awesome-swiper`的时候,如何修改这个类名呢

**Comment by hoythan** [comment]
晓得了,这个现在还不能修改对吗~多谢@

**Comment by surmon-china** [comment]
这个属性名，暂时不能修改，如果修改，则这个容器的样式都会丢失，也就意味着需要从0修饰容器的样式；但是可以增加，直接在组件上加`class`就可以啦
