### ISSUE TITLE
No swiper.css

### ISSUE THREAD

**Issue by arthur-fontaine** [surmon-china/vue-awesome-swiper#693]
#### Vue.js version and component version
`@vue/cli`: 4.4.1
`swiper`: 6.0.4
`vue-awesome-swiper`: 4.1.1

#### Reproduction
I think everywhere, just install with `npm install swiper vue-awesome-swiper --save`

#### What is Expected?
No error when compile.

#### What is actually happening?
```
ERROR  Failed to compile with 1 errors

This dependency was not found:

* swiper/css/swiper.css in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/setting-box-carousel/SettingBoxCarousel.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save swiper/css/swiper.css
```
And in `node_modules/swiper/` there isn't any `css`folder.

----------
EDIT:
I found a (temporary?) solution. I use `import 'swiper/swiper-bundle.css'` in my scss file.

**Comment by cynthiawupore** [comment]
+1

**Comment by LJ906** [comment]
+1

**Comment by jufjzq** [comment]
import 'swiper/dist/css/swiper.css'

**Comment by ygj6** [comment]
From the official README document, we can see :
```
Global Registration
import Vue from 'vue'
import VueAwesomeSwiper from 'vue-awesome-swiper'

// import style (>= Swiper 6.x)
import 'swiper/swiper-bundle.css'

// import style (<= Swiper 5.x)
import 'swiper/css/swiper.css'

Vue.use(VueAwesomeSwiper, /* { default options with global component } */)
Local Registration
import { Swiper, SwiperSlide, directive } from 'vue-awesome-swiper'

// import style (>= Swiper 6.x)
import 'swiper/swiper-bundle.css'

// import style (<= Swiper 5.x)
import 'swiper/css/swiper.css'

export default {
  components: {
    Swiper,
    SwiperSlide
  },
  directives: {
    swiper: directive
  }
}
```

**Comment by AndrewBogdanovTSS** [comment]
@arthur-fontaine it's not a temporal solution, it's in fact how you should use it if you want to target Swiper v.6

**Comment by Charlie50503** [comment]
please update dos
from
`import 'swiper/swiper-bundle.css'`
 to 
`import "swiper/swiper-bundle.min.css";`

**Comment by Root-0** [comment]
I went to npm site and used command specified there to install it. I realised later that we need to install 2 packages, 1st swiper and 2nd vue-awesome-swiper. But I still got the error because as @Charlie50503  pointed out then new path is 
```import "swiper/swiper-bundle.min.css";```

**Comment by AndrewBogdanovTSS** [comment]
To anyone coming to this topic later, if you are using Swiper 6 as a dependency - follow it's official docs on how to reference css, vue-awesome-swiper use it as a peer dependency and doesn't add any extra logic on top of already existing swiper CSS structure

**Comment by imikay** [comment]
> From the official README document, we can see :
> ### Global Registration
> 
> ```
> import Vue from 'vue'
> import VueAwesomeSwiper from 'vue-awesome-swiper'
> 
> // import style (>= Swiper 6.x)
> import 'swiper/swiper-bundle.css'
> 
> // import style (<= Swiper 5.x)
> import 'swiper/css/swiper.css'
> 
> Vue.use(VueAwesomeSwiper, /* { default options with global component } */)
> ```
> 
> ### Local Registration
> 
> ```
> import { Swiper, SwiperSlide, directive } from 'vue-awesome-swiper'
> 
> // import style (>= Swiper 6.x)
> import 'swiper/swiper-bundle.css'
> 
> // import style (<= Swiper 5.x)
> import 'swiper/css/swiper.css'
> 
> export default {
>   components: {
>     Swiper,
>     SwiperSlide
>   },
>   directives: {
>     swiper: directive
>   }
> }
> ```


For anyone unclear of this, if you use swiper 6.x you should import swiper-bundle.css like this:
```
// import style (>= Swiper 6.x)
import 'swiper/swiper-bundle.css'
```
And comment out this one:

```
// import style (<= Swiper 5.x)
import 'swiper/css/swiper.css'
```

If you use Swiper 5.x, you should import swiper.css and comment out swiper-bundle.css.

**Comment by aaroncdx** [comment]
![image](https://user-images.githubusercontent.com/87127400/131882048-a06bc508-0bf9-40bb-9f32-881a7e093a61.png)
can help me with this? i even cant read the plugin in my nuxt project.

ps: please update the doc.

**Comment by oscarhandsome** [comment]
Helped downgrade
