### ISSUE TITLE
facing These issue

### ISSUE THREAD

**Issue by amaantechworld** [surmon-china/vue-awesome-swiper#698]
ERROR  Failed to compile with 1 errors                              10:00:08 PM

This dependency was not found:

* swiper/dist/css/swiper.css in ./src/main.js

To install it, you can run: npm install --save swiper/dist/css/swiper.css

**Comment by AndrewBogdanovTSS** [comment]
check docs, check what is inside node_modules folder, try creating a more meaningful issues
