### ISSUE TITLE
无法修改 pagination 等相关 Class

### ISSUE THREAD

**Issue by hoythan** [surmon-china/vue-awesome-swiper#70]
`
pagination
bulletClass
bulletActiveClass
paginationModifierClass
`
等,自定义无效

**Comment by surmon-china** [comment]
这些元素的class的本身就是通过使用者定义的，自定义无效是指？

**Comment by hoythan** [comment]
例如我将设置中的 pagination 定义为
`
pagination : '.demo-pagination',
`
它将是无效的,因为不论这里填写说明,他只认默认的 swiper-pagination

**Comment by hoythan** [comment]
http://www.swiper.com.cn/api/pagination/2014/1217/68.html
按照官方的文档理解,他应该是可自定义的.

**Comment by surmon-china** [comment]
1：没有默认组件
`<div class="my-pagination"  slot="pagination"></div>`
2：如果使用自定义元素，需要自己实现css

**Comment by surmon-china** [comment]
所有可选控件都没有默认值，完全由使用者决定内容，配置要和自己所使用的控件对应

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-awesome-swiper#use-in-spa

**Comment by hoythan** [comment]
我发现了,是我页面修改后没有更新过来,多谢.
