### ISSUE TITLE
 Installation guide of README is misleading

### ISSUE THREAD

**Issue by creanme** [surmon-china/vue-awesome-swiper#700]
#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/surmon/kLtj6h3p/

#### Steps to reproduce

`yarn add swiper vue-awesome-swiper` install 6.x swiper，it don't work.

**Comment by AndrewBogdanovTSS** [comment]
Readme was updated with more detailed instructions, please, read carefully
