### ISSUE TITLE
Swiper directive not rendering on IE 11

### ISSUE THREAD

**Issue by smartlaksh** [surmon-china/vue-awesome-swiper#703]
At the moment swiper directive not even rendering on IE 11. While integrating this into my application it started throw an error only in IE 11 & below. 

<img width="434" alt="Screen Shot 2020-08-11 at 5 24 42 PM" src="https://user-images.githubusercontent.com/147588/89965163-1eaaec80-dc1a-11ea-862b-091c859da636.png">

**Comment by smartlaksh** [comment]
![Screen Shot 2020-08-11 at 9 33 54 PM](https://user-images.githubusercontent.com/147588/89965264-63cf1e80-dc1a-11ea-85f7-7eaf60cc6fe2.png)

We do have syntax error checker in our pipeline which catches some. Looks like peer dependencies has some syntax which isn't supported by IE 11 <

**Comment by smartlaksh** [comment]
> ![Screen Shot 2020-08-11 at 9 33 54 PM](https://user-images.githubusercontent.com/147588/89965264-63cf1e80-dc1a-11ea-85f7-7eaf60cc6fe2.png)
> 
> We do have syntax error checker in our pipeline which catches some. Looks like peer dependencies has some syntax which isn't supported by IE 11 <

Apparently there is a bug in our es check ☝️ as well which doesn't print exact error. but the main issue was causing IE 11 due to ** exponentiation operator. which is in the swiper 5.4.5 itself.

**Comment by Donghoon759** [comment]
I have the same issue on IE 11, I cant access swiper directive by its name (ex. this.mySwiper)

**Comment by Donghoon759** [comment]
For my case, I use nuxt and added 'swiper', 'dom7' to transpileDependencies list and it works fine

**Comment by AndrewBogdanovTSS** [comment]
@donghoon-song I can confirm that it's working as you described. Although you can just include `swiper` to `transpile`, `dom7` is not obligatory. @smartlaksh I've created a repo for you to check how it can be done with Nuxt https://github.com/AndrewBogdanovTSS/swiper-IE11 although it's working - you will still get issues with using CSS Custom Properties in IE11 so you should use a polyfill for that. You can also create a feature request in Swiper.js main repo about providing IE11 compatibility build
