### ISSUE TITLE
Support for SwiperJs 6.0

### ISSUE THREAD

**Issue by simonmaass** [surmon-china/vue-awesome-swiper#706]
Could you please update to SwiperJs 6.0.... You updated the docs but when installing with 6.x i get NPM dependecy error:
`vue-awesome-swiper@4.1.1" has incorrect peer dependency "swiper@^5.2.0".`

**Comment by dylanbromby** [comment]
An update here would be great.

**Comment by AndrewBogdanovTSS** [comment]
@simonmaass you should install `swiper` dependency manually in your project's package.json. You can use this method for proper swiper initialization until proper support will be introduced https://github.com/surmon-china/vue-awesome-swiper/issues/680#issuecomment-666364812

**Comment by simonmaass** [comment]
@AndrewBogdanovTSS thank you!
