### ISSUE TITLE
autoplay无效,pagination也没出来 swiper v6.1.2 ,vue-awesome-swiper v4.1.1

### ISSUE THREAD

**Issue by alsonY** [surmon-china/vue-awesome-swiper#708]
组件:
 ```<div class="swiper">
      <swiper ref="mySwiper" :options="swiperOptions">
        <swiper-slide>Slide 1</swiper-slide>
        <swiper-slide>Slide 2</swiper-slide>
        <swiper-slide>Slide 3</swiper-slide>
        <swiper-slide>Slide 4</swiper-slide>
        <swiper-slide>Slide 5</swiper-slide>
        <div class="swiper-pagination" slot="pagination"></div>
      </swiper>
    </div>
<script>
export default {
  name: 'index',
  data(){
    return{
        swiperOptions: {
          loop:true, //循环切换
          autoplay: {
            delay: 1000,
          },
          pagination: {
            el: '.swiper-pagination'
          },
        }
    }
  }
}


main.js
import VueAwesomeSwiper from 'vue-awesome-swiper'
import 'swiper/swiper-bundle.css'
Vue.use(VueAwesomeSwiper)
```

**Comment by LijiaHou** [comment]
我跟你一样的问题，调了一下午也还是不行，快要气哭了，看到很多issue说降版本，可是我试了还是不显示也不自动播放，哎，真是心累

**Comment by LijiaHou** [comment]
我跟你一样的问题，也是这个版本，调了一下午也还是不行，快要气哭了，看到很多issue说降版本，可是我试了还是不显示也不自动播放，哎，真是心累

**Comment by LijiaHou** [comment]
我放弃'vue-awesome-swiper'了，在模块里使用纯净的Swiper，然后自己封装成一个组件，一切都正常了~

**Comment by alsonY** [comment]
> 我放弃'vue-awesome-swiper'了，在模块里使用纯净的Swiper，然后自己封装成一个组件，一切都正常了~

我降级到3.1.3就好了,我看到v4之后的版本是最近几个月开始维护的

**Comment by FAOfao931013** [comment]
[https://github.com/surmon-china/vue-awesome-swiper/issues/688](https://github.com/surmon-china/vue-awesome-swiper/issues/688)
这个里面有解决方案，官方文档里也有
`import Vue from 'vue'
import { Swiper as SwiperClass, Pagination, Mousewheel, Autoplay } from 'swiper/swiper.esm'
import getAwesomeSwiper from 'vue-awesome-swiper/dist/exporter'
SwiperClass.use([Pagination, Mousewheel, Autoplay])
Vue.use(getAwesomeSwiper(SwiperClass))
const { Swiper, SwiperSlide } = getAwesomeSwiper(SwiperClass)
import 'swiper/swiper-bundle.css'`

**Comment by JayeZhu** [comment]
> > 我放弃'vue-awesome-swiper'了，在模块里使用纯净的Swiper，然后自己封装成一个组件，一切都正常了~
> 
> 我降级到3.1.3就好了,我看到v4之后的版本是最近几个月开始维护的

是的，降级就可以了，谢谢

**Comment by Haiwar** [comment]
swiper还是用6.2.0吗

**Comment by RianMan** [comment]
> > > 我放弃'vue-awesome-swiper'了，在模块里使用纯净的Swiper，然后自己封装成一个组件，一切都正常了~
> > 
> > 
> > 我降级到3.1.3就好了,我看到v4之后的版本是最近几个月开始维护的
> 
> 是的，降级就可以了，谢谢

**谢谢，确实，降低了版本就行了 我的天 ～～～**

**Comment by Nicer-n** [comment]
降到3.1.3报错 可怎么办

**Comment by AndrewBogdanovTSS** [comment]
Hey guys, first of all If you would like more people to be able to help you - please, use English.
Regarding Swiper 6 usage with Awesome Swiper - right now there is only way to use it, which I described here: https://github.com/surmon-china/vue-awesome-swiper/issues/680#issuecomment-666364812
as you can see - this approach is using directive based syntax, if you aren't okay with such style - you will have to downgrade as it was already mentioned here above

**Comment by RianMan** [comment]
> Hey guys, first of all If you would like more people to be able to help you - please, use English.
> Regarding Swiper 6 usage with Awesome Swiper - right now there is only way to use it, which I described here: [#680 (comment)](https://github.com/surmon-china/vue-awesome-swiper/issues/680#issuecomment-666364812) , if you for some reason, aren't okay with provided style - you will have to downgrade as it was already mentioned here above.
> 
> P.S. Swiper.js team recently released their own implementation of Vue plugin - https://swiperjs.com/vue but it is only compatible with Vue 3, so you can try that in case you are starting new project. I really think that in some time vue-awesome-swiper will become the legacy only solution for those who can't upgrade to Vue 3 but if I were in your shoes - I would definitely upgrade. Cheers 😃

ok，use English～😁

**Comment by JayeZhu** [comment]
> Hey guys, first of all If you would like more people to be able to help you - please, use English.
> Regarding Swiper 6 usage with Awesome Swiper - right now there is only way to use it, which I described here: [#680 (comment)](https://github.com/surmon-china/vue-awesome-swiper/issues/680#issuecomment-666364812) , if you for some reason, aren't okay with provided style - you will have to downgrade as it was already mentioned here above.
> 
> P.S. Swiper.js team recently released their own implementation of Vue plugin - https://swiperjs.com/vue but it is only compatible with Vue 3, so you can try that in case you are starting new project. I really think that in some time vue-awesome-swiper will become the legacy only solution for those who can't upgrade to Vue 3 but if I were in your shoes - I would definitely upgrade. Cheers 😃

Thanks for your kind reminder!Cheers😃

**Comment by liuestc** [comment]
> > > > 我放弃'vue-awesome-swiper'了，在模块里使用纯净的Swiper，然后自己封装成一个组件，一切都正常了~
> > > 
> > > 
> > > 我降级到3.1.3就好了,我看到v4之后的版本是最近几个月开始维护的
> > 
> > 
> > 是的，降级就可以了，谢谢
> 
> **谢谢，确实，降低了版本就行了 我的天 ～～～**

降级是指vue-awesome-swiper降级还是swiper降级

**Comment by RianMan** [comment]
> > > > > 我放弃'vue-awesome-swiper'了，在模块里使用纯净的Swiper，然后自己封装成一个组件，一切都正常了~
> > > > 
> > > > 
> > > > 我降级到3.1.3就好了,我看到v4之后的版本是最近几个月开始维护的
> > > 
> > > 
> > > 是的，降级就可以了，谢谢
> > 
> > 
> > **谢谢，确实，降低了版本就行了 我的天 ～～～**
> 
> 降级是指vue-awesome-swiper降级还是swiper降级

vue-awesome-swiper降级到3.1.3

**Comment by liuestc** [comment]
> > > > > > 我放弃'vue-awesome-swiper'了，在模块里使用纯净的Swiper，然后自己封装成一个组件，一切都正常了~
> > > > > 
> > > > > 
> > > > > 我降级到3.1.3就好了,我看到v4之后的版本是最近几个月开始维护的
> > > > 
> > > > 
> > > > 是的，降级就可以了，谢谢
> > > 
> > > 
> > > **谢谢，确实，降低了版本就行了 我的天 ～～～**
> > 
> > 
> > 降级是指vue-awesome-swiper降级还是swiper降级
> 
> vue-awesome-swiper降级到3.1.3
在弱弱问句，3.1.3对应的swiper的版本是啥？

**Comment by NguyenThanh1995** [comment]
> [# 688](https://github.com/surmon-china/vue-awesome-swiper/issues/688)
> Có một giải pháp trong việc này, và cũng có trong tài liệu chính thức
> `import Vue from 'vue'`
> `import { Swiper as SwiperClass, Pagination, Mousewheel, Autoplay } from 'swiper/swiper.esm'`
> `import getAwesomeSwiper from 'vue-awesome-swiper/dist/exporter'`
> `SwiperClass.use([Pagination, Mousewheel, Autoplay])`
> `Vue.use(getAwesomeSwiper(SwiperClass))`
> `const { Swiper, SwiperSlide } = getAwesomeSwiper(SwiperClass)`
> `import 'swiper/swiper-bundle.css'`

It active

**Comment by AndrewBogdanovTSS** [comment]
Closed as duplicate

**Comment by ameibj** [comment]
> #688
> 这个里面有解决方案，官方文档里也有
> `import Vue from 'vue'`
> `import { Swiper as SwiperClass, Pagination, Mousewheel, Autoplay } from 'swiper/swiper.esm'`
> `import getAwesomeSwiper from 'vue-awesome-swiper/dist/exporter'`
> `SwiperClass.use([Pagination, Mousewheel, Autoplay])`
> `Vue.use(getAwesomeSwiper(SwiperClass))`
> `const { Swiper, SwiperSlide } = getAwesomeSwiper(SwiperClass)`
> `import 'swiper/swiper-bundle.css'`

真坑啊。 那组件内注册引入组件可以？
