### ISSUE TITLE
swiper/css/swiper.css   not found!!!!

### ISSUE THREAD

**Issue by Archmage83** [surmon-china/vue-awesome-swiper#715]
### 中文用户注意：
1. 尽量用英文描述你的 Issue，你的问题是面向世界的
2. 不要把内容堆彻在标题上，逻辑清晰地写在内容区
3. 贴代码要提前格式化好，有颜色高亮那种，贴文本，不要贴图片
4. 提问题前，务必仔细阅读 README.md；在已关闭的问题中寻找与自身相关的问题，90% 的可能它已经被解决

#### Reproduction Link
- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug.
- You could start with this template: https://jsfiddle.net/surmon/kLtj6h3p/

#### Steps to reproduce

This dependency was not found:

* swiper/css/swiper.css in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/site/Site.vue

To install it, you can run: npm install --save swiper/css/swiper.css 

I can not find swiper/css/swiper.css, I install swiper but do not find css .
#### What is actually happening?
![image](https://user-images.githubusercontent.com/68944642/93416282-0a70a400-f8d8-11ea-9fca-a8f9839a8be6.png)

**Comment by Wambosa** [comment]
Fix this by version locking `swiper` to a previous version.

```
npm install swiper@5.4.5
```

Mentioned in another ticket here.
https://github.com/surmon-china/vue-awesome-swiper/issues/704

**Comment by RushlessWu** [comment]
![image](https://user-images.githubusercontent.com/41714360/93434110-4caadd00-f8fa-11ea-834b-681965e987f1.png)
