### ISSUE TITLE
Click on navigation buttons has no effect in Nuxt / Swiper 6 / Vue-awesome-swiper 4.11

### ISSUE THREAD

**Issue by webcoderkz** [surmon-china/vue-awesome-swiper#716]
#### Reproduction Link
- https://codesandbox.io/s/thirsty-night-opmpk?file=/pages/index.vue

#### Steps to reproduce
Using Nuxt 2.4.15, use `v-swiper` directive for ssr, put some content inside it, add navigation buttons, try to click on them

#### What is Expected?
Navigation buttons should be working, navigating you between the slides.

#### What is actually happening?
Nothing, no errors in a console.

**Comment by andorfermichael** [comment]
I can confirm that.

**Comment by andorfermichael** [comment]
Only works with custom integration as described in #680

**Comment by AndrewBogdanovTSS** [comment]
Closing as duplicate. @webcoderkz use workaround described in #680 until proper support will be implemented
