### ISSUE TITLE
If there are several swipers rendering in the same page of  vue  project after i used forloop ,the  previous button and the next  button  didn't work when i clicked any of them.

### ISSUE THREAD

**Issue by 001XuemeiLi** [surmon-china/vue-awesome-swiper#717]
i used   "swiper": "^6.2.0",
    "vue": "^2.6.11",
    "vue-awesome-swiper": "^4.1.1",

 <swiper
                      class="swiper"
                      ref="swiper"
                      :options="swiperOption"
                      v-if="item.customLearnProjectList != null"
                    >
                      <swiper-slide v-for="(subItem,i) in item.customLearnProjectList" :key="i">
                        <div
                          class="background-course-list"
                          :class="[subItem.isPass ===0? 'notPass' : 'pass']"
                        >
                          <a>
                            <img :src="subItem.coursePicUrl" />
                          </a>
                          <div class="background-course-content">
                            <div>
                              <b>
                                <a href :title="subItem.courseName">{{subItem.courseName}}</a>
                              </b>
                            </div>
                            <div>
                              <span
                                :style="{backgroundColor: subItem.courseType === '必修' ? '#e02d30' : '#000000'}"
                              >{{subItem.courseType}}</span>
                              <font>{{subItem.studyNum}}人已学习</font>
                            </div>
                            <div
                              style="overflow: hidden;text-overflow: ellipsis;-webkit-line-clamp: 1;-webkit-box-orient: vertical;display: -webkit-box;"
                            >{{subItem.coursePurpose}}</div>
                          </div>
                        </div>
                      </swiper-slide>
                    </swiper>
                    <div class="swiper-button-prev prevNext" slot="button-prev" @click="prev()"></div>
                    <div class="swiper-button-next prevNext" slot="button-next" @click="next()"></div>

<script>里面的代码是这样的    prev() {
      this.$refs.swiper.$swiper.slidePrev();
    },
    next() {
      this.$refs.swiper.$swiper.slideNext();
    },
但是有很多个这个方法就不行了，如何处理呢

**Comment by AndrewBogdanovTSS** [comment]
You should use unique names for each swiper control reference. I can recommend next solution:
```
props: {
      name: {
        type: String,
        default: 'swiper' + Math.round(Math.random() * 100000)
      },
}
data() {
      return {
        swiperOptions: {
            navigation: {
            nextEl: `.swiper-button-next-${this.name}`,
            prevEl: `.swiper-button-prev-${this.name}`
          },
          pagination: {
            el: `.swiper-pagination-${this.name}`,
            dynamicBullets: true,
            type: 'bullets',
            clickable: true
          }
      }
}
```
once your controls will have unique classes - it will start to work fine
