### ISSUE TITLE
Can't find base.scss file

### ISSUE THREAD

**Issue by frenscommunity** [surmon-china/vue-awesome-swiper#720]
#### Vue.js version and component version
vue 4.5.6 and "swiper": "^6.3.1"

I can't seem to find the base.scss anywhere

I was using one of the online examples' source code, and the base.scss is called at the bottom for styling.

<template>
  <swiper class="swiper">
    <swiper-slide>Slide 1</swiper-slide>
    <swiper-slide>Slide 2</swiper-slide>
    <swiper-slide>Slide 3</swiper-slide>
    <swiper-slide>Slide 4</swiper-slide>
    <swiper-slide>Slide 5</swiper-slide>
    <swiper-slide>Slide 6</swiper-slide>
    <swiper-slide>Slide 7</swiper-slide>
    <swiper-slide>Slide 8</swiper-slide>
    <swiper-slide>Slide 9</swiper-slide>
    <swiper-slide>Slide 10</swiper-slide>
  </swiper>
</template>

<script>
  import { Swiper, SwiperSlide } from 'vue-awesome-swiper'
  import 'swiper/css/swiper.css'

  export default {
    name: 'swiper-example-default',
    title: 'Default',
    components: {
      Swiper,
      SwiperSlide
    }
  }
</script>

<style lang="scss" scoped>
  @import './base.scss';
</style>

**Comment by AndrewBogdanovTSS** [comment]
@frenscommunity provide a link on where you found this example. Generated css for swiper is located at `node_modules/swiper/swiper-bundle.min.css`
if you want to use unbundled sass/less version it's under 
`node_modules/swiper/swiper.scss`
`node_modules/swiper/swiper.less`
