### ISSUE TITLE
loop mode will make vue click event which bind on slide not work

### ISSUE THREAD

**Issue by jimmyyao88** [surmon-china/vue-awesome-swiper#722]
#### Reproduction Link
- https://jsfiddle.net/fk1vz9py/1/

**Comment by AndrewBogdanovTSS** [comment]
@jimmyyao88 this is an issue of Swiper.js lib itself. AFAIK this is done for performance reasons and might be by design. If you think otherwise - you can log an issue [here](https://github.com/nolimits4web/swiper/issues)
