### ISSUE TITLE
Touch and swipe drag not working on mobile

### ISSUE THREAD

**Issue by flamendless** [surmon-china/vue-awesome-swiper#725]
#### Vue.js version and component version
* swiper": "^6.3.2",\
* vue-awesome-swiper": "^4.1.1",
* Vue 2

#### Reproduction Link
Anything in the demo page, when viewed with Chrome "device toolbar" (Ctrl+Shift+m).

#### Steps to reproduce
Make view to mobile with "device toolbar" or (Ctrl+Shift+m),
Do a swipe touch. Left click then drag to left or right.

#### What is Expected?
It should slide to next slide.

#### What is actually happening?
No slide is happening at all

**Comment by AndrewBogdanovTSS** [comment]
@flamendless can't reproduce this issue. Provide a reproduction repo

**Comment by flamendless** [comment]
I've found out that the issue is only available when using the chrome debug tool. In actual mobile devices it works

**Comment by AndrewBogdanovTSS** [comment]
It's a common issue of Chrome Dev Tools. Try using something more sophisticated for mobile testing, e.g. BrowserStack
