### ISSUE TITLE
Vue3.0 support

### ISSUE THREAD

**Issue by jahnli** [surmon-china/vue-awesome-swiper#726]
Could you tell me the author  Do you plan to support Vue3.0 and when do you expect to implement it

**Comment by AndrewBogdanovTSS** [comment]
@jahnli I don't think this will be needed since `swiperjs` authors prepared their own Vue3 implementation which will make `vue-awesome-swiper` not needed https://swiperjs.com/vue/

**Comment by jahnli** [comment]
> @jahnli I don't think this will be needed since `swiperjs` authors prepared their own Vue3 implementation which will make `vue-awesome-swiper` not needed https://swiperjs.com/vue/

Does that mean that  vue-awesome-swiper  No longer maintained     nonsupport vue3.0

**Comment by AndrewBogdanovTSS** [comment]
I have no information about that, you better ask @surmon-china

**Comment by surmon-china** [comment]
@jahnli @AndrewBogdanovTSS 

Yes, Swiper officially has its own Vue implementation, which looks good, but vue-awesome-swiper also has a preliminary version of [Vue3 implementation](https://github.com/surmon-china/surmon.me/tree/vuniversal/src/todo/swiper).

If Swiper's official components are easy to use and stable enough, vue-awesome-swiper will no longer be updated.

**Comment by sunxiaoxue** [comment]
vue3使用swiper6 ::页面样式有，但是功能没有，，报 Failed to resolve component: swiper-slide，有点蒙，按照https://swiperjs.com/vue/这里写的，是有什么要注意的吗，能指导一下吗

**Comment by 285858315** [comment]
[https://github.com/nolimits4web/swiper](https://github.com/nolimits4web/swiper)

用原版的不香吗？

**Comment by tafelnl** [comment]
Swiper itself does now natively support Vue.js.

The following answer contains more info on this and might be of help: https://github.com/surmon-china/vue-awesome-swiper/issues/780#issuecomment-842295010

**Comment by AndrewBogdanovTSS** [comment]
@tafelnl how that answer conflicts with what @surmon-china wrote couple posts above? Swiper.js has official support for Vue 3, so I don't know what you mean when you are saying that it doesn't support Vue natively

**Comment by tafelnl** [comment]
I think you may have misinterpreted my answer. I meant to say that it _does_ support Vue 3 now

**Comment by surmon-china** [comment]
[v5.0.0](https://github.com/surmon-china/vue-awesome-swiper/tree/v5.0.0)
