### ISSUE TITLE
移动端手势滑动之后无法自动轮播了是怎么回事，求解 

### ISSUE THREAD

**Issue by dearwangzhe** [surmon-china/vue-awesome-swiper#728]
移动端手势滑动之后无法自动轮播了是怎么回事，求解 
`swiperOption: {
        pagination: '.swiper-pagination',
        loop: true,
        autoplay:3000       
      }`

**Comment by dearwangzhe** [comment]
1

**Comment by Teacher-Li** [comment]
设置disableOnInteraction：false
参考https://www.swiper.com.cn/api/autoplay/19.html
