### ISSUE TITLE
Swiper Slide Style Won't Bind

### ISSUE THREAD

**Issue by neokazemi** [surmon-china/vue-awesome-swiper#738]
Awesome Swiper 4.1.1 Vue 2.6.12

When I go to another page and refresh it around 5 times and come back to the page that I used swiper in it, swiper slide style won't work.
normally it has a element style width that makes swiper to show 5 slide in it but when it doesn't apply it shows a big single slide with width of 100% that I applied to it.

**Comment by AndrewBogdanovTSS** [comment]
@neokazemi can you provide a code sandbox example? It may be an issue with swiper initialization. You can try updating it in mounted hook, something like:
```
mounted() {
      this.$nextTick().then(() =>  this.mySwiper?.update())
    },
```

**Comment by neokazemi** [comment]
It didn't work, I fixed it with removing "display: flex" from it's parent element.

> @neokazemi can you provide a code sandbox example? It may be an issue with swiper initialization. You can try updating it in mounted hook, something like:
> 
> ```
> mounted() {
>       this.$nextTick().then(() =>  this.mySwiper?.update())
>     },
> ```
