### ISSUE TITLE
在调用 slideNext, slidePrev 方法后，autoplay 失效，不能继续自动轮播

### ISSUE THREAD

**Issue by fegg** [surmon-china/vue-awesome-swiper#75]
比如在一个按钮 click 事件里面调用这个方法：

`this.swiper.slidePrev();`

之后就不再轮播了，是需要什么配置吗？因为我看到有

`this.swiper.startAutoplay()`

这个方法，能通过配置默认点完就开始吗？

**Comment by surmon-china** [comment]
有：
`autoplayDisableOnInteraction `
http://www.swiper.com.cn/api/basic/2014/1215/19.html
