### ISSUE TITLE
slideNext 到最后一个元素的时候

### ISSUE THREAD

**Issue by fegg** [surmon-china/vue-awesome-swiper#76]
请问这个插件有无缝滚动模式吗？
如果没这种模式，那么调用 slideNext 的时候到最后一个怎么配置才能切回第一个，重新开始呢？

**Comment by fegg** [comment]
找到了, loop 模式，从刚刚的 api 里面。

**Comment by surmon-china** [comment]
loop模式下会有些许问题，在已关闭的issues中搜索`loop`可以找到问题和解决方法。
