### ISSUE TITLE
!! Improve Touch/Click Behavior to Distinguish Click From a Drag Operation

### ISSUE THREAD

**Issue by TuringJest** [surmon-china/vue-awesome-swiper#768]
Using a touch device or a device with a trackpad (MacBook etc.) clicking on a slider element doesn't always is detected as a click but drags the slider instead. This can be frustrating for users because the drag is too faint to notice and it appears as if the click is broken.

#### What is Expected?
The slider should check for the click duration to distinguish a click from a drag operation.

**Comment by mcama** [comment]
There's  a workaround to solve that behavior by setting the `threshold` option to something greater than 0, like 20px. If "touch distance" will be lower than this value then swiper will not move:

```
swiperOptions: {
    ...
    threshold: 20,
},
```

Hope it helps.

**Comment by TuringJest** [comment]
Awesome! Maybe there should be a link to the swiper documentation to understand all the options?
