### ISSUE TITLE
watchActiveIndex  was removed?

### ISSUE THREAD

**Issue by Jarvis2018** [surmon-china/vue-awesome-swiper#797]
why remove watchActiveIndex of basic options?

this’s my packages
![image](https://user-images.githubusercontent.com/36788851/123918179-31571d00-d9b6-11eb-836a-85a486a11a5c.png)

**Comment by univdev** [comment]
use ```readIndex```

**Comment by 130150469** [comment]
Hey dude, readIndex is do not work

> use `readIndex`

**Comment by univdev** [comment]
Oh sorry, my mistake.
use ```realIndex```

**Comment by 130150469** [comment]
> Oh sorry, my mistake.
> use `realIndex`
it it not work, i want to get the activeIndex when i touchMove the swiper-slide.when i touchMove,the className swiper-slide-active is change.

**Comment by 130150469** [comment]
like this
![5](https://user-images.githubusercontent.com/29725346/131298166-72510446-73ea-4b2d-b998-d9b7d29902e5.gif)

**Comment by 130150469** [comment]
> > Oh sorry, my mistake.
> > use `realIndex`
> > it it not work, i want to get the activeIndex when i touchMove the swiper-slide.when i touchMove,the className swiper-slide-active is change.



> Oh sorry, my mistake.
> use `realIndex`

now fact is , the className swiper-slide-active is changed when i touchEnd

**Comment by 130150469** [comment]
> Oh sorry, my mistake.
> use `realIndex`

can you write a demo give me? thanks

**Comment by univdev** [comment]
Sorry for late to answer it
```html
<swiper ref="swiper">
...
</swiper>
```
```javascript
mounted() {
  console.log(this.$refs.swiper.realIndex);
}
```
Like this.

**Comment by univdev** [comment]
https://swiperjs.com/swiper-api#prop-swiper-realIndex

Read this :)

**Comment by 130150469** [comment]
> https://swiperjs.com/swiper-api#prop-swiper-realIndex
> 
> Read this :)

really appreciate your. the situation has been resolved. use watchSlidesVisibility: true can replace watchActiveIndex property

**Comment by Jarvis2018** [comment]
> like this
> ![5](https://user-images.githubusercontent.com/29725346/131298166-72510446-73ea-4b2d-b998-d9b7d29902e5.gif)

后来我用 freeMode 实现的类似效果。
