### ISSUE TITLE
任何在传统js中使用？

### ISSUE THREAD

**Issue by goldencolor** [surmon-china/vue-awesome-swiper#81]
基于webview 的使用，想编译为js 单独使用 请明示

**Comment by surmon-china** [comment]
暂时是不支持的，也没配置webpack的编译环境，今晚尝试编译。

**Comment by goldencolor** [comment]
有结果吗？

**Comment by goldencolor** [comment]
@surmon-china 嗯？

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-awesome-swiper/blob/master/dist/vue-awesome-swiper.js

**Comment by surmon-china** [comment]
https://github.com/surmon-china/vue-awesome-swiper/tree/master/dist
