### ISSUE TITLE
自动切换取索引时发现bug

### ISSUE THREAD

**Issue by ithack** [surmon-china/vue-awesome-swiper#83]
我用的是vue1
 经过调试代码发现，情景如下：
 ```
<template>
<span>{{activeIndex}}---{{in}}</span>
    <swiper :options="swiperOption" class="swiperbox" :class="{swiper2:activeIndex==1,swiper3:activeIndex==2}">
         <swiper-slide class="swiperItem" v-for="(keyP,itemBox) in swiperTitle">{{activeIndex}}---{{in}}
         </swiper-slide> 
        <div class="swiper-pagination" slot="pagination"></div>
    </swiper>
</template>

 return {
        swiperOption: {
          height: 300,
          autoplay: false,//20000
          loop : true,
          autoplayDisableOnInteraction : false,
          setWrapperSize :true,
          pagination : '.swiper-pagination',
          paginationClickable :true,
          mousewheelControl : true,
          observer:true,
          observeParents:true,
          onSlideChangeStart: function(swiper){
            vm.activeIndex=swiper.realIndex;
            vm.in=swiper.activeIndex;
            console.log(vm.activeIndex,vm.in)
          }
        },
}
```
一共三个swiper-slide块，在swiper外和swiper内分别输出activeIndex和in如果按照轮播数序(0=>1=>2)正序的话 activeIndex和in 内外输出都正常，但是如果(0=>2)倒叙的话activeIndex和in两个输出都有问题，在外输出是对的，在swiper里输出就是错误的,在（0=>2）操作之后（2=>0）也有问题了；只要不是最后一个和第一个之间切换，swiper怎么切换都ok，这两个之间切换的索引永远是无法update的，求解释

**Comment by surmon-china** [comment]
实测，这个问题并不是bug，非要说问题的话就是loop模式造就的问题；
我有两个解决方法：
1. `realIndex`始终是没问题的
2. 如果你要获取当前移动中的slide，办法就多了
    + 可以直接使用swiper中的class，如[swiper-slide-duplicate, swiper-slide-active, swiper-slide-duplicate-prev...]
    + 判断下标是否大于你的数据数组的长度，若大于，则是0
    + 尝试使用其他可以代替的api

**Comment by ithack** [comment]
@surmon-china 找到问题了，是我开启了环路功能，然后在swiper里会复制两个item出来，这两个是无法和vue的数据进行实时绑定的，我把环路关了，就用个轮播既可以了

**Comment by surmon-china** [comment]
@ithack loop模式会有一些问题，不建议使用

**Comment by ithack** [comment]
@surmon-china 是不是loop下，swiper自己复制了两个节点，但是并没用在vm里所以导致的问题？vue2.0应该也会出现这个问题吧

**Comment by surmon-china** [comment]
@ithack 对，loop是复制了dom，但不会复制dom之外的任何东西，所以点击事件什么的都会失效，即便是使用原生的swiper也是这样的问题，官方一直没修复，我尝试过优化，目前没办法

**Comment by ithack** [comment]
@surmon-china 收到！谢谢！

**Comment by struggle-fish** [comment]
重新对需要循环的slide个数进行计算，当你改变了slidesPerView参数时需要用到，这个方法是mySwiper.destroyLoop()和 mySwiper.createLoop()的结合体。
mySwiper.reLoop()参数
