### ISSUE TITLE
Is vue3.0 supported?

### ISSUE THREAD

**Issue by XWQ2018** [surmon-china/vue-awesome-swiper#842]
When will vue3.0 be available?

**Comment by AO-IO** [comment]
swiper js currently supports vue js 3 by default . 

[https://swiperjs.com/vue](SwiperJs Vue 3)

**Comment by AO-IO** [comment]
Swiper Js support Vue.js 3 out of the box .

[Swiper Vue.js Components](https://swiperjs.com/vue)

**Comment by AO-IO** [comment]
You don't need  this component for vue 3 . swiper already support vue 3 out of the box.

[Swiper Vue.js Components](https://swiperjs.com/vue)

**Comment by AO-IO** [comment]
[[> This package is based on the famous [`swiper`](https://swiperjs.com/)
> 
> As of [late 2020](https://github.com/nolimits4web/swiper/commit/423fa86d98459415e369c84e6ac54d511f2b1406#diff-33b720d4a4ce860d6322620c49aa809a09a73c55b051e8f5ea4b56c31477ddd6) they support Vue.js out of the box! (Though you must at least use Vue.js version 3). So you should migrate to that if you can.
> 
> More info here: https://swiperjs.com/vue

](https://github.com/surmon-china/vue-awesome-swiper/issues/780#issuecomment-842295010)](https://github.com/surmon-china/vue-awesome-swiper/issues/780#issuecomment-842295010)

**Comment by AO-IO** [comment]
As of [late 2020](https://github.com/nolimits4web/swiper/commit/423fa86d98459415e369c84e6ac54d511f2b1406#diff-33b720d4a4ce860d6322620c49aa809a09a73c55b051e8f5ea4b56c31477ddd6) they support Vue.js out of the box! (Though you must at least use Vue.js version 3). So you should migrate to that if you can.

More info here: https://swiperjs.com/vue

**Comment by AO-IO** [comment]
As of [late 2020](https://github.com/nolimits4web/swiper/commit/423fa86d98459415e369c84e6ac54d511f2b1406#diff-33b720d4a4ce860d6322620c49aa809a09a73c55b051e8f5ea4b56c31477ddd6) they support Vue.js out of the box! (Though you must at least use Vue.js version 3).

More info here: https://swiperjs.com/vue

**Comment by XWQ2018** [comment]
> As of [late 2020](https://github.com/nolimits4web/swiper/commit/423fa86d98459415e369c84e6ac54d511f2b1406#diff-33b720d4a4ce860d6322620c49aa809a09a73c55b051e8f5ea4b56c31477ddd6) they support Vue.js out of the box! (Though you must at least use Vue.js version 3).
> 
> More info here: https://swiperjs.com/vue

Thank you for your reply. I have checked that Swiper supports Vue3.0

**Comment by surmon-china** [comment]
[v5.0.0](https://github.com/surmon-china/vue-awesome-swiper/tree/v5.0.0)
