### ISSUE TITLE
Vue-awesome-swiper on the Macbook, Monterey 12.2.1, M1

### ISSUE THREAD

**Issue by TangoPJ** [surmon-china/vue-awesome-swiper#845]
Hi all, I'm trying to install this swiper on my Vue 3 project by using command:
`npm install swiper vue-awesome-swiper --save`

But I'm getting an error, like I show in the attach screenshot:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/64611024/158049816-1d907dae-5664-4140-a7db-82183c9e5979.png">

What am I doing wrong?

P.s. MacOS Monterey 12.2.1, M1

**Comment by surmon-china** [comment]
Please use [v5.x version](https://github.com/surmon-china/vue-awesome-swiper/tree/v5.0.0).
