### ISSUE TITLE
Can't install vue-awesome-swiper 4.1.1

### ISSUE THREAD

**Issue by Zuenda25** [surmon-china/vue-awesome-swiper#852]
### Describe the bug

When i try running command npm i or npm i vue-awesome-swiper, i get error message _C:\Personal\Projects\ropanasuri-cms\node_modules\swiper command failed_ 

### Reproduction

` "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext \".js,.vue\" --ignore-path .gitignore .",
    "lint:prettier": "prettier --check .",
    "lint": "npm run lint:js && npm run lint:prettier",
    "lintfix": "prettier --write --list-different . && npm run lint:js -- --fix",
    "pm2-start": "npx pm2 start npm --name \"rskb-ropanasuri\" --interpreter bash -- start"
  },
  "dependencies": {
    "@nuxtjs/axios": "^5.13.6",
    "@vue-hero-icons/outline": "^1.7.2",
    "core-js": "^3.25.3",
    "nuxt": "^2.15.8",
    "vue": "^2.7.10",
    "vue-dragscroll": "^4.0.5",
    "vue-server-renderer": "^2.7.10",
    "vue-template-compiler": "^2.7.10",
    "swiper": "^5.4.5",
    "vue-awesome-swiper": "^4.1.1"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.19.1",
    "@nuxt/typescript-build": "^2.1.0",
    "@nuxtjs/eslint-config": "^11.0.0",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/eslint-module": "^3.1.0",
    "@nuxtjs/tailwindcss": "^5.3.3",
    "eslint": "^8.24.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-vue": "^9.5.1",
    "postcss": "^8.4.17",
    "prettier": "^2.7.1"
  }`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 1.35 GB / 15.74 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.125
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/eslint-parser: ^7.19.1 => 7.19.1
    @nuxt/typescript-build: ^2.1.0 => 2.1.0
    @nuxtjs/axios: ^5.13.6 => 5.13.6
    @nuxtjs/eslint-config: ^11.0.0 => 11.0.0
    @nuxtjs/eslint-config-typescript: ^12.0.0 => 12.0.0
    @nuxtjs/eslint-module: ^3.1.0 => 3.1.0
    @nuxtjs/tailwindcss: ^5.3.3 => 5.3.5
    @vue-hero-icons/outline: ^1.7.2 => 1.7.2
    eslint: ^8.24.0 => 8.31.0
    eslint-config-prettier: ^8.5.0 => 8.6.0
    eslint-plugin-nuxt: ^4.0.0 => 4.0.0
    eslint-plugin-vue: ^9.5.1 => 9.8.0
    nuxt: ^2.15.8 => 2.15.8
    postcss: ^8.4.17 => 8.4.21
    prettier: ^2.7.1 => 2.8.2
    swiper: ^5.4.5 => 5.4.5
    vue: ^2.7.10 => 2.7.14
    vue-awesome-swiper: ^4.1.1 => 4.1.1
    vue-dragscroll: ^4.0.5 => 4.0.5
    vue-server-renderer: ^2.7.10 => 2.7.14
    vue-template-compiler: ^2.7.10 => 2.7.14
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ybhwang** [comment]
I got this error!

```shell
npm ERR! Could not resolve dependency:
npm ERR! peer swiper@"^5.2.0" from vue-awesome-swiper@4.1.1
npm ERR! node_modules/vue-awesome-swiper
npm ERR!   vue-awesome-swiper@"^4.1.1" from the root project
```
