### ISSUE TITLE
怎么样在vue里使用slideNext和slidePrev方法

### ISSUE THREAD

**Issue by Jenny-lzg** [surmon-china/vue-awesome-swiper#86]
### 中文用户请注意：

1. 我想在vue里使用	slideNext的方法，已经能拿到swiper的那个div了，但是参考api写的时候无效，即不报错，也没有翻页。
  		  
### Got a question?
I want use the slideNext/slidePrev API in vue，can you show a demo to me?
when i click the next button, it always told me slideNext is not a function

**Comment by surmon-china** [comment]
#48 
#36

**Comment by surmon-china** [comment]
`this.$refs.[mySwiper].swiper`用于得到当前的swiper实例，然后进行api操作。

**Comment by tedjsmeng** [comment]
这个swiper有写在data 的 return里面吗
我也遇到这个问题，看了这一篇就解决了http://blog.csdn.net/Zhooson/article/details/78348023

**Comment by asdzsc** [comment]
computed: {
    swiper() {
      return this.$refs.noticeSwiper.$swiper
    },
  },
计算属性返回一个最新的swiper实例，然后就可以在方法中调用 this.swiper.slideNext()等swiper身上的方法
