### ISSUE TITLE
23-thumbs-gallery.vue safari bug

### ISSUE THREAD

**Issue by evolutionjay** [surmon-china/vue-awesome-swiper#88]
23-thumbs-gallery.vue
这个例子

如果是用一个 v-if 加载进来的 component 

在Safari下会各种错位，等我写个demo

**Comment by Melin00** [comment]
想问下23-thumbs-gallery.vue下面的图片swiper不可以左对齐的么? 我看配置是居中对齐才有效果, 请问怎么解决呢?

**Comment by surmon-china** [comment]
@Melin00 `centeredSlides: false`

**Comment by evolutionjay** [comment]
知道问题了，如果 下面用于做 control 的swiper ，如果每个 slider 的宽度不是固定，而是自由宽度，就会出bug

**Comment by SpringLIAO** [comment]
@Melin00 我也遇到这个问题了，请问你解决了吗？
