### ISSUE TITLE
请问IE兼容到什么版本？

### ISSUE THREAD

**Issue by tinytonny** [surmon-china/vue-awesome-swiper#90]
在IE9浏览器报错，vue版本2.3.2
![qq 20170526095632](https://cloud.githubusercontent.com/assets/9532284/26477660/bfc1c972-41f9-11e7-80fd-f8ee70d0f0a3.png)

**Comment by surmon-china** [comment]
@tinytonny 需要更具体的错误堆栈信息

**Comment by mwnubd** [comment]
ie9 兼容有问题

**Comment by mwnubd** [comment]
@tinytonny ie9兼容有问题

**Comment by mwnubd** [comment]
@surmon-china ie9兼容有问题

**Comment by surmon-china** [comment]
@tinytonny 应该是`notNextTick`设置为true

@mwnubd swiper3极有可能不支持IE9

**Comment by zlxbuzz** [comment]
ie9 不支持`classList` 加一个polyfill就行

**Comment by xjccc** [comment]
@zlxbuzz 我看是不是没有添加上transform：translate属性导致没有办法切换的？
