### ISSUE TITLE
i have a warning,

### ISSUE THREAD

**Issue by webstermobile** [surmon-china/vue-awesome-swiper#95]
(Emitted value instead of an instance of Error) <swiper-slide v-for="slide in swiperSlides">: component lists rendered with v-for should have explicit keys. 
the following is my code:
`<swiper :options="swiperOption" ref="mySwiper" v-if="swiperSlides.length > 0">
		
		<swiper-slide v-for="slide in swiperSlides">
			<div class="count-wrap " 
			v-bind:class="{greenstyle:slide.foodUseable < 55,bluestyle:slide.foodUseable >= 55 && slide.foodUseable <= 70}">
				<div class="count-inner">
					<div class="count-text">血糖指数</div>
					<div class="count-num"><span v-bind:class="{hightip:slide.foodUseable > 70}">{{slide.foodUseable}}</span></div>
				</div>
			</div>`
how to fix this problem?

**Comment by F-loat** [comment]
Please format your code at first.
Just add a prop `key` with your `slide.id` or `index`.
``` vue
<swiper :options="swiperOption" ref="mySwiper" v-if="swiperSlides.length > 0">
  <!-- slides -->
  <swiper-slide v-for="(slide, index) in swiperSlides" :key="index">
    <div class="count-wrap " v-bind:class="{greenstyle:slide.foodUseable < 55,bluestyle:slide.foodUseable >= 55 && slide.foodUseable <= 70}">
      <div class="count-inner">
        <div class="count-text">血糖指数</div>
        <div class="count-num">
          <span v-bind:class="{hightip:slide.foodUseable > 70}">{{slide.foodUseable}}</span>
        </div>
      </div>
    </div>
  </swiper-slide>
</swiper>
```
